/* Question bank. u = unit id, o = options, a = index of the correct option. */
(function () {
  var Q = function (u, q, o, a, e) { return { u: u, q: q, o: o, a: a, e: e }; };

  GEO.questions = [

  /* ---- 1.1 ---- */
  Q('1.1', 'What is the birth rate?',
    ['The number of live births per 1000 people per year', 'The number of children per woman', 'The percentage increase in population each year', 'The number of births per family'],
    0, 'Fertility rate is children per woman. Birth rate is always per 1000 people per year.'),
  Q('1.1', 'Natural increase is calculated by:',
    ['Birth rate minus death rate', 'Birth rate plus immigration', 'Births minus emigration', 'Total births minus total deaths plus net migration'],
    0, 'Natural increase deliberately excludes migration. Adding migration gives total population growth instead.'),
  Q('1.1', 'Which stage of the DTM has a high birth rate and a rapidly falling death rate?',
    ['Stage 2', 'Stage 1', 'Stage 3', 'Stage 4'],
    0, 'Stage 2 is early expanding: death rate falls through better healthcare and sanitation while birth rate stays high, so growth is fastest.'),
  Q('1.1', 'A country in stage 5 of the DTM will have:',
    ['A death rate higher than its birth rate', 'A very high birth rate', 'A rapidly falling death rate', 'A high infant mortality rate'],
    0, 'Stage 5 is natural decrease: births fall below deaths, so the population shrinks without migration. Japan and Italy are examples.'),
  Q('1.1', 'Which of these best explains a high birth rate in a lower income country?',
    ['High infant mortality means parents have more children expecting some to die', 'Widely available state pensions', 'High levels of female employment', 'Low infant mortality'],
    0, 'The other three all push the birth rate down. High infant mortality pushes it up.'),
  Q('1.1', 'Over-population means:',
    ['Too many people for the resources and technology available', 'A population density above 300 per km²', 'A population of more than 100 million', 'More people than houses'],
    0, 'It is about the balance between people and resources, not about a particular number or density.'),
  Q('1.1', 'Which country is the standard example of under-population?',
    ['Australia', 'Bangladesh', 'Niger', 'India'],
    0, 'Australia has vast resources and a small population, so it cannot exploit them fully. Bangladesh and Niger are usually cited as over-populated.'),
  Q('1.1', 'Which is a pro-natalist measure?',
    ['Cash payments and subsidised childcare for families with children', 'Fines for having a second child', 'Free contraception campaigns', 'Raising the legal age of marriage'],
    0, 'Pro-natalist policies encourage births. The other three all discourage them.'),
  Q('1.1', 'A birth rate of 32 and a death rate of 8 gives a natural increase of:',
    ['2.4% per year', '24% per year', '4% per year', '0.24% per year'],
    0, '32 minus 8 is 24 per 1000. Divide by 10 to get a percentage: 2.4%.'),

  /* ---- 1.2 ---- */
  Q('1.2', 'Which of these is a push factor?',
    ['Crop failure caused by drought', 'Better schools in the destination', 'Higher wages abroad', 'Family already living in the city'],
    0, 'Push factors are negative conditions in the source area. The other three attract people to a destination.'),
  Q('1.2', 'A refugee is best defined as someone who:',
    ['Has been forced to leave their country to escape war, persecution or disaster', 'Moves abroad to find better paid work', 'Has applied for asylum and is awaiting a decision', 'Moves from the countryside to a city'],
    0, 'Someone awaiting a decision is an asylum seeker; someone moving for work is an economic migrant.'),
  Q('1.2', 'Which is a disadvantage of emigration for the source country?',
    ['Loss of skilled workers, known as brain drain', 'Reduced pressure on housing', 'Remittances sent home', 'Lower unemployment'],
    0, 'The other three are advantages for the country people leave.'),
  Q('1.2', 'Remittances are:',
    ['Money sent home by migrants working abroad', 'Payments made to a government for a visa', 'Aid given to refugees', 'Taxes paid by immigrants'],
    0, 'For several countries remittances are among the largest sources of foreign income.'),
  Q('1.2', 'Which best describes forced migration?',
    ['People flee civil war with no realistic alternative', 'A graduate moves abroad for a higher salary', 'A family moves to the coast on retirement', 'A farmer moves to the city hoping for factory work'],
    0, 'The other three are voluntary, even where the economic pressure is strong.'),
  Q('1.2', 'Roughly how many Syrians left the country as refugees during the civil war?',
    ['About 6.8 million', 'About 500,000', 'About 25 million', 'About 100,000'],
    0, 'Roughly 6.8 million left, with a similar number displaced inside Syria, out of a pre-war population of about 22 million.'),

  /* ---- 1.3 ---- */
  Q('1.3', 'A population pyramid with a very wide base indicates:',
    ['A high birth rate', 'A high death rate', 'A long life expectancy', 'High immigration'],
    0, 'The base shows the youngest age groups, so a wide base means many births.'),
  Q('1.3', 'The dependency ratio is calculated as:',
    ['(under 15 + over 64) ÷ 15–64, × 100', '(over 64) ÷ total population, × 100', '(under 15) ÷ (over 64), × 100', 'total population ÷ working population'],
    0, 'It expresses the number of dependants for every 100 people of working age.'),
  Q('1.3', 'Which is a problem caused by an ageing population?',
    ['Rising cost of state pensions and healthcare', 'Not enough school places', 'A very high birth rate', 'Rapid growth of squatter settlements'],
    0, 'The others are associated with a youthful, rapidly growing population.'),
  Q('1.3', 'An indent partway up one side of a population pyramid most likely shows:',
    ['A past event such as war, epidemic or emigration affecting that cohort', 'A rising birth rate', 'Improved healthcare', 'A fall in infant mortality'],
    0, 'A missing cohort points to a specific event that removed or never produced that age group.'),
  Q('1.3', 'Which response to an ageing population increases the size of the workforce fastest?',
    ['Encouraging immigration of working-age people', 'Pro-natalist payments for new babies', 'Building more care homes', 'Raising the school leaving age'],
    0, 'Babies take about twenty years to reach the workforce. Migrants of working age join it immediately.'),

  /* ---- 1.4 ---- */
  Q('1.4', 'Population density is:',
    ['The average number of people per square kilometre', 'The way people are spread across an area', 'The total population of a country', 'The rate at which population grows'],
    0, 'The way people are spread out is distribution, which is described rather than calculated.'),
  Q('1.4', 'Which physical factor encourages dense population?',
    ['Flat land with fertile alluvial soil', 'Steep mountain slopes', 'Very low, unreliable rainfall', 'Permanently frozen ground'],
    0, 'The other three all discourage settlement and give sparse populations.'),
  Q('1.4', 'Egypt has a low national population density but very uneven distribution because:',
    ['Almost the whole population lives along the Nile', 'Its cities are evenly spread', 'The desert is densely settled', 'It has a very small total population'],
    0, 'Egypt is the standard example of the difference between density and distribution.'),
  Q('1.4', 'Which area would you expect to be sparsely populated?',
    ['The Amazon rainforest interior', 'The Ganges valley', 'Java', 'Western Europe'],
    0, 'Dense rainforest has poor soils once cleared, difficult access and disease risk.'),

  /* ---- 1.5 ---- */
  Q('1.5', 'The site of a settlement means:',
    ['The actual land on which it is built', 'Its position relative to other settlements', 'The services it provides', 'The number of people living there'],
    0, 'Position relative to the surrounding area is situation.'),
  Q('1.5', 'A settlement built inside a river meander was most likely chosen for:',
    ['Defence', 'A water supply only', 'Shelter from wind', 'Flat land'],
    0, 'Water on three sides makes attack difficult, which is the classic defensive site.'),
  Q('1.5', 'Threshold population is:',
    ['The minimum number of people needed to support a service', 'The maximum distance people will travel to a service', 'The population of the largest settlement', 'The number of people using a service each day'],
    0, 'The maximum distance travelled is the range.'),
  Q('1.5', 'Which is a high order service?',
    ['A university', 'A newsagent', 'A postbox', 'A village shop'],
    0, 'High order services need a large threshold, are used rarely and have a long range.'),
  Q('1.5', 'As you move up the settlement hierarchy, settlements become:',
    ['Larger, fewer and further apart', 'Larger, more numerous and closer together', 'Smaller and fewer', 'Larger but closer together'],
    0, 'Bigger settlements are rarer, so they are spaced further apart and each serves a wider area.'),
  Q('1.5', 'Buildings strung out along a single road form a settlement pattern described as:',
    ['Linear', 'Nucleated', 'Dispersed', 'Concentric'],
    0, 'Nucleated means clustered; dispersed means scattered with gaps between.'),

  /* ---- 1.6 ---- */
  Q('1.6', 'Why are buildings in the CBD usually tall?',
    ['Land values are highest, so building upwards uses the space efficiently', 'Planning laws require it', 'The ground is more stable there', 'It reduces traffic congestion'],
    0, 'High accessibility drives up land prices, so the site must generate as much floor space as possible.'),
  Q('1.6', 'In many cities of lower income countries, the poorest housing is found:',
    ['On the outskirts, in squatter settlements', 'In the CBD', 'In the suburbs', 'Along the main ring road'],
    0, 'This is the reverse of the pattern in most higher income cities, where the poorest housing is in the inner city.'),
  Q('1.6', 'The Hoyt model differs from the Burgess model because it:',
    ['Shows land use developing in wedges along transport routes', 'Has no CBD', 'Places industry in the suburbs', 'Applies only to lower income countries'],
    0, 'Hoyt added transport, so zones form sectors radiating from the centre rather than complete rings.'),
  Q('1.6', 'A brownfield site is:',
    ['Land that has been built on before and is available for redevelopment', 'Farmland at the edge of a city', 'Protected open land around a city', 'Land contaminated beyond use'],
    0, 'Undeveloped land is greenfield; protected open land is green belt.'),
  Q('1.6', 'Which is a solution to urban traffic congestion?',
    ['Park and ride schemes on the edge of the city', 'Building more city-centre car parks', 'Removing bus lanes', 'Widening residential streets'],
    0, 'Park and ride intercepts cars before they reach the congested centre.'),

  /* ---- 1.7 ---- */
  Q('1.7', 'Urbanisation is:',
    ['An increase in the proportion of people living in towns and cities', 'The growth of a city\'s total population', 'The spread of a city into the countryside', 'Movement of people out of cities'],
    0, 'It is a proportion. Outward spread is urban sprawl; movement out of cities is counter-urbanisation.'),
  Q('1.7', 'Rapid urban growth in lower income countries is caused by:',
    ['Rural-urban migration and high natural increase in the city', 'Rural-urban migration alone', 'International immigration alone', 'Counter-urbanisation'],
    0, 'Migrants are mostly young adults, so the city then has a high birth rate too. Both causes are needed for full marks.'),
  Q('1.7', 'Squatter settlements are often built on marginal land such as steep slopes because:',
    ['It is unwanted by others, so it can be occupied without buying it', 'It is safer during storms', 'The government provides it free', 'Soil there is more fertile'],
    0, 'Residents have no legal title, so they occupy land nobody else wants, which is usually the most hazardous.'),
  Q('1.7', 'In a site and service scheme:',
    ['Land is laid out with water, sewerage and power before residents build their own homes', 'The settlement is bulldozed and replaced with flats', 'Residents are given completed houses free', 'Nothing is done until residents can pay'],
    0, 'It combines official infrastructure with self-build labour, so it is cheaper than full rehousing.'),
  Q('1.7', 'A criticism of clearing a squatter settlement and rehousing residents in high-rise flats is that:',
    ['It destroys the home-based businesses people depend on', 'It provides no sanitation', 'It is always cheaper than upgrading', 'It keeps communities together'],
    0, 'Small flats cannot house workshops, and vertical living breaks the ground-level trade networks that generate income.'),
  Q('1.7', 'Roughly what is Dharavi\'s area?',
    ['About 2 km²', 'About 20 km²', 'About 200 km²', 'About 0.2 km²'],
    0, 'Roughly 2.1 km² holding several hundred thousand people, which is why density is so extreme.'),

  /* ---- 2.1 ---- */
  Q('2.1', 'Plates move because of:',
    ['Convection currents in the mantle', 'The rotation of the Earth', 'Tides in the oceans', 'The pull of the Moon'],
    0, 'Heat from the core drives circulation in the semi-molten mantle, which drags the plates.'),
  Q('2.1', 'At a destructive margin the oceanic plate subducts because it is:',
    ['Denser than the continental plate', 'Thinner than the continental plate', 'Older than the continental plate', 'Moving faster'],
    0, 'Density is the reason. Oceanic crust is thinner and younger too, but density is what makes it sink.'),
  Q('2.1', 'Which margin produces fold mountains but no volcanoes?',
    ['Collision', 'Constructive', 'Destructive', 'Hot spot'],
    0, 'Neither continental plate subducts, so no magma is generated. The Himalayas are the example.'),
  Q('2.1', 'The San Andreas Fault is an example of a:',
    ['Conservative margin', 'Constructive margin', 'Destructive margin', 'Collision margin'],
    0, 'Plates slide past one another, so there are earthquakes but no volcanoes.'),
  Q('2.1', 'The focus of an earthquake is:',
    ['The point underground where the earthquake starts', 'The point on the surface above where it starts', 'The area of greatest damage', 'The centre of the plate'],
    0, 'The point on the surface directly above the focus is the epicentre.'),
  Q('2.1', 'The Richter scale measures:',
    ['Magnitude, the energy released', 'Intensity, the observed effects', 'Depth of focus', 'Distance from the epicentre'],
    0, 'Observed effects are measured by the Mercalli scale.'),
  Q('2.1', 'Composite volcanoes are found at destructive margins and have:',
    ['Steep sides built of alternating ash and viscous lava', 'Gentle slopes built of runny basaltic lava', 'No crater', 'Only effusive eruptions'],
    0, 'The runny basaltic description belongs to shield volcanoes at constructive margins and hot spots.'),
  Q('2.1', 'A lahar is:',
    ['A mudflow of volcanic ash mixed with water', 'A cloud of superheated gas and ash', 'A flow of runny lava', 'A crack in the Earth\'s crust'],
    0, 'The superheated gas and ash cloud is a pyroclastic flow.'),
  Q('2.1', 'Which is a secondary effect of an earthquake?',
    ['A tsunami', 'Buildings collapsing during the shaking', 'Roads cracking open', 'People injured by falling masonry'],
    0, 'Secondary effects follow on afterwards rather than being caused directly by the shaking.'),
  Q('2.1', 'The main reason so many died in the 2010 Haiti earthquake was:',
    ['Poor building quality and no enforced building codes', 'The extremely high magnitude', 'A very deep focus', 'It struck in the middle of the night'],
    0, 'At magnitude 7.0 with a shallow focus, it was the vulnerability of the buildings and the lack of preparation that made it catastrophic.'),
  Q('2.1', 'Why did over 200,000 people survive the 1991 Pinatubo eruption?',
    ['Monitoring gave weeks of warning and they were evacuated', 'The eruption was very small', 'The volcano is in a remote area', 'Buildings were earthquake-proof'],
    0, 'Seismic swarms, ground deformation and rising sulphur dioxide allowed an evacuation before the main eruption.'),
  Q('2.1', 'Why do people continue to live near volcanoes?',
    ['Volcanic soils are very fertile and there is geothermal energy and tourism', 'Eruptions never kill anyone', 'Governments pay them to stay', 'Land there is the most expensive'],
    0, 'Frequent benefits outweigh a rare risk, and many residents are too poor to move anyway.'),

  /* ---- 2.2 ---- */
  Q('2.2', 'A watershed is:',
    ['The boundary of a drainage basin, usually high ground', 'The point where two rivers meet', 'Where a river enters the sea', 'A waterfall'],
    0, 'The meeting point of two rivers is a confluence; the river mouth is where it enters the sea.'),
  Q('2.2', 'Which erosion process makes pebbles smaller and rounder?',
    ['Attrition', 'Abrasion', 'Hydraulic action', 'Solution'],
    0, 'Attrition acts on the load itself. Abrasion is the load wearing away the bed and banks.'),
  Q('2.2', 'Fine silt and clay carried within the flow are transported by:',
    ['Suspension', 'Traction', 'Saltation', 'Solution'],
    0, 'Solution is dissolved material; traction rolls the largest boulders along the bed.'),
  Q('2.2', 'On a meander, deposition occurs:',
    ['On the inside of the bend, where flow is slowest', 'On the outside of the bend', 'In the deepest part of the channel', 'Evenly across the channel'],
    0, 'The fastest, deepest flow swings to the outside and erodes it, forming a river cliff.'),
  Q('2.2', 'A waterfall retreats upstream because:',
    ['Undercutting removes soft rock until the hard overhang collapses', 'The river slows down', 'Deposition builds up at the base', 'The plunge pool fills with sediment'],
    0, 'Repeated collapse and retreat leaves a gorge downstream.'),
  Q('2.2', 'Levées form because:',
    ['The coarsest sediment is deposited first, right beside the channel', 'People build them from concrete', 'The river erodes its banks vertically', 'Fine silt settles nearest the channel'],
    0, 'Natural levées are depositional. The finest material travels furthest across the floodplain.'),
  Q('2.2', 'Deltas form where:',
    ['A river loses velocity entering a sea or lake and deposits its load faster than it can be removed', 'A river erodes a deep gorge', 'Two rivers meet', 'A river crosses hard rock'],
    0, 'Flocculation in salt water helps fine clay settle, and the channel splits into distributaries.'),
  Q('2.2', 'Which increases flood risk?',
    ['Urbanisation covering the ground with tarmac', 'Afforestation in the upper basin', 'Permeable rock across the basin', 'A long, narrow drainage basin'],
    0, 'Impermeable surfaces convert slow throughflow into fast surface runoff, so water reaches the channel sooner.'),
  Q('2.2', 'Which is soft engineering?',
    ['Floodplain zoning', 'Building a concrete flood wall', 'Dredging the channel', 'Constructing a dam'],
    0, 'Soft engineering works with natural processes rather than building structures to control the river.'),
  Q('2.2', 'Velocity is often higher in the lower course than the upper course because:',
    ['The channel is smoother and deeper, so there is less friction', 'The gradient is steeper there', 'There is less water', 'The load is larger'],
    0, 'This is counter-intuitive but frequently examined: friction, not gradient, dominates.'),
  Q('2.2', 'Which is a benefit of the Three Gorges Dam?',
    ['Flood control on a river with a long history of deadly floods', 'It increased sediment supply to the delta', 'It required no resettlement', 'It reduced landslide risk in the valley'],
    0, 'Sediment is now trapped behind the dam, 1.3 million people were relocated, and landslides increased.'),

  /* ---- 2.3 ---- */
  Q('2.3', 'Destructive waves are characterised by:',
    ['A strong backwash and a weak swash', 'A strong swash and weak backwash', 'A long wavelength', 'A low height'],
    0, 'The strong backwash drags material back out to sea, so the beach is eroded.'),
  Q('2.3', 'Fetch is:',
    ['The distance of open water the wind blows across', 'The height of a wave', 'The distance a wave travels up a beach', 'The time between waves'],
    0, 'A longer fetch gives the wind more time and distance to transfer energy, so waves are larger.'),
  Q('2.3', 'In longshore drift, the backwash moves material:',
    ['Straight down the beach at right angles to the shore', 'At an angle, in the direction of the prevailing wind', 'Parallel to the shore', 'Up the beach'],
    0, 'The swash arrives at an angle but gravity pulls the backwash straight down, producing the zig-zag.'),
  Q('2.3', 'The correct sequence of headland erosion is:',
    ['Crack, cave, arch, stack, stump', 'Cave, stack, arch, stump', 'Arch, cave, stump, stack', 'Stack, arch, cave, crack'],
    0, 'Waves exploit a weakness, widen it into a cave, cut through to form an arch, which collapses to a stack and then a stump.'),
  Q('2.3', 'A wave-cut platform forms as a result of:',
    ['Repeated undercutting at a wave-cut notch causing the cliff to retreat', 'Deposition at the base of a cliff', 'Longshore drift along the shore', 'A fall in sea level'],
    0, 'The platform is what is left behind as the cliff line moves inland.'),
  Q('2.3', 'A spit forms where:',
    ['The coastline changes direction and longshore drift continues across open water', 'Two headlands meet', 'A river deposits its load inland', 'Waves erode a bay'],
    0, 'The sheltered water behind a spit often becomes salt marsh.'),
  Q('2.3', 'Coral needs which conditions?',
    ['Warm, shallow, clear, salty water', 'Cold, deep water', 'Fresh water with high sediment', 'Warm water with heavy silt'],
    0, 'Sunlight must reach the algae inside the polyps, so clarity and shallow depth are essential.'),
  Q('2.3', 'Coral bleaching happens when:',
    ['Stress, usually heat, makes coral expel the algae living inside it', 'Coral is covered by sand', 'Fish eat the coral', 'Sea level falls'],
    0, 'Without the algae the coral loses colour and its main food source, and dies if the stress continues.'),
  Q('2.3', 'The main drawback of groynes is that they:',
    ['Starve the coast further along by trapping sediment', 'Are extremely expensive', 'Reflect wave energy back to sea', 'Cannot be built on sandy beaches'],
    0, 'This is terminal groyne syndrome, seen clearly at Mappleton and Cowden on the Holderness coast.'),
  Q('2.3', 'Holderness erodes so quickly mainly because:',
    ['The cliffs are made of soft boulder clay', 'It faces a very short fetch', 'It is made of resistant chalk', 'It has very wide beaches'],
    0, 'Soft, unconsolidated clay slumps when wet and is easily removed, and the beaches are narrow.'),

  /* ---- 2.4 ---- */
  Q('2.4', 'Climate is:',
    ['The average weather of a place over at least 30 years', 'The weather on a single day', 'The temperature at midday', 'The rainfall in one month'],
    0, 'Weather is short-term and specific; climate is the long-term average.'),
  Q('2.4', 'A Stevenson screen is painted white because:',
    ['It reflects sunlight so the thermometers record air temperature', 'It is easier to see', 'White paint resists rust', 'It attracts less wildlife'],
    0, 'A dark screen would absorb heat and give readings that are too high.'),
  Q('2.4', 'Which instrument measures wind speed?',
    ['Anemometer', 'Wind vane', 'Barometer', 'Hygrometer'],
    0, 'A wind vane gives direction; a barometer gives pressure; a hygrometer gives humidity.'),
  Q('2.4', 'Cloud cover is measured in:',
    ['Oktas', 'Millibars', 'Millimetres', 'Degrees'],
    0, 'An okta is one eighth of the sky, so 8 oktas means completely overcast.'),
  Q('2.4', 'Rain formed when moist air is forced to rise over mountains is:',
    ['Relief rainfall', 'Convectional rainfall', 'Frontal rainfall', 'Cyclonic rainfall'],
    0, 'The sheltered leeward side then lies in a rain shadow.'),
  Q('2.4', 'Heavy afternoon thunderstorms caused by strong surface heating are:',
    ['Convectional rainfall', 'Relief rainfall', 'Frontal rainfall', 'Orographic rainfall'],
    0, 'Air is heated, rises rapidly, cools and condenses into towering cumulonimbus.'),
  Q('2.4', 'If the maximum temperature is 24 °C and the minimum is 10 °C, the mean is:',
    ['17 °C', '14 °C', '34 °C', '12 °C'],
    0, 'Mean is (24 + 10) ÷ 2 = 17. The value 14 is the diurnal range.'),
  Q('2.4', 'Cumulonimbus cloud indicates:',
    ['Heavy showers, thunder and lightning', 'Clear settled weather', 'Light drizzle only', 'Fog'],
    0, 'It is the towering, anvil-topped storm cloud.'),

  /* ---- 2.5 ---- */
  Q('2.5', 'An equatorial climate has:',
    ['A very small annual temperature range and rain in every month', 'A large annual temperature range', 'A long dry season', 'Very low humidity'],
    0, 'The sun is overhead all year, so temperature barely changes; the daily range exceeds the annual range.'),
  Q('2.5', 'Drip tips on rainforest leaves:',
    ['Shed heavy rain quickly so fungi cannot grow', 'Collect water for the plant', 'Attract pollinating insects', 'Reduce water loss in drought'],
    0, 'Reducing water loss is a desert adaptation, not a rainforest one.'),
  Q('2.5', 'Buttress roots are an adaptation to:',
    ['Support very tall trees growing in thin soil', 'Reach deep groundwater', 'Store water', 'Absorb sunlight'],
    0, 'Rainforest nutrients sit in a thin surface layer, so roots are shallow and need above-ground support.'),
  Q('2.5', 'Most nutrients in a rainforest are stored in:',
    ['The living vegetation', 'The deep soil', 'Groundwater', 'The atmosphere'],
    0, 'This is why clearance is so damaging: once the trees go, the thin soil is quickly leached.'),
  Q('2.5', 'The largest single cause of Amazon deforestation is:',
    ['Cattle ranching', 'Mining', 'Hydroelectric dams', 'Subsistence farming'],
    0, 'Roughly 80% of cleared Amazon land ends up as cattle pasture.'),
  Q('2.5', 'Hot deserts have a large diurnal temperature range because:',
    ['Clear skies let heat escape rapidly at night', 'They are close to the poles', 'Humidity is very high', 'They receive frequent rain'],
    0, 'Without cloud there is nothing to trap outgoing radiation after sunset.'),
  Q('2.5', 'Cactus spines are an adaptation that:',
    ['Reduce water loss and deter grazing animals', 'Collect rainwater', 'Provide shade for the roots', 'Help the plant climb'],
    0, 'Spines are reduced leaves, so they have a very small surface area for transpiration.'),
  Q('2.5', 'Ephemeral desert plants survive by:',
    ['Lying dormant as seeds and completing their life cycle quickly after rain', 'Storing water in thick stems', 'Growing very long tap roots', 'Losing their leaves in the dry season'],
    0, 'Succulence and tap roots are different strategies used by other desert plants.'),

  /* ---- 3.1 ---- */
  Q('3.1', 'The Human Development Index combines:',
    ['Life expectancy, education and income', 'Income and population size', 'Birth rate, death rate and migration', 'Literacy and employment only'],
    0, 'It is a composite indicator scored between 0 and 1.'),
  Q('3.1', 'The main weakness of GNI per capita as a development measure is that:',
    ['It is an average that hides inequality within a country', 'It cannot be calculated', 'It ignores population size', 'It is only available for rich countries'],
    0, 'It also misses the informal economy and says nothing about health, education or environment.'),
  Q('3.1', 'Which is a primary sector activity?',
    ['Mining', 'Car assembly', 'Nursing', 'Software development'],
    0, 'The primary sector extracts raw materials from the land or sea.'),
  Q('3.1', 'As a country develops, the proportion employed in the primary sector:',
    ['Falls', 'Rises', 'Stays the same', 'Rises then falls sharply'],
    0, 'Mechanisation reduces the labour needed in farming, while services grow.'),
  Q('3.1', 'A transnational corporation is a company that:',
    ['Operates in more than one country', 'Only exports its products', 'Is owned by a government', 'Employs more than 1000 people'],
    0, 'Typically headquarters and research are in one country and production in others.'),
  Q('3.1', 'A disadvantage for a country hosting a TNC factory is that:',
    ['Most profits are sent back to the home country', 'No jobs are created', 'Infrastructure is destroyed', 'Exports fall'],
    0, 'The plant can also close and move if costs rise, leaving unemployment behind.'),

  /* ---- 3.2 ---- */
  Q('3.2', 'Subsistence farming means:',
    ['Producing food mainly for the farmer\'s own family', 'Farming with very high inputs per hectare', 'Farming to sell for profit', 'Farming without any animals'],
    0, 'Farming for profit is commercial; input levels describe intensive or extensive farming.'),
  Q('3.2', 'Extensive farming involves:',
    ['Low inputs spread over a very large area', 'High inputs on a small area', 'Growing only cereals', 'Farming without machinery'],
    0, 'Yield per hectare is low but total output can still be large because the area is huge.'),
  Q('3.2', 'Which is a physical input to a farming system?',
    ['Rainfall', 'Fertiliser', 'Labour', 'A tractor'],
    0, 'The other three are human inputs.'),
  Q('3.2', 'The Green Revolution introduced:',
    ['High-yielding varieties with fertiliser, pesticide and irrigation', 'Organic farming methods', 'A ban on chemical fertilisers', 'Traditional seed varieties'],
    0, 'It was a technology package, not a single change.'),
  Q('3.2', 'A criticism of the Green Revolution is that:',
    ['The package was expensive, so richer farmers benefited most', 'Yields fell', 'It required no water', 'It reduced total food production'],
    0, 'It also depleted groundwater, caused salinisation and reduced crop diversity.'),
  Q('3.2', 'Appropriate technology is best described as:',
    ['Simple, affordable technology local people can use and repair themselves', 'The most advanced technology available', 'Technology imported from higher income countries', 'Technology owned by governments'],
    0, 'Hand pumps and treadle pumps are typical examples.'),
  Q('3.2', 'Salinisation is caused by:',
    ['Irrigation where drainage is poor, leaving salts in the soil', 'Heavy rainfall washing away nutrients', 'Over-grazing by cattle', 'Planting the same crop repeatedly'],
    0, 'Water evaporates and leaves dissolved salts behind at the surface.'),

  /* ---- 3.3 ---- */
  Q('3.3', 'A footloose industry is one that:',
    ['Is not tied to raw materials or a single market', 'Must locate on a coalfield', 'Requires a port', 'Employs only unskilled workers'],
    0, 'High technology and electronics are the standard examples.'),
  Q('3.3', 'High-technology firms cluster near universities mainly for:',
    ['Access to research links and graduate labour', 'Cheap electricity', 'Access to raw materials', 'Lower taxes'],
    0, 'The key input is people, so location follows skilled labour rather than resources.'),
  Q('3.3', 'Agglomeration means:',
    ['Firms clustering together to share suppliers, labour and ideas', 'Factories moving overseas', 'Industry declining in an area', 'Government control of industry'],
    0, 'Cambridge\'s "Silicon Fen" cluster is a good example.'),
  Q('3.3', 'Heavy industry such as steelmaking historically located near coalfields because:',
    ['Coal was bulky and expensive to transport', 'Labour was cheapest there', 'The land was flattest', 'Governments required it'],
    0, 'Bulk-reducing raw materials pull industry towards their source.'),

  /* ---- 3.4 ---- */
  Q('3.4', 'Which factor has most increased international tourism?',
    ['Cheaper air travel and higher disposable incomes', 'Longer working weeks', 'Falling life expectancy', 'Fewer paid holidays'],
    0, 'More money, more free time and cheaper travel together drive the growth.'),
  Q('3.4', 'Leakage in tourism means:',
    ['Tourist money leaving the destination to foreign companies and imports', 'Water lost from hotel pools', 'Tourists visiting outside the main season', 'Damage to coral reefs'],
    0, 'All-inclusive foreign-owned resorts are the classic cause.'),
  Q('3.4', 'Which is a disadvantage of tourism for a receiving area?',
    ['Many jobs are seasonal and low paid', 'It earns foreign currency', 'It creates a multiplier effect', 'It funds conservation'],
    0, 'The other three are advantages.'),
  Q('3.4', 'Ecotourism is best described as:',
    ['Small-scale tourism that conserves the environment and benefits local people', 'Any tourism in a hot country', 'Mass tourism at a beach resort', 'Tourism organised by a government'],
    0, 'Scale and the flow of benefits to local communities are what define it.'),
  Q('3.4', 'A sustainable management strategy for safari tourism is:',
    ['Limiting vehicle numbers and enforcing minimum distances from animals', 'Allowing off-road driving to reach animals', 'Building large high-rise hotels in parks', 'Removing park entry fees'],
    0, 'Off-road driving causes soil erosion and disturbs hunting and breeding.'),
  Q('3.4', 'In Kenya, community conservancies help because:',
    ['Maasai landowners receive rent and a share of tourist income directly', 'They ban all tourism', 'They remove local people from the land', 'They are owned by foreign tour operators'],
    0, 'Directing income to local landowners gives them a reason to protect wildlife.'),

  /* ---- 3.5 ---- */
  Q('3.5', 'Which is a non-renewable energy source?',
    ['Natural gas', 'Wind', 'Geothermal', 'Tidal'],
    0, 'Nuclear is also non-renewable, because uranium is a finite resource.'),
  Q('3.5', 'An advantage of nuclear power is that it:',
    ['Produces no carbon dioxide during generation', 'Produces no waste', 'Is cheap to build', 'Uses a renewable fuel'],
    0, 'The waste stays dangerous for thousands of years and build costs are very high.'),
  Q('3.5', 'A disadvantage of hydroelectric power is that:',
    ['Reservoirs flood land and displace people', 'It emits large amounts of carbon dioxide', 'The fuel runs out', 'It only works at night'],
    0, 'Silt trapping behind the dam is another major drawback.'),
  Q('3.5', 'A disadvantage of solar power is that:',
    ['Output falls at night and in cloudy weather', 'It emits sulphur dioxide', 'The fuel is expensive', 'It cannot be used in remote areas'],
    0, 'Off-grid solar is in fact particularly useful in remote areas.'),
  Q('3.5', 'Over-collection of fuelwood causes:',
    ['Deforestation and soil erosion', 'Acid rain', 'Ozone depletion', 'Salinisation'],
    0, 'It also takes hours a day, usually from women and children, reducing school attendance.'),

  /* ---- 3.6 ---- */
  Q('3.6', 'Globally, the largest share of fresh water is used by:',
    ['Agriculture', 'Industry', 'Domestic users', 'Power stations'],
    0, 'Agriculture takes roughly 70% worldwide, mostly for irrigation.'),
  Q('3.6', 'An aquifer is:',
    ['A layer of permeable rock storing groundwater', 'A pipe carrying water to a city', 'A large surface reservoir', 'A machine that removes salt from seawater'],
    0, 'Removing salt from seawater is desalination.'),
  Q('3.6', 'Over-abstraction leads to:',
    ['A falling water table and wells drying up', 'More reliable rainfall', 'Cleaner river water', 'Reduced flood risk'],
    0, 'It can also cause land subsidence and saltwater intrusion near coasts.'),
  Q('3.6', 'Which reduces water demand rather than increasing supply?',
    ['Drip irrigation instead of flooding fields', 'Building a desalination plant', 'Drilling new boreholes', 'Constructing a reservoir'],
    0, 'The other three all add to the amount of water available.'),
  Q('3.6', 'A major effect of water shortage in lower income countries is:',
    ['Water-borne disease from drinking contaminated water', 'Increased hydroelectric output', 'Falling food prices', 'Reduced migration'],
    0, 'Cholera, typhoid and diarrhoeal disease are the main killers.'),

  /* ---- 3.7 ---- */
  Q('3.7', 'Eutrophication is caused by:',
    ['Fertiliser runoff enriching water and triggering algal growth', 'Sulphur dioxide dissolving in rain', 'Oil spilled from tankers', 'Warm water from power stations only'],
    0, 'Bacteria decomposing the dead algae use up the dissolved oxygen, so fish suffocate.'),
  Q('3.7', 'Acid rain is caused mainly by:',
    ['Sulphur dioxide and nitrogen oxides from burning fossil fuels', 'CFCs from aerosols', 'Methane from cattle', 'Dust from deserts'],
    0, 'It often falls hundreds of kilometres downwind, making it an international problem.'),
  Q('3.7', 'Desertification is:',
    ['The process by which productive land becomes desert', 'The natural expansion of sand dunes only', 'The spread of irrigation into dry areas', 'A permanent change that cannot be slowed'],
    0, 'It results from drought combined with human pressure such as overgrazing and deforestation.'),
  Q('3.7', 'Sustainable development is best defined as development that:',
    ['Meets present needs without compromising future generations', 'Produces the fastest economic growth', 'Uses no natural resources at all', 'Happens only in higher income countries'],
    0, 'This is the Brundtland definition, and it balances economy, society and environment.'),
  Q('3.7', 'Which is a method of reducing soil erosion?',
    ['Contour ploughing and terracing', 'Ploughing up and down slopes', 'Removing hedgerows', 'Increasing herd sizes on dry grassland'],
    0, 'The other three all make erosion worse.'),

  /* ---- Climate change (new content, tagged by topic) ---- */
  Q('climate-change', 'The natural greenhouse effect is:',
    ['Essential, because without it Earth would average about -18 °C', 'The cause of global warming', 'The same thing as ozone depletion', 'Caused entirely by human activity'],
    0, 'The problem is the *enhanced* greenhouse effect. Calling the natural greenhouse effect harmful loses marks.'),
  Q('climate-change', 'Which gas contributes most to the enhanced greenhouse effect overall?',
    ['Carbon dioxide', 'Methane', 'Nitrous oxide', 'Ozone'],
    0, 'Methane is more powerful per molecule, but carbon dioxide is emitted in far greater quantities.'),
  Q('climate-change', 'Ozone depletion differs from the enhanced greenhouse effect because it:',
    ['Lets more ultraviolet radiation reach the surface, and is caused mainly by CFCs', 'Traps more outgoing heat', 'Is caused by carbon dioxide', 'Only occurs over cities'],
    0, 'Confusing the two is one of the most commonly penalised errors on this topic.'),
  Q('climate-change', 'Ice cores are useful evidence of past climate because they:',
    ['Trap air bubbles that record past carbon dioxide levels', 'Show the age of glaciers', 'Contain fossils of past species', 'Record past sea levels directly'],
    0, 'They give a direct record of atmospheric composition going back hundreds of thousands of years.'),
  Q('climate-change', 'Which is a natural cause of climate change?',
    ['Milankovitch cycles in Earth\'s orbit and axial tilt', 'Burning fossil fuels', 'Deforestation', 'Nitrogen fertiliser use'],
    0, 'The other three are human causes.'),
  Q('climate-change', 'Sea level is rising because of:',
    ['Thermal expansion of warming water plus melting land ice', 'Melting sea ice alone', 'Increased rainfall over oceans', 'Tectonic movement of the sea bed'],
    0, 'Melting sea ice barely changes sea level, because floating ice already displaces its own weight.'),
  Q('climate-change', 'Mitigation of climate change means:',
    ['Reducing the causes, such as cutting greenhouse gas emissions', 'Protecting people from impacts that are already happening', 'Predicting future temperatures', 'Moving people away from the coast'],
    0, 'Protecting people from impacts is adaptation.'),
  Q('climate-change', 'Which is an example of adaptation rather than mitigation?',
    ['Building sea walls and planting drought-resistant crops', 'Switching from coal to wind power', 'Planting forests to absorb carbon dioxide', 'Introducing a carbon tax'],
    0, 'Adaptation lives with the change; mitigation tackles the cause.'),
  Q('climate-change', 'Why are lower income countries often worst affected by climate change?',
    ['They are frequently more exposed and have least money to adapt', 'They emit the most greenhouse gases', 'They are all located at the poles', 'They have no coastlines'],
    0, 'This unevenness between who causes the problem and who suffers it is central to the international politics.'),
  Q('climate-change', 'The Montreal Protocol is a useful example because it shows that:',
    ['International agreement can work when few substances and industries are involved', 'International agreements never work', 'Ozone depletion caused global warming', 'CFCs are still increasing'],
    0, 'The ozone layer is recovering, which contrasts with the slower progress on carbon emissions.'),
  Q('climate-change', 'A drawback of wind and solar power as mitigation is that:',
    ['Output varies with the weather and time of day', 'They emit large amounts of carbon dioxide', 'The fuel will run out', 'They cannot be used in remote areas'],
    0, 'This is why storage and a mixed energy supply matter.'),
  Q('climate-change', 'Permafrost thaw worsens climate change because it:',
    ['Releases methane, a powerful greenhouse gas', 'Reflects more sunlight', 'Absorbs carbon dioxide', 'Lowers sea level'],
    0, 'This is a feedback loop: warming causes thaw, which causes further warming.'),

  /* ---- Skills ---- */
  Q('maps', 'In a grid reference, which is read first?',
    ['Eastings', 'Northings', 'Whichever is larger', 'It does not matter'],
    0, 'Along the corridor, then up the stairs. Reversing them loses the mark.'),
  Q('maps', 'On a 1:50 000 map, 2 cm represents:',
    ['1 km', '500 m', '2 km', '5 km'],
    0, 'On a 1:25 000 map, 4 cm represents 1 km.'),
  Q('maps', 'Contour lines that are very close together show:',
    ['A steep slope', 'A gentle slope', 'Flat land', 'A river valley'],
    0, 'Spacing shows steepness; the shape of the contours shows the landform.'),
  Q('maps', 'Contours forming a V that points uphill indicate:',
    ['A valley', 'A spur', 'A plateau', 'A col'],
    0, 'A V pointing downhill indicates a spur.'),
  Q('maps', 'A six-figure grid reference locates a point to the nearest:',
    ['100 m', '1 km', '10 m', '1 m'],
    0, 'It divides each 1 km square into tenths.'),
  Q('maps', 'A bearing of 090° means the direction is:',
    ['East', 'North', 'South', 'West'],
    0, 'Bearings are measured clockwise from north: 090 east, 180 south, 270 west.'),

  Q('graphs', 'Which graph is best for showing proportions of a whole?',
    ['Pie chart', 'Line graph', 'Scatter graph', 'Isoline map'],
    0, 'A line graph shows change over time; a scatter graph shows relationships.'),
  Q('graphs', 'A scatter graph is used to:',
    ['Look for a relationship between two variables', 'Show change over time', 'Show proportions', 'Show movement between places'],
    0, 'Flow lines show movement; pie charts show proportions.'),
  Q('graphs', 'Percentage change is calculated as:',
    ['(new − old) ÷ old × 100', '(new − old) ÷ new × 100', 'new ÷ old × 100', '(old − new) ÷ 100'],
    0, 'Always divide by the original value.'),
  Q('graphs', 'The interquartile range is preferred to the range because it:',
    ['Ignores extreme outliers', 'Is easier to calculate', 'Uses every value', 'Is always larger'],
    0, 'It measures the spread of the middle half of the data.'),

  Q('command-words', 'A question asking you to "describe" a pattern wants you to:',
    ['State what you can see, with figures, and no reasons', 'Explain why the pattern exists', 'Evaluate how useful the data are', 'Compare two places'],
    0, 'Reasons earn nothing in a describe question. Save them for explain.'),
  Q('command-words', 'The command word "suggest" means:',
    ['Give a plausible geographical reason, applying your knowledge', 'State a fact you have memorised', 'Give your personal opinion', 'Describe what you can see'],
    0, 'It is used where you have not been taught the exact answer, so a sensible reasoned response is credited.'),
  Q('command-words', 'An answer to a "to what extent" question must include:',
    ['Both sides and a justified judgement', 'Only the evidence that supports the statement', 'A list of facts with no conclusion', 'A diagram'],
    0, 'Omitting the judgement is the most common way of missing the top band.'),
  Q('command-words', 'If a question says "using evidence from Fig. 3", you must:',
    ['Quote figures, names or grid references from that figure', 'Answer entirely from memory', 'Describe a case study instead', 'Draw your own diagram'],
    0, 'Marks are tied to the resource, so ignoring it caps the answer.'),

  Q('fieldwork', 'Primary data is:',
    ['Data you collect yourself in the field', 'Data from a census', 'Data from a textbook', 'Data from an old map'],
    0, 'The other three are all secondary data.'),
  Q('fieldwork', 'Systematic sampling means taking measurements:',
    ['At regular intervals', 'At random locations', 'In proportion to subgroup size', 'Wherever is most convenient'],
    0, 'Random uses random numbers; stratified samples subgroups in proportion.'),
  Q('fieldwork', 'River discharge is calculated as:',
    ['Cross-sectional area × velocity', 'Width × depth', 'Velocity ÷ area', 'Width × velocity'],
    0, 'Cross-sectional area itself comes from width × mean depth.'),
  Q('fieldwork', 'A limitation of timing a float to measure velocity is that:',
    ['Wind can push the float, so it does not reflect water speed', 'It takes too long', 'It cannot be repeated', 'It requires expensive equipment'],
    0, 'A flow meter is more accurate; repeating three times and taking a mean helps.'),
  Q('fieldwork', 'A good evaluation point about a small sample is:',
    ['Results may not be representative, so more sites should be measured', 'It proves the hypothesis', 'It makes the data more accurate', 'It removes all bias'],
    0, 'Always pair a limitation with a specific improvement.'),
  Q('fieldwork', 'A bipolar survey is used to measure:',
    ['Environmental quality, using a scale between two opposites', 'River velocity', 'Pebble roundness', 'Wind direction'],
    0, 'Factors such as litter, noise and greenery are scored from -3 to +3.')

  ];
})();
