/* Glossary. `id` must be the slug of `term` so that [[term]] links resolve. */
(function () {
  var raw = [

  /* --- Theme 1 --------------------------------------------------------- */
  ['Birth rate', 'The number of live births per 1000 people per year.', '1.1'],
  ['Death rate', 'The number of deaths per 1000 people per year.', '1.1'],
  ['Natural increase', 'Birth rate minus death rate; the change in population before migration is counted.', '1.1'],
  ['Natural decrease', 'When the death rate is higher than the birth rate, so population falls without migration.', '1.1'],
  ['Fertility rate', 'The average number of children a woman has in her lifetime. Around 2.1 is replacement level.', '1.1'],
  ['Infant mortality rate', 'The number of deaths of children under one year old per 1000 live births.', '1.1'],
  ['Life expectancy', 'The average number of years a person is expected to live from birth.', '1.1'],
  ['Demographic Transition Model', 'A model showing how birth and death rates change in five stages as a country develops.', '1.1'],
  ['Over-population', 'When there are too many people for the resources and technology available, lowering living standards.', '1.1'],
  ['Under-population', 'When there are too few people to use the available resources efficiently.', '1.1'],
  ['Optimum population', 'The population that produces the highest standard of living from the resources available.', '1.1'],
  ['Anti-natalist policy', 'A government policy intended to reduce the birth rate.', '1.1'],
  ['Pro-natalist policy', 'A government policy intended to raise the birth rate.', '1.1'],
  ['Family planning', 'Advice and contraception allowing couples to choose the number and spacing of their children.', '1.1'],

  ['Migration', 'The movement of people from one place to another to live, usually for a year or more.', '1.2'],
  ['Immigration', 'Movement of people into a country.', '1.2'],
  ['Emigration', 'Movement of people out of a country.', '1.2'],
  ['Net migration', 'Immigration minus emigration.', '1.2'],
  ['Internal migration', 'Migration within a country.', '1.2'],
  ['International migration', 'Migration between countries.', '1.2'],
  ['Voluntary migration', 'Migration by choice, usually to improve quality of life.', '1.2'],
  ['Forced migration', 'Migration where people have no realistic choice, such as fleeing war or disaster.', '1.2'],
  ['Refugee', 'A person forced to leave their country to escape war, persecution or disaster.', '1.2'],
  ['Asylum seeker', 'A person who has applied for refugee status and is awaiting a decision.', '1.2'],
  ['Economic migrant', 'A person who moves voluntarily to find work or higher income.', '1.2'],
  ['Push factor', 'A negative condition that drives people away from an area.', '1.2'],
  ['Pull factor', 'A positive condition that attracts people to an area.', '1.2'],
  ['Remittances', 'Money sent home by migrants working abroad.', '1.2'],
  ['Brain drain', 'The loss of skilled and educated workers through emigration.', '1.2'],
  ['Step migration', 'Migration made in a series of stages rather than one move.', '1.2'],

  ['Population pyramid', 'A graph showing the age and sex structure of a population.', '1.3'],
  ['Dependency ratio', 'The number of dependants per 100 people of working age.', '1.3'],
  ['Ageing population', 'A population with a rising proportion of people aged 65 and over.', '1.3'],
  ['Youthful population', 'A population with a high proportion of people under 15.', '1.3'],
  ['Economically active', 'People of working age, usually taken as 15 to 64.', '1.3'],

  ['Population density', 'The average number of people per square kilometre.', '1.4'],
  ['Population distribution', 'The way people are spread out across an area.', '1.4'],
  ['Sparsely populated', 'An area with few people per square kilometre.', '1.4'],
  ['Densely populated', 'An area with many people per square kilometre.', '1.4'],

  ['Site', 'The actual land on which a settlement is built.', '1.5'],
  ['Situation', 'The position of a settlement relative to the area around it.', '1.5'],
  ['Wet point site', 'A settlement site chosen for its reliable water supply.', '1.5'],
  ['Dry point site', 'A settlement site on raised, drier ground above marsh or floodplain.', '1.5'],
  ['Nucleated settlement', 'A settlement where buildings are clustered closely together.', '1.5'],
  ['Dispersed settlement', 'A settlement of scattered, isolated buildings.', '1.5'],
  ['Linear settlement', 'A settlement strung out along a road, river or valley.', '1.5'],
  ['Settlement hierarchy', 'The ranking of settlements by size, services or sphere of influence.', '1.5'],
  ['Threshold population', 'The minimum number of people needed to keep a service running profitably.', '1.5'],
  ['Range', 'The maximum distance people will travel to use a service.', '1.5'],
  ['Sphere of influence', 'The area served by a settlement or service, also called its catchment area.', '1.5'],
  ['Low order service', 'A frequently used service with a low threshold and short range, such as a newsagent.', '1.5'],
  ['High order service', 'A rarely used service with a high threshold and long range, such as a hospital.', '1.5'],

  ['Central business district', 'The commercial centre of a city, with the highest land values and greatest accessibility.', '1.6'],
  ['Inner city', 'The zone of older housing and former industry around the CBD.', '1.6'],
  ['Suburbs', 'Lower-density residential areas built outwards from the inner city.', '1.6'],
  ['Rural-urban fringe', 'The zone where the built-up area meets the countryside.', '1.6'],
  ['Green belt', 'Protected open land around a city where building is restricted.', '1.6'],
  ['Brownfield site', 'Previously developed land available for redevelopment.', '1.6'],
  ['Greenfield site', 'Land that has not been built on before.', '1.6'],
  ['Urban regeneration', 'Investment to improve a run-down urban area.', '1.6'],
  ['Gentrification', 'The improvement of run-down inner city housing by wealthier incomers moving in.', '1.6'],

  ['Urbanisation', 'An increase in the proportion of a population living in towns and cities.', '1.7'],
  ['Rural-urban migration', 'Movement of people from the countryside to towns and cities.', '1.7'],
  ['Counter-urbanisation', 'Movement of people out of large cities to smaller towns and rural areas.', '1.7'],
  ['Megacity', 'A city with more than 10 million inhabitants.', '1.7'],
  ['Squatter settlement', 'An area of illegally built, poor-quality housing, also called a shanty town.', '1.7'],
  ['Informal sector', 'Work with no contract, security, regulation or tax, such as street selling.', '1.7'],
  ['Self-help scheme', 'A scheme where residents build or improve their own homes using materials and loans provided.', '1.7'],
  ['Site and service scheme', 'A scheme providing serviced plots of land on which people build their own homes.', '1.7'],
  ['Urban sprawl', 'The uncontrolled outward spread of a built-up area.', '1.7'],
  ['Rural depopulation', 'Loss of population from the countryside as people move away.', '1.7'],

  /* --- Theme 2 --------------------------------------------------------- */
  ['Crust', 'The thin, rigid outer layer of the Earth, broken into tectonic plates.', '2.1'],
  ['Mantle', 'The semi-molten layer beneath the crust, where convection currents drive plate movement.', '2.1'],
  ['Convection currents', 'Circulating movements in the mantle, driven by heat from the core, which move the plates.', '2.1'],
  ['Constructive margin', 'A plate margin where plates move apart and new crust is formed.', '2.1'],
  ['Destructive margin', 'A plate margin where an oceanic plate is subducted beneath a continental plate.', '2.1'],
  ['Collision margin', 'A plate margin where two continental plates meet and rock is forced upwards into fold mountains.', '2.1'],
  ['Conservative margin', 'A plate margin where plates slide past each other and crust is neither made nor destroyed.', '2.1'],
  ['Subduction', 'The sinking of a denser oceanic plate beneath a less dense plate at a destructive margin.', '2.1'],
  ['Focus', 'The point underground where an earthquake begins.', '2.1'],
  ['Epicentre', 'The point on the surface directly above the focus.', '2.1'],
  ['Richter scale', 'A logarithmic scale measuring the magnitude, or energy, of an earthquake.', '2.1'],
  ['Mercalli scale', 'A scale measuring the intensity of an earthquake by its observed effects.', '2.1'],
  ['Shield volcano', 'A broad, gently sloping volcano built of runny basaltic lava.', '2.1'],
  ['Composite volcano', 'A steep-sided cone built of alternating layers of ash and viscous lava.', '2.1'],
  ['Pyroclastic flow', 'A fast-moving cloud of superheated gas, ash and rock from a volcano.', '2.1'],
  ['Lahar', 'A volcanic mudflow of ash mixed with water.', '2.1'],

  ['Drainage basin', 'The area of land drained by a river and its tributaries.', '2.2'],
  ['Watershed', 'The boundary between two drainage basins, usually high ground.', '2.2'],
  ['Tributary', 'A smaller stream or river joining a larger one.', '2.2'],
  ['Confluence', 'The point where two rivers join.', '2.2'],
  ['Infiltration', 'The movement of water from the surface into the soil.', '2.2'],
  ['Throughflow', 'The sideways movement of water through soil towards a river.', '2.2'],
  ['Surface runoff', 'Water flowing over the ground surface, the fastest route to a river.', '2.2'],
  ['Discharge', 'The volume of water passing a point in a river per second, in cubic metres per second.', '2.2'],
  ['Hydraulic action', 'Erosion caused by the sheer force of moving water forcing air into cracks.', '2.2'],
  ['Abrasion', 'Erosion caused by the load being scraped against the bed and banks.', '2.2'],
  ['Attrition', 'The wearing down of the load itself as pieces collide and become smaller and rounder.', '2.2'],
  ['Traction', 'The rolling of the largest particles along a river bed.', '2.2'],
  ['Saltation', 'The bouncing of sand and small pebbles along a river bed.', '2.2'],
  ['Meander', 'A pronounced bend in a river, with erosion on the outside and deposition on the inside.', '2.2'],
  ['Ox-bow lake', 'A horseshoe-shaped lake formed when a meander is cut off from the main channel.', '2.2'],
  ['Floodplain', 'The flat land either side of a river, formed by deposition during floods.', '2.2'],
  ['Levee', 'A raised bank of coarse sediment deposited alongside a channel during floods.', '2.2'],
  ['Delta', 'A depositional landform of sediment built where a river enters a sea or lake.', '2.2'],
  ['Alluvium', 'Fine, fertile sediment deposited by a river.', '2.2'],
  ['Hard engineering', 'Building artificial structures to control a river or coast.', '2.2'],
  ['Soft engineering', 'Working with natural processes to reduce flood or erosion risk.', '2.2'],

  ['Constructive wave', 'A low, long wave with a strong swash that builds up a beach.', '2.3'],
  ['Destructive wave', 'A high, steep wave with a strong backwash that erodes a beach.', '2.3'],
  ['Swash', 'The movement of water up a beach after a wave breaks.', '2.3'],
  ['Backwash', 'The movement of water back down a beach under gravity.', '2.3'],
  ['Fetch', 'The distance of open water over which the wind blows to create waves.', '2.3'],
  ['Longshore drift', 'The zig-zag movement of sediment along a coast caused by waves arriving at an angle.', '2.3'],
  ['Headland', 'A resistant section of coast left protruding as softer rock either side is eroded.', '2.3'],
  ['Bay', 'A curved indentation in a coast where softer rock has been eroded.', '2.3'],
  ['Wave-cut platform', 'A gently sloping rocky surface exposed at low tide as a cliff retreats.', '2.3'],
  ['Stack', 'An isolated pillar of rock left when the roof of an arch collapses.', '2.3'],
  ['Spit', 'A ridge of sand or shingle attached to the land at one end, formed by longshore drift.', '2.3'],
  ['Tombolo', 'A spit that joins an island to the mainland.', '2.3'],
  ['Coral bleaching', 'The whitening and possible death of coral when stress causes it to expel its algae.', '2.3'],
  ['Fringing reef', 'A coral reef growing directly against the shore.', '2.3'],
  ['Barrier reef', 'A coral reef separated from the coast by a lagoon.', '2.3'],
  ['Atoll', 'A ring-shaped coral reef surrounding a lagoon.', '2.3'],
  ['Mangrove', 'A salt-tolerant tree growing on sheltered tropical coasts, protecting them from wave attack.', '2.3'],
  ['Groyne', 'A wooden or rock barrier built out from a beach to trap sediment moving by longshore drift.', '2.3'],
  ['Managed retreat', 'Allowing low-value land to flood and become salt marsh rather than defending it.', '2.3'],
  ['Beach nourishment', 'Adding sand or shingle to a beach to replace what has been eroded.', '2.3'],

  ['Weather', 'The state of the atmosphere at a place at a particular time.', '2.4'],
  ['Climate', 'The average weather conditions of a place over at least 30 years.', '2.4'],
  ['Stevenson screen', 'A white, louvred box holding weather instruments 1.25 m above grass.', '2.4'],
  ['Anemometer', 'An instrument measuring wind speed.', '2.4'],
  ['Okta', 'A unit of cloud cover: one eighth of the sky.', '2.4'],
  ['Relative humidity', 'The amount of water vapour in the air as a percentage of the maximum it could hold.', '2.4'],
  ['Diurnal temperature range', 'The difference between the maximum and minimum temperature in one day.', '2.4'],
  ['Relief rainfall', 'Rain formed when moist air is forced to rise over high ground.', '2.4'],
  ['Convectional rainfall', 'Rain formed when strong surface heating makes air rise, cool and condense.', '2.4'],
  ['Frontal rainfall', 'Rain formed when warm air is forced to rise over colder, denser air.', '2.4'],
  ['Rain shadow', 'A drier area on the leeward side of high ground.', '2.4'],

  ['Ecosystem', 'A community of plants and animals interacting with their physical environment.', '2.5'],
  ['Canopy', 'The continuous layer of treetops in a rainforest that absorbs most of the light.', '2.5'],
  ['Emergent layer', 'The tallest rainforest trees, rising above the canopy.', '2.5'],
  ['Buttress roots', 'Wide, above-ground roots that support tall rainforest trees in thin soil.', '2.5'],
  ['Drip tip', 'A pointed leaf tip that sheds heavy rain quickly.', '2.5'],
  ['Epiphyte', 'A plant growing on another plant, taking moisture from the air rather than the soil.', '2.5'],
  ['Liana', 'A woody climbing plant that uses tree trunks to reach the light.', '2.5'],
  ['Leaching', 'The washing of nutrients down through the soil and out of reach of plant roots.', '2.5'],
  ['Deforestation', 'The clearing of forest, usually for farming, logging, mining or building.', '2.5'],
  ['Xerophyte', 'A plant adapted to survive in very dry conditions.', '2.5'],
  ['Ephemeral', 'A desert plant that stays dormant as a seed and completes its life cycle quickly after rain.', '2.5'],

  /* --- Theme 3 --------------------------------------------------------- */
  ['Development', 'The use of resources to improve standard of living and quality of life.', '3.1'],
  ['Standard of living', 'How well off a person is in material terms.', '3.1'],
  ['Quality of life', 'How satisfied a person is with life overall, including health, safety and environment.', '3.1'],
  ['Gross National Income per capita', 'The total income of a country divided by its population.', '3.1'],
  ['Human Development Index', 'A composite measure combining life expectancy, education and income into a score from 0 to 1.', '3.1'],
  ['Purchasing power parity', 'An adjustment to income figures allowing for what money actually buys in each country.', '3.1'],
  ['Primary sector', 'Industry that extracts raw materials, such as farming and mining.', '3.1'],
  ['Secondary sector', 'Industry that manufactures raw materials into goods.', '3.1'],
  ['Tertiary sector', 'Industry that provides services.', '3.1'],
  ['Quaternary sector', 'Industry based on research, information and high technology.', '3.1'],
  ['Globalisation', 'The growing connection and interdependence of countries through trade, investment and communication.', '3.1'],
  ['Transnational corporation', 'A company operating in more than one country.', '3.1'],
  ['Multiplier effect', 'The way an initial investment creates further jobs and spending in the wider economy.', '3.1'],

  ['Arable farming', 'Farming that grows crops.', '3.2'],
  ['Pastoral farming', 'Farming that rears animals.', '3.2'],
  ['Subsistence farming', 'Farming to feed the farmer\'s own family, with little surplus to sell.', '3.2'],
  ['Commercial farming', 'Farming to sell produce for profit.', '3.2'],
  ['Intensive farming', 'Farming with high inputs per hectare, giving high yields from a small area.', '3.2'],
  ['Extensive farming', 'Farming with low inputs spread over a very large area.', '3.2'],
  ['Green Revolution', 'The introduction of high-yielding crop varieties with fertiliser, pesticide and irrigation from the 1960s.', '3.2'],
  ['Irrigation', 'The artificial watering of farmland.', '3.2'],
  ['Salinisation', 'The build-up of salts in soil, often caused by irrigation with poor drainage.', '3.2'],
  ['Appropriate technology', 'Simple, affordable technology that local people can build, use and repair themselves.', '3.2'],
  ['Malnutrition', 'Ill health caused by a diet lacking sufficient energy or nutrients.', '3.2'],

  ['Footloose industry', 'An industry not tied to raw materials or a single market, so it can locate almost anywhere.', '3.3'],
  ['Science park', 'A planned estate of high-technology and research firms, usually near a university.', '3.3'],
  ['Agglomeration', 'The clustering of firms to share suppliers, labour and ideas.', '3.3'],
  ['Raw materials', 'The natural resources used as inputs to an industry.', '3.3'],

  ['Leakage', 'The loss of tourist income from a destination to foreign-owned companies and imports.', '3.4'],
  ['Ecotourism', 'Small-scale tourism to natural areas that conserves the environment and benefits local people.', '3.4'],
  ['Sustainable tourism', 'Tourism managed so it benefits local people and protects the environment for the future.', '3.4'],
  ['Carrying capacity', 'The maximum number of visitors an area can take before damage occurs.', '3.4'],

  ['Renewable energy', 'Energy from a source that is naturally replaced and will not run out.', '3.5'],
  ['Non-renewable energy', 'Energy from a finite source that will eventually be used up.', '3.5'],
  ['Fossil fuel', 'Coal, oil or natural gas, formed from the remains of ancient organisms.', '3.5'],
  ['Geothermal energy', 'Energy from heat within the Earth, used in volcanic regions.', '3.5'],
  ['Fuelwood', 'Wood collected and burned for cooking and heating, the main energy source in many rural areas.', '3.5'],
  ['Biomass', 'Energy from plant and animal material, including crop waste and dung.', '3.5'],

  ['Aquifer', 'A layer of permeable rock that stores groundwater.', '3.6'],
  ['Groundwater', 'Water held underground in soil and rock.', '3.6'],
  ['Water table', 'The upper level of saturated rock underground.', '3.6'],
  ['Desalination', 'The removal of salt from seawater to make it drinkable.', '3.6'],
  ['Rainwater harvesting', 'Collecting and storing rainwater, usually from roofs.', '3.6'],
  ['Over-abstraction', 'Removing groundwater faster than it is replaced, causing the water table to fall.', '3.6'],

  ['Soil erosion', 'The removal of topsoil by wind or water, usually after vegetation is removed.', '3.7'],
  ['Desertification', 'The process by which productive land turns into desert.', '3.7'],
  ['Eutrophication', 'The oxygen depletion of water caused by nutrient enrichment, which triggers algal growth.', '3.7'],
  ['Acid rain', 'Rain acidified by sulphur dioxide and nitrogen oxides, which damages trees, lakes and buildings.', '3.7'],
  ['Enhanced greenhouse effect', 'Additional warming caused by human emissions of greenhouse gases.', '3.7'],
  ['Sustainable development', 'Development meeting the needs of the present without compromising future generations.', '3.7'],
  ['Conservation', 'The protection and careful management of natural resources and environments.', '3.7'],

  /* --- Skills ---------------------------------------------------------- */
  ['Contour', 'A line on a map joining points of equal height above sea level.', 'maps'],
  ['Contour interval', 'The height difference between adjacent contour lines.', 'maps'],
  ['Escarpment', 'A ridge with a steep scarp slope on one side and a gentle dip slope on the other.', 'maps'],
  ['Spur', 'A finger of high land projecting into a valley, shown by contours forming a V pointing downhill.', 'maps'],
  ['Col', 'A dip or saddle in a ridge between two summits.', 'maps'],
  ['Bearing', 'A direction measured clockwise from north in degrees, written with three figures.', 'maps'],
  ['Primary data', 'Data collected first hand by the investigator.', 'fieldwork'],
  ['Secondary data', 'Data collected by someone else, such as census statistics or maps.', 'fieldwork'],
  ['Hypothesis', 'A statement that can be tested by collecting data and then supported or rejected.', 'fieldwork'],
  ['Systematic sampling', 'Sampling at regular intervals, such as every 50 metres.', 'fieldwork'],
  ['Stratified sampling', 'Sampling each subgroup of an area in proportion to its size.', 'fieldwork'],
  ['Bipolar survey', 'A survey scoring environmental factors on a scale between two opposites.', 'fieldwork']

  ];

  GEO.glossary = raw.map(function (r) {
    return { id: GEO.slug(r[0]), term: r[0], def: r[1], unit: r[2] };
  });
})();
