/* Question bank, part 3: Topics 9 to 12. */

window.QUESTIONS_3 = [

  /* ---------------- Topic 9: Metals ---------------- */
  { id: "q9-01", t: 9, s: "9.1", lv: "C", ty: "multi",
    q: "Which are general physical properties of metals? Select all that apply.",
    o: ["Good conductors of electricity", "Malleable and ductile",
        "Generally low melting points", "Shiny when freshly cut"],
    a: [0, 1, 3],
    ex: "Metals are typically strong, shiny, malleable, ductile, dense and good conductors of heat and electricity, with high melting points. Group I is the main exception." },

  { id: "q9-02", t: 9, s: "9.1", lv: "C", ty: "mcq",
    q: "What is produced when a metal reacts with a dilute acid?",
    o: ["A salt and water", "A salt and hydrogen",
        "A metal oxide and hydrogen", "A salt and oxygen"],
    a: 1,
    ex: "Metals above hydrogen in the reactivity series displace hydrogen from acids, forming a salt and hydrogen gas." },

  { id: "q9-03", t: 9, s: "9.2", lv: "C", ty: "mcq",
    q: "Why is aluminium used to make aircraft bodies?",
    o: ["It is very reactive", "It has a low density and resists corrosion",
        "It is the best conductor of electricity", "It has the highest melting point"],
    a: 1,
    ex: "Low density keeps the aircraft light, and the protective oxide layer stops further corrosion. Aluminium is also used for food containers for the same reason." },

  { id: "q9-04", t: 9, s: "9.2", lv: "C", ty: "mcq",
    q: "Why is copper used for electrical wiring?",
    o: ["It is an excellent conductor of electricity and is ductile",
        "It is very hard", "It is magnetic", "It has a very low density"],
    a: 0,
    ex: "Copper conducts extremely well and can be drawn into thin wires without breaking, which is what ductile means." },

  { id: "q9-05", t: 9, s: "9.3", lv: "C", ty: "mcq",
    q: "What is an alloy?",
    o: ["A compound of two metals",
        "A mixture of a metal with one or more other elements",
        "A pure metal that has been heated",
        "A metal coated with another metal"],
    a: 1,
    ex: "Alloys are mixtures, not compounds. Brass is copper with zinc, and stainless steel is iron with chromium and nickel." },

  { id: "q9-06", t: 9, s: "9.3", lv: "S", ty: "mcq",
    q: "Why is an alloy usually harder than the pure metal?",
    o: ["The added atoms are larger and heavier",
        "The different sized atoms disrupt the regular layers, so the layers cannot slide over each other easily",
        "The alloy has stronger covalent bonds",
        "The alloy contains no delocalised electrons"],
    a: 1,
    ex: "In a pure metal the identical atoms form neat layers that slip easily. Atoms of a different size distort the arrangement and block that slipping." },

  { id: "q9-07", t: 9, s: "9.4", lv: "C", ty: "mcq",
    q: "Which list places the metals in order of decreasing reactivity?",
    o: ["Potassium, calcium, zinc, copper", "Copper, zinc, calcium, potassium",
        "Zinc, potassium, copper, calcium", "Calcium, copper, potassium, zinc"],
    a: 0,
    ex: "The series runs potassium, sodium, calcium, magnesium, aluminium, carbon, zinc, iron, hydrogen, copper, silver, gold." },

  { id: "q9-08", t: 9, s: "9.4", lv: "C", ty: "mcq",
    q: "Which metal reacts with steam but not with cold water?",
    o: ["Potassium", "Magnesium", "Copper", "Sodium"],
    a: 1,
    ex: "Potassium and sodium react violently with cold water. Magnesium reacts very slowly with cold water but readily with steam. Copper does not react with either." },

  { id: "q9-09", t: 9, s: "9.4", lv: "S", ty: "mcq",
    q: "Why does aluminium appear less reactive than its position in the reactivity series suggests?",
    o: ["It is a transition metal",
        "A thin, strong layer of aluminium oxide forms on the surface and protects the metal underneath",
        "It has a very high melting point",
        "It does not form ions"],
    a: 1,
    ex: "The oxide layer forms immediately in air and sticks tightly to the surface, stopping air and water from reaching the metal below." },

  { id: "q9-10", t: 9, s: "9.4", lv: "S", ty: "mcq",
    q: "Zinc powder is added to copper(II) sulfate solution. What happens?",
    o: ["No reaction, because zinc is less reactive",
        "The blue colour fades and a red-brown solid forms, because zinc displaces copper",
        "A gas is given off",
        "A white precipitate forms"],
    a: 1,
    ex: "Zinc is more reactive so it loses electrons more readily: Zn + CuSO4 gives ZnSO4 + Cu. The blue Cu2+ ions are removed from solution." },

  { id: "q9-11", t: 9, s: "9.4", lv: "S", ty: "mcq",
    q: "In terms of electrons, what makes one metal more reactive than another?",
    o: ["It has more electrons in total",
        "Its atoms lose electrons more readily to form positive ions",
        "Its atoms gain electrons more readily",
        "It has a higher melting point"],
    a: 1,
    ex: "Metal reactions are all about forming positive ions. The easier the atom gives up its outer electrons, the higher up the series it sits." },

  { id: "q9-12", t: 9, s: "9.5", lv: "C", ty: "multi",
    q: "Which two substances are both required for iron to rust? Select both.",
    o: ["Oxygen", "Carbon dioxide", "Water", "Nitrogen"],
    a: [0, 2],
    ex: "Rusting needs oxygen and water together. In an experiment with boiled water under oil, or with dry air and a drying agent, no rusting occurs." },

  { id: "q9-13", t: 9, s: "9.5", lv: "C", ty: "mcq",
    q: "What is galvanising?",
    o: ["Coating iron with a layer of zinc",
        "Coating iron with a layer of paint",
        "Mixing iron with carbon",
        "Heating iron until it is red hot"],
    a: 0,
    ex: "Galvanising acts twice over: the zinc is a physical barrier, and being more reactive it also gives sacrificial protection if the layer is scratched." },

  { id: "q9-14", t: 9, s: "9.5", lv: "S", ty: "mcq",
    q: "How does sacrificial protection work?",
    o: ["The more reactive metal forms a barrier that keeps out air",
        "The more reactive metal loses electrons in preference to the iron, so the iron does not corrode",
        "The less reactive metal protects the iron by gaining electrons",
        "The metal is painted to keep out water"],
    a: 1,
    ex: "Blocks of zinc or magnesium attached to a ship's hull corrode instead of the iron because they lose electrons more readily. They are replaced when used up." },

  { id: "q9-15", t: 9, s: "9.6", lv: "C", ty: "mcq",
    q: "Which method is used to extract a metal that is more reactive than carbon?",
    o: ["Reduction with carbon", "Electrolysis of the molten compound",
        "Heating the ore in air", "Adding dilute acid"],
    a: 1,
    ex: "Carbon can only reduce oxides of metals below it in the series, such as iron and zinc. Aluminium and the metals above it need electrolysis." },

  { id: "q9-16", t: 9, s: "9.6", lv: "C", ty: "mcq",
    q: "What is the name of the main ore of iron used in the blast furnace?",
    o: ["Bauxite", "Hematite", "Limestone", "Cryolite"],
    a: 1,
    ex: "Hematite is iron(III) oxide. Bauxite is the aluminium ore, and limestone is added to the blast furnace to remove acidic impurities." },

  { id: "q9-17", t: 9, s: "9.6", lv: "S", ty: "mcq",
    q: "Which substance is the reducing agent for iron(III) oxide in the blast furnace?",
    o: ["Carbon dioxide", "Carbon monoxide", "Calcium oxide", "Oxygen"],
    a: 1,
    ex: "Fe2O3 + 3CO gives 2Fe + 3CO2. The carbon monoxide is made when carbon dioxide reacts with hot coke: CO2 + C gives 2CO." },

  { id: "q9-18", t: 9, s: "9.6", lv: "S", ty: "mcq",
    q: "What is the role of limestone in the blast furnace?",
    o: ["It reduces the iron oxide",
        "It decomposes to calcium oxide, which reacts with silicon(IV) oxide impurities to form slag",
        "It provides the heat for the reaction",
        "It removes carbon monoxide"],
    a: 1,
    ex: "CaCO3 gives CaO + CO2, then CaO + SiO2 gives CaSiO3. The molten slag floats on the iron and is run off separately." },

  { id: "q9-19", t: 9, s: "9.6", lv: "S", ty: "mcq",
    q: "Why is cryolite used in the extraction of aluminium?",
    o: ["It acts as a catalyst",
        "It dissolves the aluminium oxide so electrolysis can occur at a lower temperature, saving energy",
        "It removes impurities from the bauxite",
        "It protects the cathode"],
    a: 1,
    ex: "Pure aluminium oxide melts at over 2000 degrees Celsius. Dissolving it in molten cryolite lowers the operating temperature considerably." },

  { id: "q9-20", t: 9, s: "9.6", lv: "S", ty: "mcq",
    q: "Why must the carbon anodes in the aluminium extraction cell be replaced regularly?",
    o: ["They dissolve in the cryolite",
        "The oxygen produced at the anodes reacts with the hot carbon to form carbon dioxide, so the anodes burn away",
        "Aluminium is deposited on them",
        "They melt at the operating temperature"],
    a: 1,
    ex: "Oxygen is released at the anode and immediately attacks the hot graphite, so the electrodes are steadily consumed." },

  { id: "q9-21", t: 9, s: "9.4", lv: "C", ty: "mcq",
    q: "A student adds four metals to dilute hydrochloric acid. W fizzes violently, X fizzes steadily, Y fizzes very slowly and Z does not react. What is the order of reactivity, most reactive first?",
    o: ["W, X, Y, Z", "Z, Y, X, W", "X, W, Z, Y", "Y, Z, W, X"],
    a: 0,
    ex: "The more vigorous the reaction with the same acid, the more reactive the metal. Z is below hydrogen in the series, so it cannot displace hydrogen at all." },

  { id: "q9-22", t: 9, s: "9.1", lv: "C", ty: "mcq",
    q: "What is formed when a metal burns in oxygen?",
    o: ["A metal hydroxide", "A metal oxide", "A metal carbonate", "A salt and hydrogen"],
    a: 1,
    ex: "For example, 2Mg + O2 gives 2MgO, seen as a brilliant white flame leaving a white ash." },

  { id: "q9-23", t: 9, s: "9.5", lv: "C", ty: "multi",
    q: "Which are barrier methods of rust prevention? Select all that apply.",
    o: ["Painting", "Greasing", "Attaching blocks of magnesium", "Coating with plastic"],
    a: [0, 1, 3],
    ex: "Barrier methods simply keep oxygen and water away from the iron. Magnesium blocks work by sacrificial protection instead." },

  /* ---------------- Topic 10: Chemistry of the Environment ---------------- */
  { id: "q10-01", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "What is the chemical test for the presence of water?",
    o: ["Anhydrous copper(II) sulfate turns from white to blue",
        "Anhydrous copper(II) sulfate turns from blue to white",
        "Limewater turns milky",
        "Damp litmus paper is bleached"],
    a: 0,
    ex: "White anhydrous copper(II) sulfate turns blue, and blue anhydrous cobalt(II) chloride turns pink. Both show water is present but not that it is pure." },

  { id: "q10-02", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "How can you show that a sample of water is pure?",
    o: ["It turns anhydrous cobalt(II) chloride pink",
        "It boils at exactly 100 degrees Celsius and freezes at exactly 0 degrees Celsius at normal pressure",
        "It is colourless",
        "It conducts electricity"],
    a: 1,
    ex: "Only fixed, sharp melting and boiling points prove purity. Dissolved substances raise the boiling point and lower the freezing point." },

  { id: "q10-03", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "Why is distilled water used in practical chemistry rather than tap water?",
    o: ["It is cheaper",
        "Tap water contains dissolved substances that could interfere with the reaction",
        "Distilled water reacts more quickly",
        "Tap water does not dissolve solids"],
    a: 1,
    ex: "Dissolved ions in tap water, such as chloride and sulfate, could give false positive results in tests or take part in unwanted reactions." },

  { id: "q10-04", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "Why is chlorine added during the treatment of the domestic water supply?",
    o: ["To remove solid particles", "To kill bacteria and other microbes",
        "To improve the taste", "To remove dissolved salts"],
    a: 1,
    ex: "Sedimentation and filtration remove solids, carbon may remove tastes and odours, and chlorination sterilises the water." },

  { id: "q10-05", t: 10, s: "10.2", lv: "C", ty: "mcq",
    q: "Which three elements do NPK fertilisers supply?",
    o: ["Nitrogen, phosphorus, potassium", "Nitrogen, potassium, calcium",
        "Sodium, phosphorus, potassium", "Nitrogen, phosphorus, carbon"],
    a: 0,
    ex: "N, P and K are the letters used. Nitrogen supports leaf growth, phosphorus supports roots and potassium supports flowers and fruit." },

  { id: "q10-06", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "What is the approximate composition of clean, dry air?",
    o: ["78 per cent oxygen and 21 per cent nitrogen",
        "78 per cent nitrogen and 21 per cent oxygen",
        "50 per cent nitrogen and 50 per cent oxygen",
        "21 per cent nitrogen and 78 per cent carbon dioxide"],
    a: 1,
    ex: "About 78 per cent nitrogen, 21 per cent oxygen and the remaining 1 per cent mostly noble gases with a small amount of carbon dioxide." },

  { id: "q10-07", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "What is the main source of sulfur dioxide in the atmosphere?",
    o: ["Burning fossil fuels that contain sulfur compounds",
        "Respiration by animals", "Car engines burning nitrogen",
        "Decomposition of vegetation"],
    a: 0,
    ex: "Sulfur impurities in coal and oil burn to form sulfur dioxide, which dissolves in rain water and contributes to acid rain." },

  { id: "q10-08", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "Why is carbon monoxide harmful?",
    o: ["It causes acid rain",
        "It is toxic because it reduces the capacity of the blood to carry oxygen",
        "It damages the ozone layer",
        "It causes breathing problems by irritating the lungs only"],
    a: 1,
    ex: "Carbon monoxide is formed by incomplete combustion. It binds to haemoglobin in place of oxygen, and it is colourless and odourless." },

  { id: "q10-09", t: 10, s: "10.3", lv: "C", ty: "multi",
    q: "Which gases are greenhouse gases? Select all that apply.",
    o: ["Carbon dioxide", "Methane", "Nitrogen", "Oxygen"],
    a: [0, 1],
    ex: "Carbon dioxide and methane absorb the thermal energy radiated from the Earth's surface. Nitrogen and oxygen do not." },

  { id: "q10-10", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "Which statement best describes the greenhouse effect?",
    o: ["Greenhouse gases block sunlight from reaching the Earth",
        "Greenhouse gases absorb thermal energy radiated from the Earth's surface and re-emit some of it back, warming the atmosphere",
        "Greenhouse gases destroy the ozone layer",
        "Greenhouse gases make the rain acidic"],
    a: 1,
    ex: "Short wavelength radiation from the Sun passes through, but the longer wavelength radiation given off by the warmed Earth is absorbed and partly returned." },

  { id: "q10-11", t: 10, s: "10.3", lv: "C", ty: "multi",
    q: "Which are strategies to reduce the effects of climate change? Select all that apply.",
    o: ["Planting trees", "Reducing livestock farming",
        "Burning more coal", "Using hydrogen or renewable energy instead of fossil fuels"],
    a: [0, 1, 3],
    ex: "Trees remove carbon dioxide by photosynthesis, livestock produce methane, and replacing fossil fuels reduces carbon dioxide emissions at source." },

  { id: "q10-12", t: 10, s: "10.3", lv: "S", ty: "mcq",
    q: "How are oxides of nitrogen formed in a car engine?",
    o: ["Nitrogen in the fuel burns",
        "The high temperature makes nitrogen and oxygen from the air combine",
        "Nitrogen reacts with water vapour",
        "The catalytic converter produces them"],
    a: 1,
    ex: "Nitrogen is normally unreactive, but the very high temperature inside the engine supplies enough energy for it to react with oxygen." },

  { id: "q10-13", t: 10, s: "10.3", lv: "S", ty: "mcq",
    q: "What does a catalytic converter do to nitrogen oxides and carbon monoxide?",
    o: ["It converts them into nitrogen and carbon dioxide",
        "It converts them into ammonia and carbon",
        "It stores them until the engine cools",
        "It converts them into sulfur dioxide"],
    a: 0,
    ex: "The two pollutants react together on the catalyst surface, giving harmless nitrogen and much less harmful carbon dioxide." },

  { id: "q10-14", t: 10, s: "10.3", lv: "S", ty: "mcq",
    q: "Which word equation represents photosynthesis?",
    o: ["glucose + oxygen gives carbon dioxide + water",
        "carbon dioxide + water gives glucose + oxygen",
        "carbon dioxide + oxygen gives glucose + water",
        "glucose + water gives carbon dioxide + oxygen"],
    a: 1,
    ex: "It requires light and chlorophyll. The balanced symbol equation is 6CO2 + 6H2O gives C6H12O6 + 6O2." },

  { id: "q10-15", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "What is the main adverse effect of particulates in the air?",
    o: ["They cause acid rain",
        "They increase the risk of respiratory problems and some cancers",
        "They deplete the ozone layer",
        "They are toxic to the blood"],
    a: 1,
    ex: "Particulates are tiny solid particles from incomplete combustion. They are breathed deep into the lungs." },

  { id: "q10-16", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "Which pollutant is the main cause of acid rain along with sulfur dioxide?",
    o: ["Carbon monoxide", "Methane", "Oxides of nitrogen", "Particulates"],
    a: 2,
    ex: "Sulfur dioxide and nitrogen oxides dissolve in rain water to form acids that damage buildings, trees and aquatic life." },

  /* ---------------- Topic 11: Organic Chemistry ---------------- */
  { id: "q11-01", t: 11, s: "11.1", lv: "C", ty: "mcq",
    q: "What is a homologous series?",
    o: ["A group of compounds with the same molecular formula",
        "A family of similar compounds with the same functional group and general formula, differing by CH2",
        "A set of compounds that all contain carbon",
        "A group of isomers"],
    a: 1,
    ex: "Members of a homologous series show a gradual change in physical properties and have similar chemical properties because they share a functional group." },

  { id: "q11-02", t: 11, s: "11.1", lv: "C", ty: "mcq",
    q: "What does saturated mean when describing a hydrocarbon?",
    o: ["It contains as many carbon atoms as possible",
        "It contains only single carbon to carbon bonds",
        "It contains at least one carbon to carbon double bond",
        "It dissolves completely in water"],
    a: 1,
    ex: "Saturated means every carbon to carbon bond is a single bond, so no more atoms can be added. Alkenes are unsaturated because of the double bond." },

  { id: "q11-03", t: 11, s: "11.1", lv: "S", ty: "text",
    q: "What is the general formula of the alkenes? Write it in the form CnH2n+2 style.",
    disp: "CnH2n", a: ["cnh2n", "cnh2n ", "c n h 2n"],
    ex: "CnH2n. Alkanes are CnH2n+2, alcohols are CnH2n+1OH and carboxylic acids are CnH2n+1COOH." },

  { id: "q11-04", t: 11, s: "11.1", lv: "S", ty: "mcq",
    q: "What are structural isomers?",
    o: ["Compounds with the same molecular formula but different structural formulae",
        "Compounds with the same structure but different formulae",
        "Compounds in the same homologous series",
        "Compounds with the same relative molecular mass"],
    a: 0,
    ex: "Butane and methylpropane are both C4H10 but the atoms are joined differently, so their physical properties differ." },

  { id: "q11-05", t: 11, s: "11.2", lv: "C", ty: "text",
    q: "What is the name of the alkane with three carbon atoms?",
    disp: "Propane", a: ["propane"],
    ex: "Propane, C3H8. The prefixes for one to four carbons are meth, eth, prop and but." },

  { id: "q11-06", t: 11, s: "11.2", lv: "C", ty: "text",
    q: "What is the molecular formula of butane?",
    disp: "C4H10", a: ["c4h10", "c_4h_10"],
    ex: "C4H10. Using the general formula CnH2n+2 with n = 4 gives 2 x 4 + 2 = 10 hydrogen atoms." },

  { id: "q11-07", t: 11, s: "11.2", lv: "S", ty: "mcq",
    q: "Which name describes CH3CH(CH3)CH3?",
    o: ["Butane", "Methylpropane", "Propane", "Methylbutane"],
    a: 1,
    ex: "The longest chain is three carbons, which is propane, with a methyl branch on the middle carbon. It is an isomer of butane." },

  { id: "q11-08", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "What is the main constituent of natural gas?",
    o: ["Ethane", "Methane", "Propane", "Butane"],
    a: 1,
    ex: "Natural gas is mostly methane, CH4. Coal, natural gas and petroleum are the three fossil fuels." },

  { id: "q11-09", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "How is petroleum separated into useful fractions?",
    o: ["Filtration", "Fractional distillation", "Crystallisation", "Chromatography"],
    a: 1,
    ex: "The fractions have different boiling point ranges, so they condense at different heights in the fractionating column." },

  { id: "q11-10", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "Which fraction has the shortest molecules and the lowest boiling point?",
    o: ["Bitumen", "Diesel oil", "Refinery gas", "Kerosene"],
    a: 2,
    ex: "Shorter chains have weaker forces between molecules, so they boil at lower temperatures and are collected at the top of the column." },

  { id: "q11-11", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "Which fraction is used as fuel for aircraft?",
    o: ["Gasoline or petrol", "Kerosene or paraffin", "Bitumen", "Refinery gas"],
    a: 1,
    ex: "Kerosene is the jet fuel fraction. Petrol fuels cars, diesel fuels lorries, fuel oil is used for ships and heating, and bitumen surfaces roads." },

  { id: "q11-12", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "How does viscosity change as the hydrocarbon chain gets longer?",
    o: ["It increases", "It decreases", "It stays the same", "It increases then decreases"],
    a: 0,
    ex: "Longer molecules have stronger intermolecular forces, so they flow less easily and are more viscous, as well as being less volatile and harder to ignite." },

  { id: "q11-13", t: 11, s: "11.4", lv: "C", ty: "mcq",
    q: "What are the products of the complete combustion of an alkane?",
    o: ["Carbon monoxide and water", "Carbon dioxide and water",
        "Carbon and water", "Carbon dioxide and hydrogen"],
    a: 1,
    ex: "With plenty of oxygen the products are carbon dioxide and water. A limited supply gives incomplete combustion, forming carbon monoxide and soot." },

  { id: "q11-14", t: 11, s: "11.4", lv: "S", ty: "mcq",
    q: "What conditions are needed for methane to react with chlorine?",
    o: ["A nickel catalyst at 200 degrees Celsius", "Ultraviolet light",
        "Concentrated sulfuric acid", "High pressure only"],
    a: 1,
    ex: "This is a substitution reaction: CH4 + Cl2 gives CH3Cl + HCl in the presence of ultraviolet light. One hydrogen is replaced by one chlorine." },

  { id: "q11-15", t: 11, s: "11.5", lv: "C", ty: "mcq",
    q: "What is the test for an unsaturated hydrocarbon?",
    o: ["It turns limewater milky",
        "It decolourises aqueous bromine from orange to colourless",
        "It turns damp litmus paper red",
        "It gives a squeaky pop with a lighted splint"],
    a: 1,
    ex: "The bromine adds across the carbon to carbon double bond, so the orange colour disappears. An alkane leaves the colour unchanged." },

  { id: "q11-16", t: 11, s: "11.5", lv: "C", ty: "mcq",
    q: "What is cracking?",
    o: ["Joining small molecules to make a polymer",
        "Breaking larger alkane molecules into smaller, more useful molecules including alkenes and hydrogen",
        "Separating petroleum into fractions",
        "Burning hydrocarbons in a limited supply of air"],
    a: 1,
    ex: "Cracking converts the surplus long-chain fractions into short chains that are in demand, and supplies the alkenes needed for making polymers." },

  { id: "q11-17", t: 11, s: "11.5", lv: "S", ty: "mcq",
    q: "What is formed when ethene reacts with steam in the presence of a catalyst?",
    o: ["Ethane", "Ethanol", "Ethanoic acid", "Poly(ethene)"],
    a: 1,
    ex: "This is the addition of water across the double bond: C2H4 + H2O gives C2H5OH, using about 300 degrees Celsius, 60 atmospheres and a phosphoric acid catalyst." },

  { id: "q11-18", t: 11, s: "11.5", lv: "S", ty: "mcq",
    q: "What is formed when ethene reacts with hydrogen using a nickel catalyst?",
    o: ["Ethane", "Ethanol", "Ethyne", "Poly(ethene)"],
    a: 0,
    ex: "The hydrogen adds across the double bond, converting the unsaturated alkene into the saturated alkane ethane." },

  { id: "q11-19", t: 11, s: "11.6", lv: "C", ty: "multi",
    q: "Which conditions are needed for the fermentation of glucose? Select all that apply.",
    o: ["Yeast", "A temperature of about 25 to 35 degrees Celsius",
        "A temperature of about 300 degrees Celsius", "The absence of oxygen"],
    a: [0, 1, 3],
    ex: "Yeast provides the enzymes, moderate warmth keeps them active without denaturing them, and anaerobic conditions prevent the ethanol from being oxidised." },

  { id: "q11-20", t: 11, s: "11.6", lv: "S", ty: "mcq",
    q: "Which is an advantage of making ethanol by the catalytic addition of steam to ethene rather than by fermentation?",
    o: ["It uses a renewable raw material",
        "It is a continuous process that gives pure ethanol at a fast rate",
        "It uses less energy and lower pressures",
        "It works at room temperature"],
    a: 1,
    ex: "The hydration route is fast, continuous and gives a pure product, but it uses non-renewable petroleum and needs high temperature and pressure. Fermentation uses renewable sugar but is slow, batch based and gives dilute ethanol." },

  { id: "q11-21", t: 11, s: "11.6", lv: "C", ty: "multi",
    q: "What are the uses of ethanol? Select all that apply.",
    o: ["As a solvent", "As a fuel", "As a fertiliser", "As a catalyst"],
    a: [0, 1],
    ex: "Ethanol dissolves substances that water cannot, and burns cleanly: C2H5OH + 3O2 gives 2CO2 + 3H2O." },

  { id: "q11-22", t: 11, s: "11.7", lv: "C", ty: "mcq",
    q: "What is produced when ethanoic acid reacts with sodium carbonate?",
    o: ["Sodium ethanoate, water and carbon dioxide",
        "Sodium ethanoate and hydrogen",
        "Ethanol and carbon dioxide",
        "Sodium ethanoate only"],
    a: 0,
    ex: "Carboxylic acids behave like other acids, so with a carbonate they give a salt, water and carbon dioxide." },

  { id: "q11-23", t: 11, s: "11.7", lv: "S", ty: "mcq",
    q: "How can ethanol be oxidised to ethanoic acid in the laboratory?",
    o: ["By heating with a nickel catalyst",
        "By warming with acidified potassium manganate(VII)",
        "By adding concentrated sulfuric acid only",
        "By passing it over hot aluminium oxide"],
    a: 1,
    ex: "The purple manganate(VII) is decolourised as it oxidises the ethanol. Ethanol left open to air is also oxidised by bacteria, which is how wine turns to vinegar." },

  { id: "q11-24", t: 11, s: "11.7", lv: "S", ty: "text",
    q: "Name the ester formed from ethanol and ethanoic acid.",
    disp: "Ethyl ethanoate", a: ["ethyl ethanoate", "ethylethanoate"],
    ex: "Ethyl ethanoate. The alcohol gives the first part of the name and the acid gives the second. An acid catalyst is used and water is the other product." },

  { id: "q11-25", t: 11, s: "11.8", lv: "C", ty: "mcq",
    q: "What is a monomer?",
    o: ["A very large molecule made of repeating units",
        "The small molecule from which a polymer is built",
        "A molecule containing only one carbon atom",
        "A branch on a hydrocarbon chain"],
    a: 1,
    ex: "Many monomers join together to form a polymer. Ethene is the monomer for poly(ethene)." },

  { id: "q11-26", t: 11, s: "11.8", lv: "C", ty: "mcq",
    q: "Why are addition polymers such as poly(ethene) a pollution problem?",
    o: ["They are toxic",
        "They are non-biodegradable, so they persist in landfill and in the oceans",
        "They dissolve in water and poison rivers",
        "They react with oxygen in the air"],
    a: 1,
    ex: "The carbon backbone is not broken down by microorganisms. Burning them can release toxic gases such as hydrogen chloride from PVC." },

  { id: "q11-27", t: 11, s: "11.8", lv: "S", ty: "mcq",
    q: "What is the repeat unit of the polymer formed from propene, CH2=CHCH3?",
    o: ["-CH2-CH(CH3)-", "-CH2=CH(CH3)-", "-CH3-CH2-", "-CH2-CH2-"],
    a: 0,
    ex: "In addition polymerisation the double bond opens and the units join through single bonds. The side group is unchanged." },

  { id: "q11-28", t: 11, s: "11.8", lv: "S", ty: "mcq",
    q: "How does condensation polymerisation differ from addition polymerisation?",
    o: ["It produces no other product",
        "It joins monomers with two functional groups and loses a small molecule such as water each time a link forms",
        "It requires a carbon to carbon double bond",
        "It produces only one type of polymer"],
    a: 1,
    ex: "PET is a polyester made from a diol and a dicarboxylic acid, and nylon is a polyamide. Addition polymerisation has only one product." },

  { id: "q11-29", t: 11, s: "11.8", lv: "S", ty: "mcq",
    q: "Why is PET easier to recycle than poly(ethene)?",
    o: ["It melts at a lower temperature",
        "It can be broken down chemically back into its monomers, which can be used again",
        "It is biodegradable",
        "It dissolves in water"],
    a: 1,
    ex: "The ester links in a condensation polymer can be hydrolysed, returning the original monomers for re-polymerisation." },

  { id: "q11-30", t: 11, s: "11.1", lv: "C", ty: "mcq",
    q: "Which functional group belongs to the carboxylic acids?",
    o: ["-OH", "-COOH", "C=C", "-NH2"],
    a: 1,
    ex: "Alcohols have -OH, carboxylic acids have -COOH and alkenes contain a carbon to carbon double bond." },

  { id: "q11-31", t: 11, s: "11.4", lv: "C", ty: "mcq",
    q: "Why are alkanes described as generally unreactive?",
    o: ["They have no hydrogen atoms",
        "They are saturated with strong carbon to carbon and carbon to hydrogen single bonds and no functional group to attack",
        "They are too large to react",
        "They contain a double bond"],
    a: 1,
    ex: "Apart from combustion and substitution with halogens in ultraviolet light, alkanes take part in few reactions." },

  /* ---------------- Topic 12: Experimental Techniques and Analysis ---------------- */
  { id: "q12-01", t: 12, s: "12.1", lv: "C", ty: "mcq",
    q: "Which piece of apparatus measures a variable volume of a solution most accurately during a titration?",
    o: ["Measuring cylinder", "Burette", "Beaker", "Conical flask"],
    a: 1,
    ex: "A burette delivers any volume accurately and is read to the nearest 0.05 cm3. A pipette is more accurate still but only delivers one fixed volume." },

  { id: "q12-02", t: 12, s: "12.2", lv: "C", ty: "mcq",
    q: "What is the end point of a titration?",
    o: ["When the burette is empty",
        "When the indicator changes colour permanently, showing the reaction is just complete",
        "When the solution becomes hot",
        "When a precipitate forms"],
    a: 1,
    ex: "The indicator changes colour when the acid and alkali have exactly reacted. Adding the solution dropwise near the end point gives the best accuracy." },

  { id: "q12-03", t: 12, s: "12.2", lv: "S", ty: "num",
    q: "25.0 cm3 of sodium hydroxide solution is neutralised by 20.0 cm3 of 0.100 mol/dm3 hydrochloric acid. The ratio is 1 to 1. What is the concentration of the alkali in mol/dm3?",
    a: 0.08, tol: 0.002,
    ex: "n(HCl) = 0.100 x 0.0200 = 0.00200 mol. The ratio is 1 to 1 so n(NaOH) = 0.00200 mol. c = 0.00200 / 0.0250 = 0.0800 mol/dm3" },

  { id: "q12-04", t: 12, s: "12.2", lv: "S", ty: "num",
    q: "20.0 cm3 of 0.500 mol/dm3 sulfuric acid neutralises sodium hydroxide in the ratio 1 acid to 2 alkali. How many moles of sodium hydroxide react?",
    a: 0.02, tol: 0.0005,
    ex: "n(H2SO4) = 0.500 x 0.0200 = 0.0100 mol. The ratio is 1 to 2, so n(NaOH) = 2 x 0.0100 = 0.0200 mol" },

  { id: "q12-05", t: 12, s: "12.2", lv: "C", ty: "mcq",
    q: "Why is a conical flask, rather than a beaker, used for the solution being titrated?",
    o: ["It holds more liquid",
        "Its shape allows the contents to be swirled without splashing out",
        "It is more accurate at measuring volume",
        "It keeps the solution cool"],
    a: 1,
    ex: "The sloping sides mean the mixture can be swirled continuously to mix the reagents while nothing is lost over the rim." },

  { id: "q12-06", t: 12, s: "12.3", lv: "C", ty: "mcq",
    q: "In paper chromatography, why must the start line be drawn in pencil?",
    o: ["Pencil is easier to see",
        "Ink would dissolve in the solvent and move up the paper",
        "Pencil reacts with the solvent",
        "Pencil makes the paper stronger"],
    a: 1,
    ex: "Pencil is made of graphite, which is insoluble, so the line stays put. The start line must also sit above the level of the solvent." },

  { id: "q12-07", t: 12, s: "12.3", lv: "C", ty: "mcq",
    q: "A chromatogram of a substance shows a single spot. What does this indicate?",
    o: ["The substance is impure", "The substance is likely to be pure",
        "The substance is a mixture of two dyes", "The solvent was wrong"],
    a: 1,
    ex: "A pure substance gives one spot in every solvent. Two or more spots means the sample is a mixture." },

  { id: "q12-08", t: 12, s: "12.3", lv: "S", ty: "num",
    q: "A spot travels 4.5 cm while the solvent front travels 9.0 cm. Calculate the Rf value.",
    a: 0.5, tol: 0.01,
    ex: "Rf = distance moved by the spot / distance moved by the solvent = 4.5 / 9.0 = 0.50. Rf values are always between 0 and 1 and have no units." },

  { id: "q12-09", t: 12, s: "12.3", lv: "C", ty: "mcq",
    q: "Why is a locating agent sometimes needed in chromatography?",
    o: ["To make the solvent rise faster",
        "To make colourless spots visible",
        "To dissolve the sample",
        "To hold the paper in place"],
    a: 1,
    ex: "Substances such as amino acids and sugars are colourless, so the dried chromatogram is sprayed with a locating agent to reveal the spots." },

  { id: "q12-10", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "Which technique separates a solvent from a solution and keeps the solvent?",
    o: ["Filtration", "Simple distillation", "Crystallisation", "Chromatography"],
    a: 1,
    ex: "The solvent evaporates, passes into the condenser and is collected as the distillate. Crystallisation keeps the solute instead." },

  { id: "q12-11", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "How would you separate a mixture of ethanol and water?",
    o: ["Filtration", "Fractional distillation", "Crystallisation", "Using a separating funnel"],
    a: 1,
    ex: "Both are liquids that mix completely, but they have different boiling points, so a fractionating column separates them. Ethanol boils first at 78 degrees Celsius." },

  { id: "q12-12", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "How would you separate sand from salt solution?",
    o: ["Filtration, because sand is insoluble and stays in the filter paper",
        "Distillation, because sand has a higher boiling point",
        "Chromatography",
        "Crystallisation"],
    a: 0,
    ex: "The insoluble sand is the residue, and the salt solution passes through as the filtrate. Crystallising the filtrate would then recover the salt." },

  { id: "q12-13", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "A sample melts over the range 52 to 58 degrees Celsius, but the pure substance melts sharply at 60 degrees Celsius. What does this show?",
    o: ["The sample is pure",
        "The sample is impure, because impurities lower the melting point and widen the range",
        "The thermometer is broken",
        "The sample is a different element"],
    a: 1,
    ex: "Pure substances melt and boil at sharp, fixed temperatures. Impurities lower the melting point and spread it over a range." },

  { id: "q12-14", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "Aqueous sodium hydroxide is added to a solution, giving a light blue precipitate that does not dissolve in excess. Which cation is present?",
    o: ["Fe2+", "Cu2+", "Zn2+", "Ca2+"],
    a: 1,
    ex: "Copper(II) gives a light blue precipitate. With aqueous ammonia it also gives a light blue precipitate but this dissolves in excess to give a dark blue solution." },

  { id: "q12-15", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "A solution gives a white precipitate with aqueous sodium hydroxide that dissolves in excess to give a colourless solution. Which cation is present?",
    o: ["Ca2+", "Zn2+", "Fe3+", "Cu2+"],
    a: 1,
    ex: "Zinc gives a white precipitate that is soluble in excess of both sodium hydroxide and ammonia. Calcium gives a white precipitate that is insoluble in excess." },

  { id: "q12-16", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "What colour precipitate do iron(III) ions give with aqueous sodium hydroxide?",
    o: ["Green", "Red-brown", "White", "Light blue"],
    a: 1,
    ex: "Iron(III) gives a red-brown precipitate and iron(II) gives a green one. Neither dissolves in excess." },

  { id: "q12-17", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "How do you test for ammonium ions?",
    o: ["Add aqueous sodium hydroxide and warm, then test the gas with damp red litmus paper",
        "Add dilute nitric acid then silver nitrate",
        "Carry out a flame test",
        "Add aqueous barium nitrate"],
    a: 0,
    ex: "Ammonia gas is given off, which turns damp red litmus paper blue. It is the only common alkaline gas." },

  { id: "q12-18", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "Which ion gives a lilac colour in a flame test?",
    o: ["Lithium", "Sodium", "Potassium", "Copper(II)"],
    a: 2,
    ex: "Lithium gives red, sodium gives yellow, potassium gives lilac and copper(II) gives blue-green." },

  { id: "q12-19", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "A solution is acidified with dilute nitric acid and aqueous silver nitrate is added. A cream precipitate forms. Which ion is present?",
    o: ["Chloride", "Bromide", "Iodide", "Sulfate"],
    a: 1,
    ex: "Chloride gives white, bromide gives cream and iodide gives yellow. The acid is added first to remove carbonate ions that would also give a precipitate." },

  { id: "q12-20", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "How do you test for sulfate ions?",
    o: ["Add dilute nitric acid then aqueous barium nitrate, giving a white precipitate",
        "Add aqueous sodium hydroxide and warm",
        "Add dilute hydrochloric acid and test the gas with limewater",
        "Carry out a flame test"],
    a: 0,
    ex: "Barium sulfate is a white insoluble solid. Acidifying first prevents a false positive from carbonate or sulfite ions." },

  { id: "q12-21", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "How do you test for carbonate ions?",
    o: ["Add aqueous ammonia",
        "Add dilute acid and bubble the gas produced through limewater, which turns milky",
        "Add silver nitrate solution",
        "Add aqueous sodium hydroxide and aluminium foil"],
    a: 1,
    ex: "The acid releases carbon dioxide, which forms a white precipitate of calcium carbonate in limewater, making it look milky." },

  { id: "q12-22", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "How do you test for nitrate ions?",
    o: ["Add aqueous sodium hydroxide and aluminium foil, warm, then test for ammonia",
        "Add dilute nitric acid then silver nitrate",
        "Add limewater",
        "Add acidified potassium manganate(VII)"],
    a: 0,
    ex: "The aluminium reduces the nitrate to ammonia, which turns damp red litmus paper blue." },

  { id: "q12-23", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "Which gas relights a glowing splint?",
    o: ["Hydrogen", "Oxygen", "Carbon dioxide", "Ammonia"],
    a: 1,
    ex: "Oxygen relights a glowing splint. Hydrogen gives a squeaky pop with a lighted splint, and carbon dioxide puts a splint out and turns limewater milky." },

  { id: "q12-24", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "A gas bleaches damp litmus paper. Which gas is it?",
    o: ["Ammonia", "Chlorine", "Sulfur dioxide", "Hydrogen"],
    a: 1,
    ex: "Chlorine turns damp litmus red then bleaches it white. Ammonia turns damp red litmus blue." },

  { id: "q12-25", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "How is sulfur dioxide identified?",
    o: ["It turns limewater milky",
        "It turns acidified aqueous potassium manganate(VII) from purple to colourless",
        "It relights a glowing splint",
        "It turns damp red litmus blue"],
    a: 1,
    ex: "Sulfur dioxide is a reducing agent, so it decolourises the purple manganate(VII) solution." },

  { id: "q12-26", t: 12, s: "12.1", lv: "C", ty: "mcq",
    q: "Which apparatus delivers one fixed volume of solution most accurately?",
    o: ["Burette", "Pipette", "Measuring cylinder", "Beaker"],
    a: 1,
    ex: "A pipette is calibrated for a single volume such as 25.0 cm3 and is more accurate than a measuring cylinder for that volume." },

  { id: "q12-27", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "Which method would you use to obtain pure salt crystals from salt solution?",
    o: ["Filtration",
        "Crystallisation, by evaporating some of the water and leaving the rest to crystallise slowly",
        "Chromatography",
        "Adding more solvent"],
    a: 1,
    ex: "Heating to the point of crystallisation and then cooling slowly gives well formed crystals, which are then filtered off and dried." },

  { id: "q12-28", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "A green precipitate forms when aqueous sodium hydroxide is added and it does not dissolve in excess. Which cation is present?",
    o: ["Iron(II)", "Iron(III)", "Chromium(III)", "Copper(II)"],
    a: 0,
    ex: "Iron(II) gives a green precipitate insoluble in excess. Chromium(III) also gives a green precipitate but it dissolves in excess sodium hydroxide." }
];
