/* Question bank, part 5: the interactive formats.
   balance -> type a coefficient into every gap of an equation
   order   -> put the cards into the right sequence
   match   -> pair each item with its partner */

window.QUESTIONS_5 = [

  /* ---------------- Balancing equations ---------------- */
  { id: "b-01", t: 3, s: "3.1", lv: "C", ty: "balance",
    q: "Balance the complete combustion of methane.",
    eq: { lhs: [["CH4", 1], ["O2", 2]], rhs: [["CO2", 1], ["H2O", 2]] },
    ex: "CH4 + 2O2 gives CO2 + 2H2O. Balance carbon first, then hydrogen, and leave oxygen until last because it appears in both products." },

  { id: "b-02", t: 3, s: "3.1", lv: "C", ty: "balance",
    q: "Balance the burning of magnesium in oxygen.",
    eq: { lhs: [["Mg", 2], ["O2", 1]], rhs: [["MgO", 2]] },
    ex: "2Mg + O2 gives 2MgO. One oxygen molecule supplies two oxygen atoms, so two units of magnesium oxide form." },

  { id: "b-03", t: 3, s: "3.1", lv: "C", ty: "balance",
    q: "Balance the reaction of magnesium with dilute hydrochloric acid.",
    eq: { lhs: [["Mg", 1], ["HCl", 2]], rhs: [["MgCl2", 1], ["H2", 1]] },
    ex: "Mg + 2HCl gives MgCl2 + H2. Two chlorides are needed for the salt, and the two hydrogens they bring make one hydrogen molecule." },

  { id: "b-04", t: 3, s: "3.1", lv: "C", ty: "balance",
    q: "Balance the reaction of calcium carbonate with dilute hydrochloric acid.",
    eq: { lhs: [["CaCO3", 1], ["HCl", 2]], rhs: [["CaCl2", 1], ["H2O", 1], ["CO2", 1]] },
    ex: "CaCO3 + 2HCl gives CaCl2 + H2O + CO2. Acid plus carbonate always gives a salt, water and carbon dioxide." },

  { id: "b-05", t: 3, s: "3.1", lv: "C", ty: "balance",
    q: "Balance the reaction of sodium with water.",
    eq: { lhs: [["Na", 2], ["H2O", 2]], rhs: [["NaOH", 2], ["H2", 1]] },
    ex: "2Na + 2H2O gives 2NaOH + H2. Half of the hydrogen ends up in the hydroxide and half is released as gas." },

  { id: "b-06", t: 9, s: "9.6", lv: "S", ty: "balance",
    q: "Balance the reduction of iron(III) oxide in the blast furnace.",
    eq: { lhs: [["Fe2O3", 1], ["CO", 3]], rhs: [["Fe", 2], ["CO2", 3]] },
    ex: "Fe2O3 + 3CO gives 2Fe + 3CO2. Each carbon monoxide takes one oxygen atom from the ore, and there are three to remove." },

  { id: "b-07", t: 6, s: "6.3", lv: "S", ty: "balance",
    q: "Balance the reaction in the Haber process.",
    eq: { lhs: [["N2", 1], ["H2", 3]], rhs: [["NH3", 2]] },
    ex: "N2 + 3H2 gives 2NH3. Four molecules of gas become two, which is why high pressure improves the yield." },

  { id: "b-08", t: 6, s: "6.3", lv: "S", ty: "balance",
    q: "Balance the key step of the Contact process.",
    eq: { lhs: [["SO2", 2], ["O2", 1]], rhs: [["SO3", 2]] },
    ex: "2SO2 + O2 gives 2SO3. Three molecules of gas become two, so raising the pressure would shift the equilibrium to the right." },

  { id: "b-09", t: 11, s: "11.4", lv: "C", ty: "balance",
    q: "Balance the complete combustion of propane, C3H8.",
    eq: { lhs: [["C3H8", 1], ["O2", 5]], rhs: [["CO2", 3], ["H2O", 4]] },
    ex: "C3H8 + 5O2 gives 3CO2 + 4H2O. Three carbons need 3 CO2 and eight hydrogens need 4 H2O, which is 6 + 4 = 10 oxygen atoms, so 5 O2." },

  { id: "b-10", t: 11, s: "11.6", lv: "C", ty: "balance",
    q: "Balance the complete combustion of ethanol, C2H5OH.",
    eq: { lhs: [["C2H5OH", 1], ["O2", 3]], rhs: [["CO2", 2], ["H2O", 3]] },
    ex: "C2H5OH + 3O2 gives 2CO2 + 3H2O. Remember the oxygen atom already inside the ethanol when you count up the right hand side." },

  { id: "b-11", t: 8, s: "8.3", lv: "S", ty: "balance",
    q: "Balance the displacement of iodine by chlorine from potassium iodide.",
    eq: { lhs: [["KI", 2], ["Cl2", 1]], rhs: [["KCl", 2], ["I2", 1]] },
    ex: "2KI + Cl2 gives 2KCl + I2. Chlorine is the more reactive halogen, so it takes the place of iodine and the solution turns brown." },

  { id: "b-12", t: 7, s: "7.1", lv: "C", ty: "balance",
    q: "Balance the neutralisation of sulfuric acid by sodium hydroxide.",
    eq: { lhs: [["NaOH", 2], ["H2SO4", 1]], rhs: [["Na2SO4", 1], ["H2O", 2]] },
    ex: "2NaOH + H2SO4 gives Na2SO4 + 2H2O. Sulfuric acid is dibasic, so it needs two units of alkali." },

  { id: "b-13", t: 6, s: "6.4", lv: "S", ty: "balance",
    q: "Balance the reduction of copper(II) oxide by hydrogen.",
    eq: { lhs: [["CuO", 1], ["H2", 1]], rhs: [["Cu", 1], ["H2O", 1]] },
    ex: "CuO + H2 gives Cu + H2O. Hydrogen takes the oxygen, so it is oxidised and acts as the reducing agent." },

  { id: "b-14", t: 9, s: "9.1", lv: "C", ty: "balance",
    q: "Balance the burning of aluminium in oxygen.",
    eq: { lhs: [["Al", 4], ["O2", 3]], rhs: [["Al2O3", 2]] },
    ex: "4Al + 3O2 gives 2Al2O3. Doubling the product to clear the fraction is the usual trick when a formula contains an odd number of oxygens." },

  { id: "b-15", t: 6, s: "6.3", lv: "C", ty: "balance",
    q: "Balance the thermal decomposition of calcium carbonate.",
    eq: { lhs: [["CaCO3", 1]], rhs: [["CaO", 1], ["CO2", 1]] },
    ex: "CaCO3 gives CaO + CO2. This one is already balanced as written, which is worth checking before you start changing numbers." },

  { id: "b-16", t: 3, s: "3.1", lv: "S", ty: "balance",
    q: "Balance the reaction of zinc with dilute sulfuric acid.",
    eq: { lhs: [["Zn", 1], ["H2SO4", 1]], rhs: [["ZnSO4", 1], ["H2", 1]] },
    ex: "Zn + H2SO4 gives ZnSO4 + H2. The sulfate ion moves across unchanged, so only the hydrogen and zinc need checking." },

  { id: "b-17", t: 8, s: "8.2", lv: "C", ty: "balance",
    q: "Balance the reaction of potassium with water.",
    eq: { lhs: [["K", 2], ["H2O", 2]], rhs: [["KOH", 2], ["H2", 1]] },
    ex: "2K + 2H2O gives 2KOH + H2. All the Group I metals follow this pattern with water." },

  { id: "b-18", t: 11, s: "11.5", lv: "S", ty: "balance",
    q: "Balance the complete combustion of ethene, C2H4.",
    eq: { lhs: [["C2H4", 1], ["O2", 3]], rhs: [["CO2", 2], ["H2O", 2]] },
    ex: "C2H4 + 3O2 gives 2CO2 + 2H2O. Two carbons give 2 CO2 and four hydrogens give 2 H2O, needing 6 oxygen atoms in total." },

  /* ---------------- Ordering ---------------- */
  { id: "o-01", t: 9, s: "9.4", lv: "C", ty: "order",
    q: "Put these metals in order of reactivity, most reactive first.",
    a: ["Potassium", "Calcium", "Magnesium", "Zinc", "Copper"],
    ex: "The full series runs potassium, sodium, calcium, magnesium, aluminium, carbon, zinc, iron, hydrogen, copper, silver, gold." },

  { id: "o-02", t: 11, s: "11.3", lv: "C", ty: "order",
    q: "Put these petroleum fractions in order of increasing boiling point.",
    a: ["Refinery gas", "Gasoline", "Kerosene", "Diesel oil", "Bitumen"],
    ex: "Boiling point rises with chain length, so this is also the order in which they are collected going down the fractionating column." },

  { id: "o-03", t: 1, s: "1.1", lv: "C", ty: "order",
    q: "Put these states in order of increasing average particle energy.",
    a: ["Solid", "Liquid", "Gas"],
    ex: "Energy has to be supplied to melt and then to boil a substance, so the gas state holds the most energy." },

  { id: "o-04", t: 7, s: "7.1", lv: "C", ty: "order",
    q: "Put these solutions in order of increasing pH.",
    a: ["Hydrochloric acid", "Ethanoic acid", "Pure water", "Ammonia solution", "Sodium hydroxide"],
    ex: "Hydrochloric acid is strong so has the lowest pH, ethanoic acid is weak, water is neutral at 7, and sodium hydroxide is a strong alkali." },

  { id: "o-05", t: 7, s: "7.3", lv: "C", ty: "order",
    q: "Put the steps for preparing copper(II) sulfate crystals in the right order.",
    a: ["Add excess copper(II) oxide to warm dilute sulfuric acid",
        "Filter off the unreacted copper(II) oxide",
        "Heat the filtrate to the point of crystallisation",
        "Leave the solution to cool so crystals form",
        "Dry the crystals between filter papers"],
    ex: "The excess guarantees all the acid is used, filtering removes what is left over, and slow cooling gives well formed crystals." },

  { id: "o-06", t: 12, s: "12.2", lv: "C", ty: "order",
    q: "Put the steps of an acid-base titration in the right order.",
    a: ["Rinse the burette with the acid and fill it",
        "Pipette 25.0 cm3 of the alkali into a conical flask",
        "Add a few drops of indicator to the flask",
        "Run acid in with swirling until the colour just changes",
        "Record the burette reading and repeat for concordant results"],
    ex: "Rinsing with the solution being used stops dilution changing the concentration. The first run is usually rough and is not counted." },

  { id: "o-07", t: 9, s: "9.6", lv: "S", ty: "order",
    q: "Put the blast furnace stages in the order they happen.",
    a: ["Hot air is blasted in and the coke burns to form carbon dioxide",
        "The carbon dioxide reacts with more hot coke to form carbon monoxide",
        "The carbon monoxide reduces iron(III) oxide to iron",
        "Molten iron runs to the bottom of the furnace and is tapped off"],
    ex: "Burning the coke supplies the heat, then makes the carbon monoxide that does the reducing." },

  { id: "o-08", t: 8, s: "8.2", lv: "C", ty: "order",
    q: "Put these Group I metals in order of increasing reactivity.",
    a: ["Lithium", "Sodium", "Potassium"],
    ex: "Reactivity increases down Group I because the outer electron is further from the nucleus and more shielded, so it is lost more easily." },

  { id: "o-09", t: 2, s: "2.6", lv: "C", ty: "order",
    q: "Put these substances in order of increasing melting point.",
    a: ["Iodine", "Sodium chloride", "Diamond"],
    ex: "Iodine is simple molecular with weak forces between molecules, sodium chloride is a giant ionic lattice, and diamond is giant covalent with the strongest structure of the three." },

  { id: "o-10", t: 11, s: "11.2", lv: "C", ty: "order",
    q: "Put these alkanes in order of increasing boiling point.",
    a: ["Methane", "Ethane", "Propane", "Butane"],
    ex: "Each extra CH2 makes the molecule larger, so the intermolecular forces are stronger and more energy is needed to separate the molecules." },

  { id: "o-11", t: 10, s: "10.1", lv: "C", ty: "order",
    q: "Put the stages of treating the domestic water supply in the right order.",
    a: ["Screening to remove large objects",
        "Sedimentation to let fine solids settle",
        "Filtration through sand",
        "Chlorination to kill microbes"],
    ex: "Solids are taken out from largest to smallest before the water is finally sterilised." },

  { id: "o-12", t: 12, s: "12.4", lv: "C", ty: "order",
    q: "Put the steps for obtaining pure salt from rock salt in the right order.",
    a: ["Crush the rock salt",
        "Stir it with warm water to dissolve the salt",
        "Filter to remove the insoluble sand",
        "Evaporate the filtrate to crystallise the salt"],
    ex: "Dissolving separates the soluble salt from the insoluble rock, filtration removes the rock, and crystallisation recovers the salt." },

  { id: "o-13", t: 8, s: "8.3", lv: "C", ty: "order",
    q: "Put these halogens in order of increasing density.",
    a: ["Chlorine", "Bromine", "Iodine"],
    ex: "Density increases down the group, which matches the change from gas to liquid to solid at room temperature." },

  /* ---------------- Matching ---------------- */
  { id: "m-01", t: 12, s: "12.5", lv: "C", ty: "match",
    q: "Match each ion to what you see when aqueous sodium hydroxide is added.",
    pairs: [["Copper(II)", "Light blue precipitate, insoluble in excess"],
            ["Iron(II)", "Green precipitate, insoluble in excess"],
            ["Iron(III)", "Red-brown precipitate, insoluble in excess"],
            ["Zinc", "White precipitate, soluble in excess"]],
    ex: "Colour identifies the transition metal ions. Zinc and chromium(III) are the two that redissolve in excess sodium hydroxide." },

  { id: "m-02", t: 12, s: "12.5", lv: "C", ty: "match",
    q: "Match each ion to its flame colour.",
    pairs: [["Lithium", "Red"], ["Sodium", "Yellow"],
            ["Potassium", "Lilac"], ["Copper(II)", "Blue-green"]],
    ex: "These four are the only flame tests named in the syllabus, so they are worth learning as a set." },

  { id: "m-03", t: 12, s: "12.5", lv: "C", ty: "match",
    q: "Match each gas to its test result.",
    pairs: [["Hydrogen", "Squeaky pop with a lighted splint"],
            ["Oxygen", "Relights a glowing splint"],
            ["Carbon dioxide", "Turns limewater milky"],
            ["Chlorine", "Bleaches damp litmus paper"]],
    ex: "Ammonia is the fifth to know: it turns damp red litmus blue, and it is the only common alkaline gas." },

  { id: "m-04", t: 12, s: "12.5", lv: "C", ty: "match",
    q: "Match each halide ion to the precipitate it gives with acidified silver nitrate.",
    pairs: [["Chloride", "White precipitate"],
            ["Bromide", "Cream precipitate"],
            ["Iodide", "Yellow precipitate"]],
    ex: "The colour deepens down the group. Acidify with dilute nitric acid first so that carbonate ions cannot give a false positive." },

  { id: "m-05", t: 11, s: "11.1", lv: "C", ty: "match",
    q: "Match each homologous series to its functional group.",
    pairs: [["Alkanes", "Only single carbon to carbon bonds"],
            ["Alkenes", "A carbon to carbon double bond"],
            ["Alcohols", "The -OH group"],
            ["Carboxylic acids", "The -COOH group"]],
    ex: "The functional group is what gives each series its characteristic reactions." },

  { id: "m-06", t: 6, s: "6.3", lv: "S", ty: "match",
    q: "Match each industrial process to its catalyst.",
    pairs: [["Haber process", "Iron"],
            ["Contact process", "Vanadium(V) oxide"],
            ["Cracking", "Silica or alumina"],
            ["Hydration of ethene", "Phosphoric acid"]],
    ex: "Each catalyst lowers the activation energy for that particular reaction, allowing a workable rate at a lower temperature." },

  { id: "m-07", t: 2, s: "2.6", lv: "C", ty: "match",
    q: "Match each structure to the property it explains.",
    pairs: [["Diamond", "Extremely hard, used in cutting tools"],
            ["Graphite", "Conducts electricity and is slippery"],
            ["Simple molecular", "Low melting and boiling points"],
            ["Giant ionic", "Conducts only when molten or dissolved"]],
    ex: "Every property question comes back to the structure and the strength of the forces that have to be overcome." },

  { id: "m-08", t: 12, s: "12.1", lv: "C", ty: "match",
    q: "Match each piece of apparatus to what it is used for.",
    pairs: [["Burette", "Measuring a variable volume accurately"],
            ["Pipette", "Delivering one fixed volume accurately"],
            ["Measuring cylinder", "Measuring an approximate volume"],
            ["Thermometer", "Measuring temperature"]],
    ex: "The burette and the pipette are the accurate pieces. A measuring cylinder is fine for rough volumes only." },

  { id: "m-09", t: 12, s: "12.4", lv: "C", ty: "match",
    q: "Match each mixture to the technique that separates it.",
    pairs: [["Sand and water", "Filtration"],
            ["Salt from salt solution", "Crystallisation"],
            ["Ethanol and water", "Fractional distillation"],
            ["Coloured dyes in ink", "Chromatography"]],
    ex: "Choose the technique from the difference you can exploit: solubility, boiling point or attraction to paper." },

  { id: "m-10", t: 12, s: "12.5", lv: "C", ty: "match",
    q: "Match each anion to its test.",
    pairs: [["Carbonate", "Add dilute acid, the gas turns limewater milky"],
            ["Sulfate", "Acidify, then add aqueous barium nitrate for a white precipitate"],
            ["Nitrate", "Add sodium hydroxide and aluminium foil, warm, then test for ammonia"],
            ["Chloride", "Acidify, then add aqueous silver nitrate for a white precipitate"]],
    ex: "Sulfate and chloride both give white precipitates, so the reagent added is what tells them apart." },

  { id: "m-11", t: 8, s: "8.1", lv: "C", ty: "match",
    q: "Match each element to its group.",
    pairs: [["Sodium", "Group I"], ["Calcium", "Group II"],
            ["Bromine", "Group VII"], ["Neon", "Group 0"]],
    ex: "The group number equals the number of outer-shell electrons, except for Group 0 where the shell is full." },

  { id: "m-12", t: 9, s: "9.6", lv: "C", ty: "match",
    q: "Match each metal to how it is extracted.",
    pairs: [["Aluminium", "Electrolysis of the molten oxide"],
            ["Iron", "Reduction with carbon in a blast furnace"],
            ["Gold", "Found uncombined in the ground"]],
    ex: "The method follows the position in the reactivity series: above carbon needs electrolysis, below carbon can be reduced, and the least reactive are found native." },

  { id: "m-13", t: 10, s: "10.3", lv: "C", ty: "match",
    q: "Match each pollutant to its main source.",
    pairs: [["Carbon monoxide", "Incomplete combustion of fuels"],
            ["Sulfur dioxide", "Burning fuels that contain sulfur compounds"],
            ["Oxides of nitrogen", "The high temperature inside car engines"],
            ["Methane", "Livestock farming and decomposing landfill waste"]],
    ex: "Knowing the source usually tells you the fix, from catalytic converters to removing sulfur from fuel." },

  { id: "m-14", t: 11, s: "11.8", lv: "S", ty: "match",
    q: "Match each polymer to its type.",
    pairs: [["Poly(ethene)", "Addition polymer"],
            ["PET", "Condensation polyester"],
            ["Nylon", "Condensation polyamide"]],
    ex: "Addition polymers come from monomers with a C=C double bond. Condensation polymers need two functional groups and release a small molecule as they form." },

  { id: "m-15", t: 5, s: "5.1", lv: "C", ty: "match",
    q: "Match each process to its energy change.",
    pairs: [["Combustion of methane", "Exothermic"],
            ["Photosynthesis", "Endothermic"],
            ["Neutralisation", "Exothermic"],
            ["Thermal decomposition of limestone", "Endothermic"]],
    ex: "If a reaction needs a continuous supply of energy to keep going, it is endothermic." },

  { id: "m-16", t: 4, s: "4.1", lv: "S", ty: "match",
    q: "Match each electrolysis to the product formed at the anode.",
    pairs: [["Molten lead(II) bromide", "Bromine"],
            ["Concentrated aqueous sodium chloride", "Chlorine"],
            ["Dilute sulfuric acid", "Oxygen"],
            ["Aqueous copper(II) sulfate with copper electrodes", "The anode dissolves, no gas forms"]],
    ex: "At the anode, a concentrated halide gives the halogen, otherwise hydroxide ions from water are discharged and oxygen is released." }
];
