/* Question bank, part 6: extra depth, weighted towards applying the ideas
   rather than recalling them. */

window.QUESTIONS_6 = [

  /* ---- Topic 1 ---- */
  { id: "x1-01", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Why does a solid keep its own shape?",
    o: ["Its particles are heavier than those in a liquid",
        "Its particles are held in fixed positions by strong forces of attraction",
        "Its particles do not move at all",
        "Its particles are further apart than in a liquid"],
    a: 1,
    ex: "The particles still vibrate, but they cannot change places, so the shape is fixed." },

  { id: "x1-02", t: 1, s: "1.1", lv: "S", ty: "mcq",
    q: "A gas is heated in a sealed container of fixed volume. What happens to the pressure?",
    o: ["It rises, because the particles hit the walls more often and harder",
        "It falls, because the particles spread out",
        "It stays the same, because the volume cannot change",
        "It falls, because the particles collide with each other more"],
    a: 0,
    ex: "Pressure comes from collisions with the walls. Faster particles hit more frequently and with more force, so the pressure rises." },

  { id: "x1-03", t: 1, s: "1.2", lv: "S", ty: "mcq",
    q: "Why is diffusion much slower in a liquid than in a gas?",
    o: ["Liquid particles are heavier",
        "Liquid particles are close together, so a particle collides constantly and moves through the liquid slowly",
        "Liquid particles do not move",
        "Liquids have no concentration gradient"],
    a: 1,
    ex: "Gas particles have long free runs between collisions. In a liquid the particles are touching, so progress is slow even though the motion is just as random." },

  { id: "x1-04", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Steam at 100 degrees Celsius causes worse scalds than water at 100 degrees Celsius. Why?",
    o: ["Steam is hotter than the water",
        "Steam releases extra energy to the skin as it condenses",
        "Steam particles are heavier",
        "Steam is a chemical, water is not"],
    a: 1,
    ex: "Condensing is exothermic. The energy that was needed to boil the water is given back out when the steam turns to liquid on the skin." },

  { id: "x1-05", t: 1, s: "1.2", lv: "C", ty: "mcq",
    q: "A gas jar of brown bromine vapour is placed under a gas jar of air and the cover is removed. What happens?",
    o: ["Nothing, because bromine is denser than air",
        "The brown colour spreads evenly through both jars over time",
        "The bromine stays entirely in the lower jar",
        "The bromine reacts with the air"],
    a: 1,
    ex: "Diffusion happens even against gravity, because the random motion of the particles mixes the two gases until the concentration is even." },

  /* ---- Topic 2 ---- */
  { id: "x2-01", t: 2, s: "2.4", lv: "C", ty: "num",
    q: "How many electrons does a magnesium ion, Mg2+, contain? Magnesium has proton number 12.",
    a: 10, tol: 0,
    ex: "The atom has 12 electrons. Losing 2 to form the 2+ ion leaves 10, the same as neon." },

  { id: "x2-02", t: 2, s: "2.2", lv: "C", ty: "num",
    q: "An atom is written as having mass number 40 and proton number 18. How many neutrons does it have?",
    a: 22, tol: 0,
    ex: "40 - 18 = 22 neutrons. This atom is argon." },

  { id: "x2-03", t: 2, s: "2.5", lv: "C", ty: "num",
    q: "How many shared pairs of electrons are there in a molecule of ammonia, NH3?",
    a: 3, tol: 0,
    ex: "Nitrogen forms one bond to each of the three hydrogen atoms. The fourth pair on the nitrogen is a lone pair and is not shared." },

  { id: "x2-04", t: 2, s: "2.2", lv: "C", ty: "mcq",
    q: "Why do Group 0 elements not usually form ions?",
    o: ["Their atoms are too small",
        "They already have a full outer shell, so there is nothing to gain by losing or gaining electrons",
        "Their nuclei are unstable",
        "They have no outer-shell electrons"],
    a: 1,
    ex: "Other atoms form ions in order to reach the arrangement noble gases already have." },

  { id: "x2-05", t: 2, s: "2.4", lv: "S", ty: "text",
    q: "Aluminium ions are Al3+ and sulfate ions are SO4 2-. What is the formula of aluminium sulfate?",
    disp: "Al2(SO4)3", a: ["al2(so4)3", "al2so43", "al2 (so4)3"],
    ex: "Al2(SO4)3. Two 3+ ions give 6+ and three 2- ions give 6-, so the charges cancel. The bracket keeps the whole sulfate group together." },

  { id: "x2-06", t: 2, s: "2.1", lv: "C", ty: "mcq",
    q: "A diagram shows a container holding molecules made of two different types of atom bonded together, and nothing else. What does it show?",
    o: ["A mixture of two elements", "A single compound",
        "A mixture of a compound and an element", "A single element"],
    a: 1,
    ex: "All the particles are identical and each contains more than one type of atom chemically joined, so this is a pure compound." },

  { id: "x2-07", t: 2, s: "2.6", lv: "C", ty: "mcq",
    q: "Why is graphite used to make the electrodes for electrolysis?",
    o: ["It is very cheap only",
        "It conducts electricity, has a very high melting point and is unreactive with most electrolytes",
        "It is a good insulator",
        "It reacts with the electrolyte to speed up the process"],
    a: 1,
    ex: "The delocalised electrons carry the current, and the giant covalent structure survives the high temperatures involved." },

  { id: "x2-08", t: 2, s: "2.3", lv: "C", ty: "mcq",
    q: "Two isotopes of the same element differ in which of these?",
    o: ["Number of protons", "Number of neutrons",
        "Number of outer-shell electrons", "Chemical properties"],
    a: 1,
    ex: "Only the neutron count changes, which alters the mass but leaves the chemistry identical." },

  /* ---- Topic 3 ---- */
  { id: "x3-01", t: 3, s: "3.2", lv: "S", ty: "num",
    q: "Calculate the relative formula mass of hydrated copper(II) sulfate, CuSO4.5H2O. Use Ar: Cu = 64, S = 32, O = 16, H = 1",
    a: 250, tol: 0,
    ex: "CuSO4 = 64 + 32 + 64 = 160. Each water is 18, so 5 x 18 = 90. Total = 160 + 90 = 250" },

  { id: "x3-02", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "Calculate the percentage by mass of oxygen in water, H2O, to one decimal place. Use Ar: H = 1, O = 16",
    a: 88.9, tol: 0.2,
    ex: "Mr = 18. Percentage = 16 / 18 x 100 = 88.9 per cent" },

  { id: "x3-03", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What volume of carbon dioxide, in dm3 at rtp, is produced when 25 g of calcium carbonate decomposes? Mr of CaCO3 = 100",
    a: 6, tol: 0.1,
    ex: "n(CaCO3) = 25 / 100 = 0.25 mol. The ratio is 1 to 1, so n(CO2) = 0.25 mol. Volume = 0.25 x 24 = 6 dm3" },

  { id: "x3-04", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "A compound is found to contain 2.4 g of carbon and 0.8 g of hydrogen only. What is the ratio of carbon to hydrogen atoms? Give the number of hydrogen atoms per carbon atom.",
    a: 4, tol: 0,
    ex: "C: 2.4 / 12 = 0.20 mol. H: 0.8 / 1 = 0.80 mol. Dividing by 0.20 gives 1 : 4, so the empirical formula is CH4." },

  { id: "x3-05", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What mass of sodium hydroxide, in g, is needed to make 500 cm3 of a 0.100 mol/dm3 solution? Mr of NaOH = 40",
    a: 2, tol: 0.05,
    ex: "n = c x V = 0.100 x 0.500 = 0.0500 mol. m = n x M = 0.0500 x 40 = 2.0 g" },

  { id: "x3-06", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "48 g of magnesium is burned in 16 g of oxygen. 2Mg + O2 gives 2MgO. How many moles of magnesium oxide can form? Ar: Mg = 24, O = 16",
    a: 1, tol: 0.02,
    ex: "n(Mg) = 48 / 24 = 2.0 mol and n(O2) = 16 / 32 = 0.50 mol. 2 mol of Mg would need 1 mol of O2, so oxygen is limiting and gives 2 x 0.50 = 1.0 mol of MgO." },

  { id: "x3-07", t: 3, s: "3.1", lv: "S", ty: "mcq",
    q: "Which set of state symbols is correct for the reaction of solid zinc with dilute hydrochloric acid?",
    o: ["Zn(s) + 2HCl(aq) gives ZnCl2(aq) + H2(g)",
        "Zn(l) + 2HCl(l) gives ZnCl2(s) + H2(g)",
        "Zn(s) + 2HCl(g) gives ZnCl2(aq) + H2(aq)",
        "Zn(aq) + 2HCl(aq) gives ZnCl2(s) + H2(l)"],
    a: 0,
    ex: "The metal is a solid, the acid and the salt formed are in solution, and hydrogen leaves as a gas." },

  { id: "x3-08", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "Calculate the relative formula mass of ammonium sulfate, (NH4)2SO4. Use Ar: N = 14, H = 1, S = 32, O = 16",
    a: 132, tol: 0,
    ex: "Mr = 2 x (14 + 4) + 32 + 64 = 36 + 96 = 132" },

  /* ---- Topic 4 ---- */
  { id: "x4-01", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Which half-equation shows hydrogen being formed at the cathode?",
    o: ["2H+ + 2e- gives H2", "H2 gives 2H+ + 2e-",
        "2H2O gives O2 + 4H+ + 4e-", "H+ + OH- gives H2O"],
    a: 0,
    ex: "Hydrogen ions gain electrons at the negative cathode, which is reduction. Two are needed to make one molecule." },

  { id: "x4-02", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Molten sodium chloride is electrolysed. What forms at each electrode?",
    o: ["Sodium at the cathode, chlorine at the anode",
        "Hydrogen at the cathode, chlorine at the anode",
        "Sodium at the anode, chlorine at the cathode",
        "Hydrogen at the cathode, oxygen at the anode"],
    a: 0,
    ex: "There is no water present, so the metal itself is formed at the cathode. In aqueous solution hydrogen would be released instead." },

  { id: "x4-03", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "During the purification of copper, why does the mass of the cathode increase by roughly the same amount as the anode loses?",
    o: ["Copper is transferred through the electrolyte as Cu2+ ions",
        "Copper evaporates from one electrode to the other",
        "The electrolyte is converted into copper",
        "The cathode reacts with the sulfate ions"],
    a: 0,
    ex: "The anode dissolves as Cu gives Cu2+ + 2e-, the ions travel through the solution, and Cu2+ + 2e- gives Cu at the cathode." },

  { id: "x4-04", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Why is electroplating used on steel cutlery?",
    o: ["To make the steel conduct electricity",
        "To give an attractive finish and protect the steel from corrosion",
        "To make the cutlery magnetic",
        "To lower the melting point"],
    a: 1,
    ex: "A thin layer of a less reactive metal such as silver or chromium is both decorative and protective." },

  { id: "x4-05", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Dilute sulfuric acid is electrolysed. Which observation is correct?",
    o: ["Twice the volume of gas collects at the anode",
        "Twice the volume of gas collects at the cathode",
        "Equal volumes of gas collect at both electrodes",
        "Gas collects only at the anode"],
    a: 1,
    ex: "Water is being split, and the formula H2O means twice as much hydrogen as oxygen is released. Hydrogen appears at the cathode." },

  { id: "x4-06", t: 4, s: "4.2", lv: "S", ty: "multi",
    q: "Which are advantages of a hydrogen-oxygen fuel cell over a petrol engine? Select all that apply.",
    o: ["It produces no carbon dioxide at the point of use",
        "It is more efficient at converting the fuel's energy into useful energy",
        "Hydrogen is easy to store in a small space",
        "It has fewer moving parts, so less energy is wasted as heat and sound"],
    a: [0, 1, 3],
    ex: "Storage and transport of hydrogen is the main problem with fuel cells, not an advantage." },

  /* ---- Topic 5 ---- */
  { id: "x5-01", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "Two reactions have activation energies of 40 and 120 kJ/mol. Which statement is correct?",
    o: ["The reaction with Ea = 120 kJ/mol is faster at the same temperature",
        "The reaction with Ea = 40 kJ/mol is faster, because more collisions have enough energy",
        "They proceed at the same rate",
        "Neither reaction can occur"],
    a: 1,
    ex: "A lower barrier means a greater proportion of collisions is successful, which is exactly how a catalyst speeds a reaction up." },

  { id: "x5-02", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "In an exothermic reaction, how do the bonds in the products compare with those in the reactants?",
    o: ["The bonds in the products are stronger overall",
        "The bonds in the products are weaker overall",
        "The bonds are identical",
        "No bonds are formed"],
    a: 0,
    ex: "More energy is released making the new bonds than was needed to break the old ones, which means the new bonds are stronger overall." },

  { id: "x5-03", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Which industrial process relies on an endothermic reaction driven by strong heating?",
    o: ["The combustion of natural gas",
        "The thermal decomposition of limestone to make quicklime",
        "The neutralisation of acid waste",
        "The rusting of iron"],
    a: 1,
    ex: "Calcium carbonate only decomposes while energy is being supplied, which is why lime kilns are heated continuously." },

  { id: "x5-04", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Two students measure the temperature rise for the same reaction. One uses an open beaker, the other an insulated cup with a lid. Whose value is closer to the true energy change?",
    o: ["The open beaker, because air can circulate",
        "The insulated cup, because less energy escapes to the surroundings",
        "They will be identical",
        "Neither, the apparatus makes no difference"],
    a: 1,
    ex: "Energy lost to the room makes the measured rise smaller than it should be, so insulation gives the better result." },

  /* ---- Topic 6 ---- */
  { id: "x6-01", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Why does the rate of a reaction between an acid and a metal decrease as time goes on?",
    o: ["The temperature falls to zero",
        "The acid is used up, so its concentration falls and collisions become less frequent",
        "The metal becomes more reactive",
        "The activation energy increases"],
    a: 1,
    ex: "The graph is steepest at the start and flattens out as the reactants run down, becoming horizontal when the reaction stops." },

  { id: "x6-02", t: 6, s: "6.2", lv: "S", ty: "mcq",
    q: "Increasing the pressure speeds up a reaction between two gases. Why?",
    o: ["The particles gain more energy",
        "The particles are pushed into a smaller volume, so they collide more often",
        "The activation energy is lowered",
        "The particles become larger"],
    a: 1,
    ex: "Raising the pressure of a gas has the same effect as raising the concentration of a solution: the particles are more crowded." },

  { id: "x6-03", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "On a graph of gas volume against time, two curves reach the same final volume but one is steeper at the start. What does this show?",
    o: ["The steeper curve used more reactant",
        "The steeper curve was faster but produced the same amount of product",
        "The steeper curve had a different reaction",
        "The flatter curve is more accurate"],
    a: 1,
    ex: "Rate and yield are separate ideas. Only a change in the amount of limiting reactant changes the final volume." },

  { id: "x6-04", t: 6, s: "6.4", lv: "S", ty: "num",
    q: "What is the oxidation number of sulfur in sulfuric acid, H2SO4?",
    a: 6, tol: 0,
    ex: "Two hydrogens give +2 and four oxygens give -8. For a neutral molecule, sulfur must be +6." },

  { id: "x6-05", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "In the reaction CuO + Mg gives Cu + MgO, which statement is correct?",
    o: ["Magnesium is reduced and copper(II) oxide is oxidised",
        "Magnesium is oxidised and copper(II) oxide is reduced",
        "Neither species changes",
        "Both species are oxidised"],
    a: 1,
    ex: "Magnesium gains oxygen and loses electrons, so it is oxidised and acts as the reducing agent. The copper oxide loses its oxygen." },

  { id: "x6-06", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "At equilibrium, more reactant is added to a closed system. What happens?",
    o: ["The position of equilibrium shifts towards the products",
        "The position of equilibrium shifts towards the reactants",
        "Nothing changes",
        "The reaction stops"],
    a: 0,
    ex: "The system responds to oppose the change, so it uses up some of the added reactant by making more product." },

  { id: "x6-07", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "Why is a temperature of about 450 degrees Celsius used in the Haber process, rather than a much lower one?",
    o: ["A lower temperature would give a lower yield",
        "A lower temperature would give a better yield but the rate would be far too slow to be economic",
        "The catalyst only works above 400 degrees Celsius in every case",
        "Ammonia decomposes below 450 degrees Celsius"],
    a: 1,
    ex: "The forward reaction is exothermic, so a cool reactor favours a high yield. The temperature chosen is a compromise between yield and rate." },

  { id: "x6-08", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "A student wants to measure the rate of a reaction that gives off a gas. Which two methods are suitable?",
    o: ["Measuring the volume of gas collected over time, or the loss in mass over time",
        "Measuring the colour of the flask, or its temperature",
        "Weighing the gas syringe only",
        "Timing how long the flask takes to cool"],
    a: 0,
    ex: "Both track how much product has formed at each moment, which is what rate means." },

  /* ---- Topic 7 ---- */
  { id: "x7-01", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Which acid and which base would you use to make potassium nitrate?",
    o: ["Nitric acid and potassium hydroxide",
        "Hydrochloric acid and potassium hydroxide",
        "Nitric acid and sodium hydroxide",
        "Sulfuric acid and potassium carbonate"],
    a: 0,
    ex: "The metal comes from the base and the rest of the salt name comes from the acid, so a nitrate needs nitric acid." },

  { id: "x7-02", t: 7, s: "7.2", lv: "S", ty: "mcq",
    q: "Aluminium oxide reacts with both dilute hydrochloric acid and aqueous sodium hydroxide. What does this show?",
    o: ["It is a basic oxide", "It is an acidic oxide",
        "It is an amphoteric oxide", "It is a neutral oxide"],
    a: 2,
    ex: "Reacting with both an acid and an alkali is the definition of an amphoteric oxide. Zinc oxide behaves the same way." },

  { id: "x7-03", t: 7, s: "7.1", lv: "S", ty: "mcq",
    q: "Equal concentrations of hydrochloric acid and ethanoic acid are tested with a conductivity meter. What is observed?",
    o: ["The ethanoic acid conducts better",
        "The hydrochloric acid conducts better, because it contains more ions",
        "They conduct equally",
        "Neither conducts"],
    a: 1,
    ex: "Being fully dissociated, hydrochloric acid has a much higher concentration of ions, and it is the ions that carry the current." },

  { id: "x7-04", t: 7, s: "7.3", lv: "S", ty: "mcq",
    q: "Which pair of solutions would you mix to precipitate barium sulfate?",
    o: ["Barium nitrate and sodium sulfate",
        "Barium sulfate and water",
        "Barium carbonate and sodium chloride",
        "Barium hydroxide and sodium nitrate"],
    a: 0,
    ex: "Both starting solutions must be soluble. Mixing them brings Ba2+ and SO4 2- together, and the insoluble barium sulfate drops out as a white solid." },

  { id: "x7-05", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "Universal indicator turns orange in a solution. What is the approximate pH?",
    o: ["1", "5", "9", "13"],
    a: 1,
    ex: "Red is strongly acidic at about pH 1, orange or yellow is weakly acidic around pH 5 to 6, green is neutral and blue to purple is alkaline." },

  { id: "x7-06", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Why is the reaction mixture warmed when making a soluble salt from an acid and an insoluble metal oxide?",
    o: ["To make the salt more soluble only",
        "To speed up the reaction so the acid is used up in a reasonable time",
        "To evaporate the acid",
        "To decompose the oxide"],
    a: 1,
    ex: "Warming increases the rate. The mixture is not boiled, because that would lose acid and water." },

  { id: "x7-07", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "Indigestion tablets containing magnesium hydroxide relieve excess stomach acid. What type of reaction is this?",
    o: ["Oxidation", "Neutralisation", "Precipitation", "Thermal decomposition"],
    a: 1,
    ex: "A base reacts with the hydrochloric acid in the stomach to make a salt and water, raising the pH towards neutral." },

  /* ---- Topic 8 ---- */
  { id: "x8-01", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "Francium is at the bottom of Group I. Which prediction is most likely to be correct?",
    o: ["It reacts less vigorously with water than caesium",
        "It reacts extremely violently with water and has a low melting point",
        "It is a hard metal with a high melting point",
        "It does not conduct electricity"],
    a: 1,
    ex: "Continuing the trends down the group gives greater reactivity and a lower melting point." },

  { id: "x8-02", t: 8, s: "8.4", lv: "C", ty: "mcq",
    q: "A compound dissolves to give a bright blue solution. Which type of element is it most likely to contain?",
    o: ["A Group I metal", "A Group VII element",
        "A transition element", "A noble gas"],
    a: 2,
    ex: "Coloured compounds are a hallmark of the transition elements. Group I compounds are typically white and give colourless solutions." },

  { id: "x8-03", t: 8, s: "8.3", lv: "S", ty: "mcq",
    q: "Bromine water is added to colourless potassium iodide solution. What is seen and why?",
    o: ["No change, because bromine is less reactive than iodine",
        "The solution turns brown, because bromine displaces iodine",
        "A white precipitate forms",
        "The solution turns pale green"],
    a: 1,
    ex: "Bromine is above iodine in Group VII, so it is the more reactive and takes the electrons: Br2 + 2KI gives 2KBr + I2." },

  { id: "x8-04", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "Going from left to right across Period 3, from sodium to argon, which change happens?",
    o: ["The elements become more metallic",
        "The elements change from metallic to non-metallic in character",
        "The number of occupied electron shells increases",
        "The proton number decreases"],
    a: 1,
    ex: "Sodium, magnesium and aluminium are metals, silicon is in between, and phosphorus onwards are non-metals. The shell count stays at three." },

  { id: "x8-05", t: 8, s: "8.1", lv: "S", ty: "mcq",
    q: "An element has the electronic configuration 2,8,5. What charge will its ion carry?",
    o: ["5+", "3+", "3-", "5-"],
    a: 2,
    ex: "It is in Group V, so it gains 3 electrons to complete the outer shell, giving a 3- ion such as the nitride ion." },

  { id: "x8-06", t: 8, s: "8.5", lv: "C", ty: "mcq",
    q: "Why is helium used in balloons rather than hydrogen?",
    o: ["Helium is lighter than hydrogen",
        "Helium is unreactive, so it will not burn or explode",
        "Helium is cheaper",
        "Helium is denser than air"],
    a: 1,
    ex: "Hydrogen is less dense but highly flammable. Helium gives most of the lift with none of the fire risk." },

  /* ---- Topic 9 ---- */
  { id: "x9-01", t: 9, s: "9.3", lv: "C", ty: "mcq",
    q: "Why is stainless steel used for cutlery and sinks rather than pure iron?",
    o: ["It is cheaper than iron",
        "It is harder and does not rust, because of the chromium and nickel it contains",
        "It has a lower melting point",
        "It is a better conductor of electricity"],
    a: 1,
    ex: "Alloying changes both the mechanical properties and the resistance to corrosion." },

  { id: "x9-02", t: 9, s: "9.5", lv: "C", ty: "mcq",
    q: "Blocks of magnesium are bolted to the steel hull of a ship. Why?",
    o: ["To add weight for stability",
        "To corrode in place of the iron, because magnesium is more reactive",
        "To make a barrier that keeps water out",
        "To conduct electricity away from the hull"],
    a: 1,
    ex: "This is sacrificial protection. The magnesium loses electrons more readily, so it is oxidised instead of the iron and is replaced when used up." },

  { id: "x9-03", t: 9, s: "9.4", lv: "S", ty: "mcq",
    q: "An iron nail is placed in blue copper(II) sulfate solution. What is observed?",
    o: ["No change, because iron is less reactive than copper",
        "The nail becomes coated with pink-brown copper and the blue colour fades",
        "The nail dissolves completely and a gas is given off",
        "A white precipitate forms"],
    a: 1,
    ex: "Iron is above copper in the reactivity series, so it displaces the copper: Fe + CuSO4 gives FeSO4 + Cu." },

  { id: "x9-04", t: 9, s: "9.1", lv: "C", ty: "mcq",
    q: "Why is gold used for jewellery and electrical contacts?",
    o: ["It is the best conductor of all metals",
        "It is very unreactive, so it keeps its shine and does not corrode",
        "It is very hard",
        "It has the highest melting point"],
    a: 1,
    ex: "Gold sits at the bottom of the reactivity series, so it does not react with air, water or most chemicals." },

  { id: "x9-05", t: 9, s: "9.6", lv: "C", ty: "mcq",
    q: "Zinc is below carbon in the reactivity series. How is zinc extracted from zinc oxide?",
    o: ["By electrolysis of the molten oxide",
        "By heating the oxide with carbon, which reduces it",
        "By adding dilute acid",
        "It is found uncombined in the ground"],
    a: 1,
    ex: "Carbon can only reduce the oxides of metals below it in the series, and zinc qualifies." },

  { id: "x9-06", t: 9, s: "9.4", lv: "C", ty: "mcq",
    q: "What is produced when calcium reacts with cold water?",
    o: ["Calcium oxide and hydrogen",
        "Calcium hydroxide and hydrogen",
        "Calcium carbonate and oxygen",
        "Calcium chloride and water"],
    a: 1,
    ex: "Ca + 2H2O gives Ca(OH)2 + H2. The steady stream of bubbles and the cloudy solution are the usual observations." },

  { id: "x9-07", t: 9, s: "9.4", lv: "C", ty: "mcq",
    q: "Metal X displaces metal Y from its salt solution, but Y displaces metal Z. What is the order of reactivity, most reactive first?",
    o: ["X, Y, Z", "Z, Y, X", "Y, X, Z", "X, Z, Y"],
    a: 0,
    ex: "A metal can only displace one that is less reactive than itself, so X is above Y and Y is above Z." },

  /* ---- Topic 10 ---- */
  { id: "x10-01", t: 10, s: "10.3", lv: "C", ty: "num",
    q: "What percentage of clean, dry air is oxygen?",
    a: 21, tol: 1,
    ex: "About 21 per cent oxygen, with 78 per cent nitrogen and the remaining 1 per cent made up of noble gases and carbon dioxide." },

  { id: "x10-02", t: 10, s: "10.3", lv: "C", ty: "multi",
    q: "What are the adverse effects of acid rain? Select all that apply.",
    o: ["It damages buildings and statues made of limestone",
        "It lowers the pH of lakes and harms aquatic life",
        "It increases crop yields",
        "It damages trees and leaches nutrients from soil"],
    a: [0, 1, 3],
    ex: "Acid rain forms when sulfur dioxide and nitrogen oxides dissolve in rain water. Nothing about it helps plant growth." },

  { id: "x10-03", t: 10, s: "10.3", lv: "S", ty: "mcq",
    q: "Inside a catalytic converter, carbon monoxide and nitrogen monoxide react together. What are the products?",
    o: ["Carbon dioxide and nitrogen",
        "Carbon and nitrogen dioxide",
        "Carbon dioxide and ammonia",
        "Carbon monoxide and oxygen"],
    a: 0,
    ex: "2CO + 2NO gives 2CO2 + N2. Two harmful gases are converted into one harmless gas and one that is much less harmful." },

  { id: "x10-04", t: 10, s: "10.2", lv: "C", ty: "mcq",
    q: "Which element in an NPK fertiliser mainly supports the growth of flowers and fruit?",
    o: ["Nitrogen", "Phosphorus", "Potassium", "Carbon"],
    a: 2,
    ex: "Nitrogen drives leaf growth, phosphorus supports the roots, and potassium supports flowers and fruit." },

  { id: "x10-05", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "A sample of water boils at 102 degrees Celsius. What does this show?",
    o: ["It is pure water",
        "It contains dissolved substances, so it is impure",
        "It has been heated too quickly",
        "It contains no water"],
    a: 1,
    ex: "Dissolved solutes raise the boiling point and lower the freezing point, so a sharp 100 degrees Celsius is the sign of purity." },

  { id: "x10-06", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "Which strategy would most directly reduce carbon dioxide emissions from transport?",
    o: ["Planting more trees",
        "Switching vehicles to hydrogen fuel cells or electricity from renewable sources",
        "Reducing livestock farming",
        "Adding sulfur to fuels"],
    a: 1,
    ex: "Planting trees removes carbon dioxide after it is emitted, but changing the fuel stops the emission happening at all." },

  /* ---- Topic 11 ---- */
  { id: "x11-01", t: 11, s: "11.1", lv: "S", ty: "num",
    q: "How many structural isomers does C4H10 have?",
    a: 2, tol: 0,
    ex: "Butane, an unbranched chain of four carbons, and methylpropane, a three carbon chain with a methyl branch." },

  { id: "x11-02", t: 11, s: "11.5", lv: "C", ty: "mcq",
    q: "Decane, C10H22, is cracked to give octane, C8H18, and one other product. What is it?",
    o: ["Ethene, C2H4", "Ethane, C2H6", "Methane, CH4", "Hydrogen only"],
    a: 0,
    ex: "The atoms must balance: C10H22 gives C8H18 + C2H4. Cracking always produces at least one unsaturated molecule." },

  { id: "x11-03", t: 11, s: "11.6", lv: "C", ty: "mcq",
    q: "What are the products of the complete combustion of ethanol?",
    o: ["Carbon monoxide and water", "Carbon dioxide and water",
        "Ethanoic acid and water", "Carbon and hydrogen"],
    a: 1,
    ex: "C2H5OH + 3O2 gives 2CO2 + 3H2O. Ethanol burns with a clean blue flame, which is why it is used as a fuel." },

  { id: "x11-04", t: 11, s: "11.7", lv: "S", ty: "mcq",
    q: "What conditions are needed to make an ester from an alcohol and a carboxylic acid?",
    o: ["Ultraviolet light", "An acid catalyst, usually with warming",
        "A nickel catalyst at high pressure", "Yeast at 30 degrees Celsius"],
    a: 1,
    ex: "Concentrated sulfuric acid is the usual catalyst. Water is formed alongside the ester, so this is a condensation reaction." },

  { id: "x11-05", t: 11, s: "11.5", lv: "S", ty: "mcq",
    q: "What is formed when ethene reacts with bromine?",
    o: ["1,2-dibromoethane, and the orange colour disappears",
        "Bromoethane and hydrogen bromide",
        "Ethane and bromine gas",
        "Poly(ethene)"],
    a: 0,
    ex: "The double bond opens and a bromine atom adds to each carbon. This addition reaction is the basis of the test for unsaturation." },

  { id: "x11-06", t: 11, s: "11.5", lv: "C", ty: "mcq",
    q: "Why are alkenes more reactive than alkanes?",
    o: ["They contain more hydrogen",
        "The carbon to carbon double bond can open up so that atoms add across it",
        "They have larger molecules",
        "They are saturated"],
    a: 1,
    ex: "A saturated alkane has nowhere to add extra atoms without first breaking a bond, so it is far less reactive." },

  { id: "x11-07", t: 11, s: "11.6", lv: "C", ty: "mcq",
    q: "Which gas is given off during the fermentation of glucose?",
    o: ["Hydrogen", "Oxygen", "Carbon dioxide", "Methane"],
    a: 2,
    ex: "C6H12O6 gives 2C2H5OH + 2CO2. Bubbling the gas through limewater turns it milky, which confirms carbon dioxide." },

  { id: "x11-08", t: 11, s: "11.8", lv: "C", ty: "mcq",
    q: "Which problem is caused by disposing of addition polymers in landfill?",
    o: ["They decompose quickly and release methane",
        "They are non-biodegradable, so they take up space for a very long time",
        "They dissolve into groundwater",
        "They react with soil minerals"],
    a: 1,
    ex: "The unreactive carbon backbone is not broken down by microorganisms, which is why recycling and reducing use matter so much." },

  /* ---- Topic 12 ---- */
  { id: "x12-01", t: 12, s: "12.3", lv: "S", ty: "num",
    q: "A spot moves 3.0 cm while the solvent front moves 12.0 cm. Calculate the Rf value to two decimal places.",
    a: 0.25, tol: 0.01,
    ex: "Rf = 3.0 / 12.0 = 0.25. The value has no units because it is a ratio of two lengths." },

  { id: "x12-02", t: 12, s: "12.2", lv: "S", ty: "num",
    q: "25.0 cm3 of 0.200 mol/dm3 sodium hydroxide is exactly neutralised by 12.5 cm3 of hydrochloric acid. The ratio is 1 to 1. What is the concentration of the acid in mol/dm3?",
    a: 0.4, tol: 0.01,
    ex: "n(NaOH) = 0.200 x 0.0250 = 0.00500 mol, so n(HCl) = 0.00500 mol. c = 0.00500 / 0.0125 = 0.400 mol/dm3" },

  { id: "x12-03", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "In filtration, what are the solid and the liquid that pass through called?",
    o: ["The residue stays in the paper and the filtrate passes through",
        "The filtrate stays in the paper and the residue passes through",
        "Both are called the residue",
        "The solid is the distillate"],
    a: 0,
    ex: "Residue is what is left behind, filtrate is what runs through. The distillate is the liquid collected from a distillation." },

  { id: "x12-04", t: 12, s: "12.3", lv: "C", ty: "mcq",
    q: "A chromatogram of a food colouring shows three separate spots. What does this tell you?",
    o: ["The colouring is a pure substance",
        "The colouring is a mixture of at least three substances",
        "The solvent was contaminated",
        "The paper was faulty"],
    a: 1,
    ex: "A pure substance gives a single spot. Each additional spot is another component that has separated out." },

  { id: "x12-05", t: 12, s: "12.5", lv: "C", ty: "mcq",
    q: "A white precipitate forms when aqueous sodium hydroxide is added, and it does not dissolve in excess. Which ion could be present?",
    o: ["Calcium", "Zinc", "Copper(II)", "Iron(III)"],
    a: 0,
    ex: "Calcium gives a white precipitate that stays. Zinc also gives a white precipitate, but that one dissolves in excess." },

  { id: "x12-06", t: 12, s: "12.1", lv: "C", ty: "mcq",
    q: "Which apparatus would you use to measure 24.6 cm3 of a solution accurately?",
    o: ["A 25 cm3 pipette", "A burette",
        "A 100 cm3 measuring cylinder", "A beaker with a scale"],
    a: 1,
    ex: "A pipette only delivers its one fixed volume. A burette can deliver any volume within its range, read to 0.05 cm3." },

  { id: "x12-07", t: 12, s: "12.2", lv: "C", ty: "mcq",
    q: "Why is the conical flask rinsed with distilled water rather than with the alkali before a titration?",
    o: ["Distilled water is cheaper",
        "Rinsing with alkali would leave extra alkali behind and increase the titre",
        "Water reacts with the indicator",
        "The flask must be dry"],
    a: 1,
    ex: "Distilled water left in the flask does not change the number of moles of alkali present, so it does not affect the result." }
];

/* Merge every bank into the single list the app uses. */
window.QUESTIONS = [].concat(
  window.QUESTIONS_1, window.QUESTIONS_2, window.QUESTIONS_3,
  window.QUESTIONS_4, window.QUESTIONS_5, window.QUESTIONS_6
);
