/* Question bank, part 1: Topics 1 to 4.
   ty: mcq (a = index) | multi (a = [indices]) | num (a = value, tol) | text (a = [accepted])
   lv: C = Core, S = Supplement */

window.QUESTIONS_1 = [

  /* ---------------- Topic 1: States of Matter ---------------- */
  { id: "q1-01", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "How are the particles arranged and how do they move in a solid?",
    o: ["Regularly arranged, touching, vibrating about fixed positions",
        "Randomly arranged, touching, sliding past each other",
        "Randomly arranged, far apart, moving quickly in all directions",
        "Regularly arranged, far apart, vibrating slowly"],
    a: 0,
    ex: "Solids have a regular arrangement with particles in contact. They cannot move from place to place, so they only vibrate about fixed positions." },

  { id: "q1-02", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Which set of properties belongs to a gas?",
    o: ["Fixed shape, fixed volume, cannot be compressed",
        "No fixed shape, fixed volume, cannot be compressed",
        "No fixed shape, no fixed volume, easily compressed",
        "Fixed shape, no fixed volume, easily compressed"],
    a: 2,
    ex: "Gas particles are far apart with large spaces between them, so a gas fills its container completely and can be squeezed into a smaller volume." },

  { id: "q1-03", t: 1, s: "1.1", lv: "C", ty: "text",
    q: "Name the change of state when a gas turns into a liquid.",
    disp: "Condensation", a: ["condensation", "condensing", "condense"],
    ex: "Condensation. The particles lose energy, move more slowly and the attractive forces pull them together into a liquid." },

  { id: "q1-04", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Which change of state is endothermic?",
    o: ["Freezing", "Condensing", "Melting", "None of them"],
    a: 2,
    ex: "Melting takes in energy from the surroundings to overcome the forces holding the particles in fixed positions. Freezing and condensing release energy." },

  { id: "q1-05", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "A fixed mass of gas is heated at constant pressure. What happens to its volume?",
    o: ["It increases", "It decreases", "It stays the same", "It first decreases then increases"],
    a: 0,
    ex: "Heating gives the particles more kinetic energy so they move faster and hit the walls harder and more often. To keep the pressure constant, the volume must increase." },

  { id: "q1-06", t: 1, s: "1.1", lv: "S", ty: "mcq",
    q: "The pressure on a fixed mass of gas is increased at constant temperature. Which statement explains the change in volume?",
    o: ["The particles shrink, so the volume falls",
        "The particles are pushed closer together, reducing the spaces between them",
        "The particles move more slowly, so they take up less room",
        "Some particles condense into a liquid"],
    a: 1,
    ex: "Particles themselves never change size. Increasing the pressure forces the particles closer together, so the empty space between them is reduced and the volume falls." },

  { id: "q1-07", t: 1, s: "1.1", lv: "S", ty: "mcq",
    q: "Why does the temperature stay constant while a pure solid is melting, even though heating continues?",
    o: ["The thermometer is not sensitive enough",
        "The energy supplied is used to overcome the forces between particles rather than to increase their kinetic energy",
        "The solid stops absorbing energy at its melting point",
        "The energy is lost to the surroundings"],
    a: 1,
    ex: "During a change of state the energy supplied separates the particles by overcoming the forces of attraction. The average kinetic energy, and therefore the temperature, does not change until melting is complete." },

  { id: "q1-08", t: 1, s: "1.1", lv: "C", ty: "multi",
    q: "Which of these processes release energy to the surroundings? Select all that apply.",
    o: ["Freezing", "Boiling", "Condensing", "Evaporating"],
    a: [0, 2],
    ex: "Going from a more energetic state to a less energetic one releases energy. Freezing (liquid to solid) and condensing (gas to liquid) are both exothermic." },

  { id: "q1-09", t: 1, s: "1.2", lv: "C", ty: "text",
    q: "What word describes the net movement of particles from a region of higher concentration to a region of lower concentration?",
    disp: "Diffusion", a: ["diffusion", "diffusing", "diffuse"],
    ex: "Diffusion. It happens because particles are in constant random motion, so they spread out and mix without being stirred." },

  { id: "q1-10", t: 1, s: "1.2", lv: "S", ty: "mcq",
    q: "Cotton wool soaked in concentrated ammonia is put at one end of a long glass tube and cotton wool soaked in concentrated hydrochloric acid at the other. Where does the white ring of ammonium chloride form?",
    o: ["Exactly in the middle",
        "Nearer the ammonia end",
        "Nearer the hydrochloric acid end",
        "At both ends at the same time"],
    a: 2,
    ex: "Ammonia has Mr = 17 and hydrogen chloride has Mr = 36.5. The lighter ammonia molecules move faster and travel further, so the two gases meet nearer the hydrochloric acid end." },

  { id: "q1-11", t: 1, s: "1.2", lv: "S", ty: "mcq",
    q: "Four gases are released at the same time. Which diffuses fastest?",
    o: ["Carbon dioxide, Mr = 44", "Oxygen, Mr = 32", "Methane, Mr = 16", "Sulfur dioxide, Mr = 64"],
    a: 2,
    ex: "The lower the relative molecular mass, the faster the average speed of the molecules at a given temperature, so the faster the gas diffuses. Methane is lightest here." },

  { id: "q1-12", t: 1, s: "1.2", lv: "C", ty: "mcq",
    q: "A drop of purple potassium manganate(VII) solution is placed in a beaker of still water. After some hours the whole beaker is pale purple. What does this show?",
    o: ["The water was hot",
        "Particles are in constant random motion and spread through the liquid",
        "The solution is denser than water",
        "A chemical reaction has taken place"],
    a: 1,
    ex: "This is diffusion in a liquid. No stirring is needed because the particles of both substances move randomly and gradually mix." },

  { id: "q1-13", t: 1, s: "1.2", lv: "C", ty: "mcq",
    q: "How does raising the temperature affect the rate of diffusion of a gas?",
    o: ["It increases the rate", "It decreases the rate", "It has no effect", "It stops diffusion"],
    a: 0,
    ex: "Higher temperature means greater average kinetic energy, so the particles move faster and spread out more quickly." },

  { id: "q1-14", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Which statement about a liquid is correct?",
    o: ["Particles are far apart and move randomly at high speed",
        "Particles are close together, randomly arranged and slide over each other",
        "Particles are close together in a regular pattern and only vibrate",
        "Particles are held in fixed positions but far apart"],
    a: 1,
    ex: "In a liquid the particles are touching but disordered, and they can move past one another. That is why a liquid flows but keeps a fixed volume." },

  { id: "q1-15", t: 1, s: "1.1", lv: "S", ty: "mcq",
    q: "Which statement about evaporation is correct?",
    o: ["It happens only at the boiling point",
        "It happens throughout the liquid",
        "Only the most energetic particles at the surface escape",
        "It causes the remaining liquid to warm up"],
    a: 2,
    ex: "Evaporation occurs at the surface at any temperature. The particles with the most energy escape, which lowers the average energy of those left behind, so the liquid cools." },

  { id: "q1-16", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "In which state do the particles of a substance have the greatest average kinetic energy?",
    o: ["Solid", "Liquid", "Gas", "The same in all three"],
    a: 2,
    ex: "For the same substance, particles in the gas state have the most energy, which is why they have broken free of the forces of attraction completely." },

  { id: "q1-17", t: 1, s: "1.1", lv: "C", ty: "text",
    q: "Name the change of state that occurs when a solid turns directly into a gas without becoming a liquid.",
    disp: "Sublimation", a: ["sublimation", "subliming", "sublime"],
    ex: "Sublimation. Solid carbon dioxide, known as dry ice, does this at normal atmospheric pressure." },

  { id: "q1-18", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Why can gases be compressed much more easily than liquids?",
    o: ["Gas particles are smaller than liquid particles",
        "Gas particles are lighter than liquid particles",
        "There are large spaces between gas particles",
        "Gas particles have no forces between them at all"],
    a: 2,
    ex: "Compression reduces the space between particles. Liquid particles are already touching, so there is almost nothing to squeeze out." },

  { id: "q1-19", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "A pure substance freezes at 18 degrees Celsius. At what temperature does it melt?",
    o: ["0 degrees Celsius", "18 degrees Celsius", "36 degrees Celsius", "It cannot be predicted"],
    a: 1,
    ex: "For a pure substance the melting point and freezing point are the same temperature. The change simply runs in opposite directions." },

  { id: "q1-20", t: 1, s: "1.2", lv: "S", ty: "mcq",
    q: "Why does a smell from an open bottle of perfume reach the far side of a room even though the air is still?",
    o: ["Air currents carry it in one direction",
        "The perfume molecules are pushed by gravity",
        "The perfume molecules move randomly and collide with air molecules, spreading through the room",
        "The perfume molecules dissolve in the air"],
    a: 2,
    ex: "This is diffusion. Random motion plus repeated collisions with air molecules causes the net spread from high to low concentration." },

  /* ---------------- Topic 2: Atoms, Elements and Compounds ---------------- */
  { id: "q2-01", t: 2, s: "2.1", lv: "C", ty: "mcq",
    q: "Which statement describes a compound?",
    o: ["Two or more substances mixed together but not chemically joined",
        "A substance made of only one type of atom",
        "Two or more different elements chemically combined in fixed proportions",
        "Any substance that can be separated by filtration"],
    a: 2,
    ex: "A compound has its elements chemically bonded in a fixed ratio, and it can only be separated by a chemical reaction. A mixture is not chemically joined." },

  { id: "q2-02", t: 2, s: "2.1", lv: "C", ty: "multi",
    q: "Which of these are mixtures? Select all that apply.",
    o: ["Air", "Water", "Sea water", "Carbon dioxide"],
    a: [0, 2],
    ex: "Air is a mixture of gases and sea water is a mixture of water with dissolved salts. Water and carbon dioxide are compounds with fixed formulae." },

  { id: "q2-03", t: 2, s: "2.2", lv: "C", ty: "mcq",
    q: "What are the relative charges of a proton, a neutron and an electron?",
    o: ["+1, 0, -1", "-1, 0, +1", "+1, +1, -1", "0, +1, -1"],
    a: 0,
    ex: "Protons carry +1, neutrons are neutral with 0, and electrons carry -1. An atom is neutral because the numbers of protons and electrons are equal." },

  { id: "q2-04", t: 2, s: "2.2", lv: "C", ty: "mcq",
    q: "What is the approximate relative mass of an electron?",
    o: ["1", "0.5", "1/1840", "2"],
    a: 2,
    ex: "An electron has a mass of about 1/1840 of a proton, which is why nearly all the mass of an atom is in the nucleus." },

  { id: "q2-05", t: 2, s: "2.2", lv: "C", ty: "num",
    q: "An atom has a mass number of 27 and a proton number of 13. How many neutrons does it contain?",
    a: 14, tol: 0,
    ex: "Neutrons = mass number - proton number = 27 - 13 = 14. This atom is aluminium." },

  { id: "q2-06", t: 2, s: "2.2", lv: "C", ty: "text",
    q: "Write the electronic configuration of a chlorine atom, proton number 17. Use commas, for example 2,8,1",
    disp: "2,8,7", a: ["2,8,7", "2.8.7", "2 8 7"],
    ex: "2,8,7. The first shell holds up to 2, the second up to 8, leaving 7 in the third shell. Seven outer electrons places chlorine in Group VII." },

  { id: "q2-07", t: 2, s: "2.2", lv: "C", ty: "mcq",
    q: "An element has the electronic configuration 2,8,2. Where is it in the Periodic Table?",
    o: ["Group II, Period 3", "Group II, Period 2", "Group VIII, Period 2", "Group III, Period 2"],
    a: 0,
    ex: "The number of outer-shell electrons gives the group, so Group II. The number of occupied shells gives the period, so Period 3. This is magnesium." },

  { id: "q2-08", t: 2, s: "2.2", lv: "C", ty: "mcq",
    q: "Which quantity always identifies which element an atom is?",
    o: ["Mass number", "Number of neutrons", "Proton number", "Number of outer-shell electrons"],
    a: 2,
    ex: "The proton number is unique to each element. Change it and you have a different element, whereas changing the neutron number only gives another isotope." },

  { id: "q2-09", t: 2, s: "2.3", lv: "C", ty: "mcq",
    q: "Why do two isotopes of the same element have identical chemical properties?",
    o: ["They have the same mass number",
        "They have the same number of neutrons",
        "They have the same number of outer-shell electrons",
        "They have the same density"],
    a: 2,
    ex: "Chemical behaviour is controlled by the electrons, especially the outer shell. Isotopes differ only in neutron number, so their electron arrangements are identical." },

  { id: "q2-10", t: 2, s: "2.3", lv: "S", ty: "num",
    q: "Chlorine exists as 75 per cent chlorine-35 and 25 per cent chlorine-37. Calculate its relative atomic mass.",
    a: 35.5, tol: 0.05,
    ex: "Ar = (75 x 35 + 25 x 37) / 100 = (2625 + 925) / 100 = 35.5" },

  { id: "q2-11", t: 2, s: "2.3", lv: "S", ty: "num",
    q: "Boron has two isotopes: boron-10 with 20 per cent abundance and boron-11 with 80 per cent abundance. Calculate the relative atomic mass to one decimal place.",
    a: 10.8, tol: 0.05,
    ex: "Ar = (20 x 10 + 80 x 11) / 100 = (200 + 880) / 100 = 10.8" },

  { id: "q2-12", t: 2, s: "2.4", lv: "C", ty: "mcq",
    q: "How does a sodium atom become a sodium ion?",
    o: ["It gains one electron to form Na-", "It loses one electron to form Na+",
        "It loses one proton to form Na+", "It gains one proton to form Na+"],
    a: 1,
    ex: "Sodium has the configuration 2,8,1. Losing the single outer electron gives 2,8, the configuration of neon, and leaves a 1+ charge. Protons never move in chemical reactions." },

  { id: "q2-13", t: 2, s: "2.4", lv: "C", ty: "mcq",
    q: "What charge does an ion of a Group VI element usually carry?",
    o: ["6+", "2+", "2-", "6-"],
    a: 2,
    ex: "Group VI atoms have 6 outer electrons and gain 2 to reach a full outer shell of 8, giving a 2- charge. Oxide and sulfide ions are examples." },

  { id: "q2-14", t: 2, s: "2.4", lv: "C", ty: "mcq",
    q: "What is an ionic bond?",
    o: ["A shared pair of electrons between two atoms",
        "The strong electrostatic attraction between oppositely charged ions",
        "The attraction between positive ions and delocalised electrons",
        "A weak force between molecules"],
    a: 1,
    ex: "Ionic bonding is electrostatic attraction between a cation and an anion. Sharing electrons is covalent bonding, and a sea of delocalised electrons is metallic bonding." },

  { id: "q2-15", t: 2, s: "2.4", lv: "S", ty: "text",
    q: "Magnesium ions are Mg2+ and chloride ions are Cl-. What is the formula of magnesium chloride?",
    disp: "MgCl2", a: ["mgcl2", "mg cl2", "mgcl_2"],
    ex: "MgCl2. Two 1- chloride ions are needed to balance one 2+ magnesium ion so that the compound is neutral overall." },

  { id: "q2-16", t: 2, s: "2.4", lv: "S", ty: "mcq",
    q: "Why does solid sodium chloride not conduct electricity, while molten sodium chloride does?",
    o: ["Solid sodium chloride has no ions",
        "In the solid the ions are held in fixed positions in the lattice and cannot move",
        "Melting changes the ions into electrons",
        "The solid has no charged particles at all"],
    a: 1,
    ex: "Conduction needs charge carriers that are free to move. The ions exist in the solid but are locked in the giant lattice. Melting frees them." },

  { id: "q2-17", t: 2, s: "2.4", lv: "S", ty: "mcq",
    q: "Why do ionic compounds have high melting points?",
    o: ["The covalent bonds between ions are very strong",
        "There are many strong electrostatic attractions throughout the giant lattice that need a lot of energy to overcome",
        "The ions are very heavy",
        "The intermolecular forces between the molecules are strong"],
    a: 1,
    ex: "An ionic compound is a giant lattice, not molecules. Every ion attracts its oppositely charged neighbours, so a large amount of energy is needed to break the structure apart." },

  { id: "q2-18", t: 2, s: "2.5", lv: "C", ty: "mcq",
    q: "What is a covalent bond?",
    o: ["The transfer of electrons from one atom to another",
        "A shared pair of electrons between two atoms",
        "The attraction between a positive and a negative ion",
        "A force between two molecules"],
    a: 1,
    ex: "In a covalent bond a pair of electrons is shared, and both nuclei are attracted to that shared pair. This lets both atoms reach a noble gas configuration." },

  { id: "q2-19", t: 2, s: "2.5", lv: "S", ty: "num",
    q: "How many shared pairs of electrons are there between the two nitrogen atoms in a nitrogen molecule, N2?",
    a: 3, tol: 0,
    ex: "Each nitrogen atom has 5 outer electrons and needs 3 more, so they share three pairs to form a triple bond." },

  { id: "q2-20", t: 2, s: "2.5", lv: "C", ty: "num",
    q: "In a dot-and-cross diagram of methane, CH4, how many electrons are shown in the outer shell of the carbon atom in total?",
    a: 8, tol: 0,
    ex: "Carbon contributes 4 electrons and shares one from each of the 4 hydrogen atoms, giving 8 electrons around carbon, a full outer shell." },

  { id: "q2-21", t: 2, s: "2.5", lv: "S", ty: "mcq",
    q: "Why does carbon dioxide have a low boiling point?",
    o: ["The covalent bonds inside each molecule are weak",
        "The forces between the molecules are weak and need little energy to overcome",
        "It is a giant covalent structure",
        "The molecules are very light"],
    a: 1,
    ex: "This is the classic trap. The covalent bonds within a molecule are strong, but boiling only separates the molecules from each other, and the intermolecular forces are weak." },

  { id: "q2-22", t: 2, s: "2.5", lv: "C", ty: "mcq",
    q: "Why do most simple molecular substances not conduct electricity?",
    o: ["Their molecules are too large",
        "They have no free ions or free electrons",
        "Their bonds are too strong",
        "They are always solid"],
    a: 1,
    ex: "The molecules are neutral overall and the electrons are held in bonds, so there are no mobile charge carriers." },

  { id: "q2-23", t: 2, s: "2.6", lv: "C", ty: "mcq",
    q: "How many other carbon atoms is each carbon atom bonded to in diamond?",
    o: ["2", "3", "4", "6"],
    a: 2,
    ex: "Each carbon forms 4 strong covalent bonds in a rigid tetrahedral arrangement, which makes diamond extremely hard and gives it a very high melting point." },

  { id: "q2-24", t: 2, s: "2.6", lv: "C", ty: "mcq",
    q: "Why is graphite used as a lubricant?",
    o: ["It has delocalised electrons",
        "Its layers are held together by weak forces and can slide over each other",
        "Each carbon atom forms four covalent bonds",
        "It has a low melting point"],
    a: 1,
    ex: "Each carbon in graphite bonds to only three others, forming layers. The weak forces between the layers let them slide, so graphite feels slippery." },

  { id: "q2-25", t: 2, s: "2.6", lv: "C", ty: "mcq",
    q: "Why does graphite conduct electricity when diamond does not?",
    o: ["Graphite contains free ions",
        "Graphite has one delocalised electron per carbon atom that can move through the structure",
        "Graphite has a smaller molecular mass",
        "Graphite has weaker covalent bonds"],
    a: 1,
    ex: "Only three of carbon's four outer electrons are used in bonding in graphite. The fourth is delocalised and free to move, so graphite is used for electrodes." },

  { id: "q2-26", t: 2, s: "2.6", lv: "S", ty: "mcq",
    q: "Which statement about silicon(IV) oxide is correct?",
    o: ["It has a simple molecular structure with weak forces between molecules",
        "It has a giant covalent structure similar to diamond, so it is hard with a high melting point",
        "It conducts electricity because of delocalised electrons",
        "It is soft and slippery like graphite"],
    a: 1,
    ex: "Silicon(IV) oxide, found in sand and quartz, is a giant covalent lattice. Like diamond it is hard, has a very high melting point and does not conduct." },

  { id: "q2-27", t: 2, s: "2.7", lv: "S", ty: "mcq",
    q: "What is metallic bonding?",
    o: ["The attraction between a lattice of positive ions and a sea of delocalised electrons",
        "The attraction between oppositely charged ions",
        "Shared pairs of electrons between metal atoms",
        "Weak forces between metal molecules"],
    a: 0,
    ex: "Metal atoms release their outer electrons, which become delocalised and move throughout the structure. The attraction between these electrons and the positive ions holds the metal together." },

  { id: "q2-28", t: 2, s: "2.7", lv: "S", ty: "mcq",
    q: "Why are metals malleable?",
    o: ["Their delocalised electrons repel each other",
        "Layers of positive ions can slide over each other while the bonding remains",
        "The covalent bonds bend without breaking",
        "The ions are held only by weak forces"],
    a: 1,
    ex: "The ions are arranged in layers. When a force is applied the layers slip, but the sea of electrons still holds the structure together so the metal changes shape without shattering." },

  { id: "q2-29", t: 2, s: "2.2", lv: "S", ty: "mcq",
    q: "Why is a noble gas electronic configuration important in bonding?",
    o: ["It is the arrangement with the fewest electrons",
        "It is a full outer shell, which is a very stable arrangement that atoms achieve by losing, gaining or sharing electrons",
        "It allows atoms to become radioactive",
        "It makes atoms conduct electricity"],
    a: 1,
    ex: "Atoms bond in ways that give them the stable full outer shell of the nearest noble gas, which is why the group number predicts the charge or number of bonds." },

  { id: "q2-30", t: 2, s: "2.2", lv: "C", ty: "text",
    q: "Write the electronic configuration of a potassium atom, proton number 19.",
    disp: "2,8,8,1", a: ["2,8,8,1", "2.8.8.1", "2 8 8 1"],
    ex: "2,8,8,1. The fourth shell starts before the third fills beyond 8 for elements up to calcium. One outer electron places potassium in Group I, Period 4." },

  /* ---------------- Topic 3: Stoichiometry ---------------- */
  { id: "q3-01", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "Calculate the relative molecular mass of sulfuric acid, H2SO4. Use Ar: H = 1, S = 32, O = 16",
    a: 98, tol: 0,
    ex: "Mr = (2 x 1) + 32 + (4 x 16) = 2 + 32 + 64 = 98" },

  { id: "q3-02", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "Calculate the relative formula mass of calcium hydroxide, Ca(OH)2. Use Ar: Ca = 40, O = 16, H = 1",
    a: 74, tol: 0,
    ex: "Mr = 40 + 2 x (16 + 1) = 40 + 34 = 74. The bracket applies to both the O and the H." },

  { id: "q3-03", t: 3, s: "3.1", lv: "C", ty: "num",
    q: "Balance the equation and give the coefficient in front of O2: __ CH4 + __ O2 gives __ CO2 + __ H2O",
    a: 2, tol: 0,
    ex: "CH4 + 2O2 gives CO2 + 2H2O. One carbon, four hydrogens needing 2 water molecules, so 4 oxygen atoms in total, which is 2 O2." },

  { id: "q3-04", t: 3, s: "3.1", lv: "C", ty: "num",
    q: "Balance this equation and give the coefficient in front of HCl: __ Mg + __ HCl gives __ MgCl2 + __ H2",
    a: 2, tol: 0,
    ex: "Mg + 2HCl gives MgCl2 + H2. Two chlorine atoms are needed for MgCl2, which brings 2 hydrogen atoms, forming one H2." },

  { id: "q3-05", t: 3, s: "3.1", lv: "C", ty: "mcq",
    q: "Which state symbol shows that a substance is dissolved in water?",
    o: ["(s)", "(l)", "(g)", "(aq)"],
    a: 3,
    ex: "(aq) means aqueous, that is dissolved in water. Note that (l) means a pure liquid, so water itself is written H2O(l)." },

  { id: "q3-06", t: 3, s: "3.1", lv: "S", ty: "text",
    q: "Aluminium ions are Al3+ and oxide ions are O2-. What is the formula of aluminium oxide?",
    disp: "Al2O3", a: ["al2o3", "al_2o_3", "al2 o3"],
    ex: "Al2O3. Two 3+ ions give 6+ and three 2- ions give 6-, so the charges cancel." },

  { id: "q3-07", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "How many moles are there in 8.0 g of sodium hydroxide, NaOH? Use Ar: Na = 23, O = 16, H = 1",
    a: 0.2, tol: 0.005,
    ex: "Mr of NaOH = 40. n = m / M = 8.0 / 40 = 0.20 mol" },

  { id: "q3-08", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What is the mass, in g, of 0.25 mol of calcium carbonate, CaCO3? Use Ar: Ca = 40, C = 12, O = 16",
    a: 25, tol: 0.1,
    ex: "Mr of CaCO3 = 40 + 12 + 48 = 100. m = n x M = 0.25 x 100 = 25 g" },

  { id: "q3-09", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What volume, in dm3, does 0.5 mol of oxygen gas occupy at room temperature and pressure?",
    a: 12, tol: 0.1,
    ex: "One mole of any gas occupies 24 dm3 at rtp, so 0.5 x 24 = 12 dm3" },

  { id: "q3-10", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "How many moles of gas are there in 72 dm3 measured at room temperature and pressure?",
    a: 3, tol: 0.05,
    ex: "n = volume / 24 = 72 / 24 = 3.0 mol" },

  { id: "q3-11", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What is the concentration, in mol/dm3, of a solution containing 0.10 mol of solute in 250 cm3 of solution?",
    a: 0.4, tol: 0.01,
    ex: "250 cm3 = 0.250 dm3. c = n / V = 0.10 / 0.250 = 0.40 mol/dm3. Always convert cm3 to dm3 by dividing by 1000." },

  { id: "q3-12", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "A solution of sodium hydroxide has a concentration of 40 g/dm3. What is its concentration in mol/dm3? Mr of NaOH = 40",
    a: 1, tol: 0.01,
    ex: "Divide the concentration in g/dm3 by the molar mass: 40 / 40 = 1.0 mol/dm3" },

  { id: "q3-13", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "How many moles of solute are in 50 cm3 of 0.20 mol/dm3 hydrochloric acid?",
    a: 0.01, tol: 0.0005,
    ex: "n = c x V = 0.20 x (50 / 1000) = 0.20 x 0.050 = 0.010 mol" },

  { id: "q3-14", t: 3, s: "3.3", lv: "S", ty: "text",
    q: "A compound contains 40.0 per cent carbon, 6.7 per cent hydrogen and 53.3 per cent oxygen by mass. What is its empirical formula? Use Ar: C = 12, H = 1, O = 16",
    disp: "CH2O", a: ["ch2o", "c1h2o1"],
    ex: "Moles: C 40/12 = 3.33, H 6.7/1 = 6.7, O 53.3/16 = 3.33. Divide by the smallest, 3.33, giving 1 : 2 : 1, so CH2O." },

  { id: "q3-15", t: 3, s: "3.3", lv: "S", ty: "text",
    q: "A compound has the empirical formula CH2 and a relative molecular mass of 56. What is its molecular formula?",
    disp: "C4H8", a: ["c4h8", "c_4h_8"],
    ex: "The empirical formula mass of CH2 is 14. 56 / 14 = 4, so multiply everything by 4 to get C4H8." },

  { id: "q3-16", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "Calculate the percentage by mass of nitrogen in ammonium nitrate, NH4NO3, to the nearest whole number. Use Ar: N = 14, H = 1, O = 16",
    a: 35, tol: 0.6,
    ex: "Mr = 14 + 4 + 14 + 48 = 80. Mass of N = 2 x 14 = 28. Percentage = 28 / 80 x 100 = 35 per cent" },

  { id: "q3-17", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "In a reaction the theoretical yield is 25.0 g but only 20.0 g is obtained. Calculate the percentage yield.",
    a: 80, tol: 0.5,
    ex: "Percentage yield = actual / theoretical x 100 = 20.0 / 25.0 x 100 = 80 per cent" },

  { id: "q3-18", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "A 5.0 g sample of impure sodium chloride yields 4.6 g of pure sodium chloride. Calculate the percentage purity.",
    a: 92, tol: 0.5,
    ex: "Percentage purity = mass of pure substance / total mass x 100 = 4.6 / 5.0 x 100 = 92 per cent" },

  { id: "q3-19", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "24 g of magnesium reacts completely with oxygen to form 40 g of magnesium oxide. What mass of magnesium oxide, in g, is formed from 12 g of magnesium?",
    a: 20, tol: 0.1,
    ex: "Halving the mass of magnesium halves the mass of product, so 40 / 2 = 20 g. Reacting masses stay in fixed proportion." },

  { id: "q3-20", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "Calcium carbonate decomposes: CaCO3 gives CaO + CO2. What mass of calcium oxide, in g, is produced from 50 g of calcium carbonate? Mr: CaCO3 = 100, CaO = 56",
    a: 28, tol: 0.5,
    ex: "n(CaCO3) = 50 / 100 = 0.50 mol. The ratio is 1 : 1 so n(CaO) = 0.50 mol. m = 0.50 x 56 = 28 g" },

  { id: "q3-21", t: 3, s: "3.3", lv: "S", ty: "mcq",
    q: "2.0 mol of hydrogen reacts with 2.0 mol of oxygen: 2H2 + O2 gives 2H2O. Which reactant is limiting?",
    o: ["Hydrogen", "Oxygen", "Neither, both are used up exactly", "It cannot be determined"],
    a: 0,
    ex: "2.0 mol of H2 needs only 1.0 mol of O2. Hydrogen runs out first, so it is limiting and 1.0 mol of oxygen is left over." },

  { id: "q3-22", t: 3, s: "3.3", lv: "S", ty: "mcq",
    q: "What is the value of the Avogadro constant?",
    o: ["6.02 x 10^23 per mole", "6.02 x 10^-23 per mole", "3.01 x 10^23 per mole", "1.00 x 10^24 per mole"],
    a: 0,
    ex: "One mole of any substance contains 6.02 x 10^23 particles. This is the number of atoms in exactly 12 g of carbon-12." },

  { id: "q3-23", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "What volume of oxygen, in dm3 at rtp, is needed to burn 12 dm3 of methane completely? CH4 + 2O2 gives CO2 + 2H2O",
    a: 24, tol: 0.5,
    ex: "For gases the volume ratio equals the mole ratio. Two volumes of oxygen per volume of methane, so 2 x 12 = 24 dm3" },

  { id: "q3-24", t: 3, s: "3.2", lv: "C", ty: "mcq",
    q: "What is relative atomic mass measured against?",
    o: ["The mass of a hydrogen atom",
        "One twelfth of the mass of a carbon-12 atom",
        "The mass of a proton",
        "The mass of an oxygen-16 atom"],
    a: 1,
    ex: "Ar is the average mass of the isotopes of an element compared with 1/12th of the mass of an atom of carbon-12." },

  { id: "q3-25", t: 3, s: "3.1", lv: "S", ty: "mcq",
    q: "Which is the correct ionic equation for the precipitation of silver chloride?",
    o: ["Ag+(aq) + Cl-(aq) gives AgCl(s)",
        "AgNO3(aq) + NaCl(aq) gives AgCl(s) + NaNO3(aq)",
        "Ag+(aq) + Cl2(g) gives AgCl2(s)",
        "Na+(aq) + NO3-(aq) gives NaNO3(s)"],
    a: 0,
    ex: "An ionic equation shows only the species that change. Sodium and nitrate ions stay in solution as spectator ions, so they are left out." },

  { id: "q3-26", t: 3, s: "3.1", lv: "C", ty: "text",
    q: "Write the formula of the compound formed between calcium and chlorine.",
    disp: "CaCl2", a: ["cacl2", "ca cl2", "cacl_2"],
    ex: "CaCl2. Calcium is in Group II so it forms Ca2+, and chlorine is in Group VII so it forms Cl-. Two chlorides balance one calcium ion." },

  { id: "q3-27", t: 3, s: "3.3", lv: "S", ty: "num",
    q: "How many moles of atoms are there in 4.8 g of carbon? Ar of C = 12",
    a: 0.4, tol: 0.005,
    ex: "n = m / M = 4.8 / 12 = 0.40 mol" },

  { id: "q3-28", t: 3, s: "3.1", lv: "C", ty: "num",
    q: "Balance the equation and give the coefficient in front of Fe2O3: __ Fe2O3 + __ CO gives __ Fe + __ CO2",
    a: 1, tol: 0,
    ex: "Fe2O3 + 3CO gives 2Fe + 3CO2. Only one Fe2O3 is needed, balanced by 3 CO and 3 CO2." },

  /* ---------------- Topic 4: Electrochemistry ---------------- */
  { id: "q4-01", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "What is electrolysis?",
    o: ["The reaction of a metal with an acid",
        "The decomposition of an ionic compound, when molten or in aqueous solution, by the passage of electricity",
        "The production of electricity from a chemical reaction",
        "The heating of a compound until it breaks down"],
    a: 1,
    ex: "Electrolysis uses electrical energy to break down a compound. Producing electricity from a reaction is the opposite, which is what a cell or fuel cell does." },

  { id: "q4-02", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Why must an ionic compound be molten or dissolved before it can be electrolysed?",
    o: ["So the ions are free to move and carry charge",
        "So the compound becomes a metal",
        "So the electrons can be released from the nucleus",
        "So the compound reacts with the electrodes"],
    a: 0,
    ex: "In the solid the ions are fixed in the lattice. Melting or dissolving frees them so they can move to the electrodes." },

  { id: "q4-03", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Which statement about the cathode is correct?",
    o: ["It is positive and attracts anions", "It is negative and attracts cations",
        "It is negative and attracts anions", "It is positive and attracts cations"],
    a: 1,
    ex: "The cathode is the negative electrode, so it attracts positive ions, the cations. Reduction happens there because the ions gain electrons." },

  { id: "q4-04", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Molten lead(II) bromide is electrolysed with inert electrodes. What forms at each electrode?",
    o: ["Lead at the cathode, bromine at the anode",
        "Bromine at the cathode, lead at the anode",
        "Hydrogen at the cathode, oxygen at the anode",
        "Lead at both electrodes"],
    a: 0,
    ex: "Pb2+ ions move to the cathode and gain electrons to form molten lead. Br- ions move to the anode, lose electrons and form red-brown bromine vapour." },

  { id: "q4-05", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Which is the correct half-equation for the reaction at the anode during the electrolysis of molten lead(II) bromide?",
    o: ["Pb2+ + 2e- gives Pb", "2Br- gives Br2 + 2e-",
        "Br2 + 2e- gives 2Br-", "2H+ + 2e- gives H2"],
    a: 1,
    ex: "At the anode negative ions lose electrons, which is oxidation. Two bromide ions each give up one electron to form a bromine molecule." },

  { id: "q4-06", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Which process happens at the cathode in any electrolysis?",
    o: ["Oxidation, because electrons are lost", "Reduction, because electrons are gained",
        "Neutralisation", "Thermal decomposition"],
    a: 1,
    ex: "Positive ions arrive at the negative cathode and gain electrons. Gain of electrons is reduction. Remember that reduction is at the cathode." },

  { id: "q4-07", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Concentrated aqueous sodium chloride is electrolysed with inert electrodes. What is produced at the anode?",
    o: ["Sodium", "Hydrogen", "Chlorine", "Oxygen"],
    a: 2,
    ex: "When a halide solution is concentrated, the halogen is produced in preference to oxygen, so chlorine is released at the anode." },

  { id: "q4-08", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "In the electrolysis of concentrated aqueous sodium chloride, why is hydrogen produced at the cathode rather than sodium?",
    o: ["There is more hydrogen than sodium in the solution",
        "Sodium is more reactive than hydrogen, so hydrogen is discharged instead",
        "Sodium ions are too large to move",
        "Sodium is a gas at this temperature"],
    a: 1,
    ex: "When the metal is more reactive than hydrogen, the hydrogen ions from water are discharged instead. Only metals below hydrogen in the reactivity series are deposited from solution." },

  { id: "q4-09", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Dilute aqueous sodium chloride is electrolysed with inert electrodes. What is produced at the anode?",
    o: ["Chlorine", "Oxygen", "Hydrogen", "Sodium"],
    a: 1,
    ex: "In a dilute halide solution the concentration of halide ions is low, so hydroxide ions from water are discharged instead and oxygen is produced." },

  { id: "q4-10", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Dilute sulfuric acid is electrolysed with inert electrodes. What is the ratio of the volume of gas at the cathode to that at the anode?",
    o: ["1 to 1", "1 to 2", "2 to 1", "4 to 1"],
    a: 2,
    ex: "Hydrogen forms at the cathode and oxygen at the anode. Water is effectively split as 2H2O gives 2H2 + O2, so twice the volume of hydrogen is produced." },

  { id: "q4-11", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Aqueous copper(II) sulfate is electrolysed using inert carbon electrodes. What is seen at each electrode?",
    o: ["A pink-brown coating of copper at the cathode and bubbles of oxygen at the anode",
        "Bubbles of hydrogen at the cathode and chlorine at the anode",
        "Copper at both electrodes",
        "No change at either electrode"],
    a: 0,
    ex: "Copper is below hydrogen in the reactivity series so copper is deposited. The anion is sulfate, so hydroxide ions from water are discharged and oxygen is released." },

  { id: "q4-12", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Aqueous copper(II) sulfate is electrolysed using copper electrodes. What happens?",
    o: ["Both electrodes gain mass",
        "The anode loses mass and the cathode gains mass",
        "The anode gains mass and the cathode loses mass",
        "Oxygen is produced at the anode"],
    a: 1,
    ex: "The copper anode dissolves as Cu gives Cu2+ + 2e-, and copper is deposited on the cathode. This is how impure copper is purified." },

  { id: "q4-13", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "An iron spoon is to be electroplated with silver. How should it be connected?",
    o: ["The spoon is the anode and silver is the cathode",
        "The spoon is the cathode and silver is the anode",
        "Both the spoon and the silver are cathodes",
        "The spoon is not connected to the circuit"],
    a: 1,
    ex: "The object to be plated is always the cathode, so the metal ions are attracted to it and deposited on its surface. The electrolyte must contain ions of the plating metal." },

  { id: "q4-14", t: 4, s: "4.1", lv: "C", ty: "multi",
    q: "Why are objects electroplated? Select all that apply.",
    o: ["To improve the appearance", "To prevent corrosion",
        "To make the object lighter", "To make the object melt at a lower temperature"],
    a: [0, 1],
    ex: "Electroplating gives a decorative finish and puts a protective barrier of a less reactive metal on the surface." },

  { id: "q4-15", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "How is charge carried through the electrolyte and through the wires in an electrolysis circuit?",
    o: ["By electrons in both",
        "By ions in both",
        "By ions in the electrolyte and by electrons in the wires",
        "By electrons in the electrolyte and by ions in the wires"],
    a: 2,
    ex: "Electrons cannot travel through the solution. Ions move to the electrodes to carry charge there, while electrons flow through the external circuit." },

  { id: "q4-16", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Molten aluminium oxide is electrolysed. Which products are formed?",
    o: ["Aluminium at the cathode, oxygen at the anode",
        "Oxygen at the cathode, aluminium at the anode",
        "Hydrogen at the cathode, oxygen at the anode",
        "Aluminium at both electrodes"],
    a: 0,
    ex: "For a molten binary compound, the metal is always formed at the cathode and the non-metal at the anode." },

  { id: "q4-17", t: 4, s: "4.1", lv: "S", ty: "text",
    q: "Write the half-equation for the formation of copper at the cathode from Cu2+ ions. Use e- for an electron.",
    disp: "Cu2+ + 2e- gives Cu", a: ["cu2+ + 2e- -> cu", "cu2+ +2e- -> cu", "cu2++2e--> cu", "cu2+ + 2e- = cu",
        "cu2+ + 2e- gives cu", "cu(2+) + 2e- -> cu"],
    ex: "Cu2+ + 2e- gives Cu. The copper ion gains two electrons, which is reduction." },

  { id: "q4-18", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Which material is suitable for inert electrodes?",
    o: ["Copper", "Iron", "Graphite", "Zinc"],
    a: 2,
    ex: "Graphite and platinum are used because they conduct electricity but do not take part in the reaction." },

  { id: "q4-19", t: 4, s: "4.2", lv: "C", ty: "mcq",
    q: "What is the only chemical product of a hydrogen-oxygen fuel cell?",
    o: ["Carbon dioxide", "Water", "Hydrogen peroxide", "Nitrogen oxides"],
    a: 1,
    ex: "Hydrogen and oxygen combine to form water while producing an electrical output. There are no carbon-based emissions at the cell itself." },

  { id: "q4-20", t: 4, s: "4.2", lv: "S", ty: "multi",
    q: "Which are disadvantages of hydrogen-oxygen fuel cells compared with petrol engines? Select all that apply.",
    o: ["Hydrogen is difficult and expensive to store and transport",
        "They produce carbon dioxide",
        "Hydrogen is highly flammable, which raises safety concerns",
        "They are less efficient than petrol engines"],
    a: [0, 2],
    ex: "Fuel cells are more efficient and produce no carbon dioxide. The real problems are storing and transporting hydrogen safely, and the cost of producing it." },

  { id: "q4-21", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "During the purification of copper by electrolysis, what happens to the impurities from the impure anode?",
    o: ["They are deposited on the cathode with the copper",
        "They fall to the bottom of the cell as a sludge",
        "They dissolve and remain in the electrolyte forever",
        "They react with the electrolyte to form a gas"],
    a: 1,
    ex: "Impurities that are less reactive than copper do not dissolve, so they collect below the anode as anode sludge, which often contains valuable metals." },

  { id: "q4-22", t: 4, s: "4.1", lv: "C", ty: "text",
    q: "What is the name given to the liquid or solution that is broken down during electrolysis?",
    disp: "Electrolyte", a: ["electrolyte", "the electrolyte"],
    ex: "The electrolyte. It must contain ions that are free to move." },

  { id: "q4-23", t: 4, s: "4.1", lv: "S", ty: "mcq",
    q: "Which half-equation shows the formation of oxygen at the anode in aqueous solution?",
    o: ["4OH- gives O2 + 2H2O + 4e-", "O2 + 4e- gives 2O2-",
        "2H+ + 2e- gives H2", "O2- gives O2 + 2e-"],
    a: 0,
    ex: "Hydroxide ions from water are oxidised at the anode. Four are needed to release one oxygen molecule, along with water and four electrons." },

  { id: "q4-24", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "A gas produced at an anode bleaches damp litmus paper. Which gas is it?",
    o: ["Hydrogen", "Oxygen", "Chlorine", "Carbon dioxide"],
    a: 2,
    ex: "Chlorine turns damp litmus paper red then bleaches it white. Oxygen relights a glowing splint and hydrogen gives a squeaky pop." }
];
