/* Question bank, part 2: Topics 5 to 8. */

window.QUESTIONS_2 = [

  /* ---------------- Topic 5: Chemical Energetics ---------------- */
  { id: "q5-01", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "What happens to the temperature of the surroundings during an exothermic reaction?",
    o: ["It rises", "It falls", "It stays the same", "It falls then rises"],
    a: 0,
    ex: "An exothermic reaction transfers thermal energy out to the surroundings, so a thermometer in the mixture shows a temperature rise." },

  { id: "q5-02", t: 5, s: "5.1", lv: "C", ty: "multi",
    q: "Which of these are exothermic processes? Select all that apply.",
    o: ["Combustion of methane", "Thermal decomposition of calcium carbonate",
        "Neutralisation of an acid by an alkali", "Photosynthesis"],
    a: [0, 2],
    ex: "Combustion and neutralisation both release energy. Thermal decomposition and photosynthesis both need a continuous supply of energy, so they are endothermic." },

  { id: "q5-03", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "What is the sign of delta H for an endothermic reaction?",
    o: ["Negative, because energy is released", "Positive, because energy is taken in",
        "Negative, because energy is taken in", "Zero"],
    a: 1,
    ex: "Endothermic means energy is absorbed from the surroundings, so the products store more energy than the reactants and delta H is positive." },

  { id: "q5-04", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "On a reaction pathway diagram for an exothermic reaction, how do the energy levels compare?",
    o: ["The products are higher than the reactants",
        "The products are lower than the reactants",
        "They are at the same level",
        "The products are always at zero"],
    a: 1,
    ex: "Energy has been given out to the surroundings, so the products are left with less energy than the reactants and the line ends lower." },

  { id: "q5-05", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "What does the activation energy, Ea, represent on a reaction pathway diagram?",
    o: ["The overall energy change of the reaction",
        "The minimum energy colliding particles need for a reaction to occur",
        "The energy of the products",
        "The energy released when bonds form"],
    a: 1,
    ex: "Ea is the height of the barrier from the reactants up to the peak. Collisions with less energy than this do not lead to a reaction." },

  { id: "q5-06", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "Which statement about bonds and energy is correct?",
    o: ["Breaking bonds releases energy and making bonds absorbs energy",
        "Breaking bonds absorbs energy and making bonds releases energy",
        "Both breaking and making bonds release energy",
        "Both breaking and making bonds absorb energy"],
    a: 1,
    ex: "Energy must be supplied to pull bonded atoms apart, so bond breaking is endothermic. Forming bonds releases energy, so it is exothermic." },

  { id: "q5-07", t: 5, s: "5.1", lv: "S", ty: "num",
    q: "For H2 + Cl2 gives 2HCl, bond energies in kJ/mol are H-H 436, Cl-Cl 242, H-Cl 431. Calculate delta H in kJ/mol.",
    a: -184, tol: 1,
    ex: "Bonds broken = 436 + 242 = 678. Bonds made = 2 x 431 = 862. delta H = 678 - 862 = -184 kJ/mol, so the reaction is exothermic." },

  { id: "q5-08", t: 5, s: "5.1", lv: "S", ty: "num",
    q: "A reaction breaks bonds worth 1200 kJ/mol and forms bonds worth 1150 kJ/mol. What is delta H in kJ/mol?",
    a: 50, tol: 1,
    ex: "delta H = energy in - energy out = 1200 - 1150 = +50 kJ/mol. The positive sign shows the reaction is endothermic." },

  { id: "q5-09", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "A student dissolves a solid in water and the temperature of the solution falls from 21 to 15 degrees Celsius. What does this show?",
    o: ["The process is exothermic", "The process is endothermic",
        "No energy change occurred", "The thermometer is faulty"],
    a: 1,
    ex: "Energy has been taken in from the surroundings, which includes the water, so the surroundings cool down." },

  { id: "q5-10", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "A reaction is exothermic overall. What does this tell you about the bonds?",
    o: ["More energy was needed to break bonds than was released when bonds formed",
        "More energy was released forming bonds than was needed to break bonds",
        "No bonds were broken",
        "The bonds in the products are weaker than those in the reactants"],
    a: 1,
    ex: "The overall energy change is the balance between the two. If forming the new bonds releases more than breaking the old ones cost, the surplus is given out." },

  { id: "q5-11", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Which everyday application relies on an endothermic process?",
    o: ["A hand warmer", "An instant cold pack for injuries",
        "A gas cooker", "A candle"],
    a: 1,
    ex: "Cold packs contain a salt that absorbs energy as it dissolves, cooling the surroundings. The others all release energy." },

  { id: "q5-12", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "How does adding a catalyst change a reaction pathway diagram?",
    o: ["It lowers the energy of the products",
        "It lowers the activation energy but leaves delta H unchanged",
        "It raises the activation energy",
        "It changes delta H to zero"],
    a: 1,
    ex: "A catalyst gives an alternative route with a lower barrier. The reactants and products are unchanged, so the overall energy change stays the same." },

  /* ---------------- Topic 6: Chemical Reactions ---------------- */
  { id: "q6-01", t: 6, s: "6.1", lv: "C", ty: "multi",
    q: "Which of these are chemical changes? Select all that apply.",
    o: ["Burning magnesium", "Melting ice", "Rusting iron", "Dissolving sugar in water"],
    a: [0, 2],
    ex: "A chemical change makes a new substance and is usually hard to reverse. Melting and dissolving are physical changes because no new substance forms." },

  { id: "q6-02", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Which change would decrease the rate of a reaction between marble chips and hydrochloric acid?",
    o: ["Using more concentrated acid", "Using smaller marble chips",
        "Lowering the temperature", "Adding a catalyst"],
    a: 2,
    ex: "Lowering the temperature means particles move more slowly, so there are fewer collisions and fewer of them have enough energy to react." },

  { id: "q6-03", t: 6, s: "6.2", lv: "S", ty: "mcq",
    q: "Why does increasing the concentration of a solution increase the rate of reaction?",
    o: ["The particles move faster",
        "There are more particles in the same volume, so collisions are more frequent",
        "Each collision has more energy",
        "The activation energy is lowered"],
    a: 1,
    ex: "Concentration changes how crowded the particles are, not how fast they move. More frequent collisions means more successful collisions per second." },

  { id: "q6-04", t: 6, s: "6.2", lv: "S", ty: "mcq",
    q: "Why does raising the temperature increase the rate of reaction? Choose the most complete answer.",
    o: ["The particles collide more often only",
        "The particles have more energy only",
        "The particles move faster so collide more often, and a greater proportion of collisions have energy above the activation energy",
        "The activation energy is reduced"],
    a: 2,
    ex: "Temperature has two effects and the second one matters most: a much larger fraction of collisions now exceeds the activation energy." },

  { id: "q6-05", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Why do powdered solids react faster than large lumps of the same mass?",
    o: ["The powder is more concentrated",
        "The powder has a much larger surface area exposed to the other reactant",
        "The powder is at a higher temperature",
        "The powder has a lower activation energy"],
    a: 1,
    ex: "Reaction happens at the surface. Breaking a solid up exposes far more surface, so there are more collisions per second." },

  { id: "q6-06", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Which statement about a catalyst is correct?",
    o: ["It is used up during the reaction",
        "It increases the rate and is chemically unchanged at the end",
        "It increases the yield of product",
        "It makes the reaction exothermic"],
    a: 1,
    ex: "A catalyst speeds up a reaction without being used up. It does not change how much product is finally made, only how quickly it is made." },

  { id: "q6-07", t: 6, s: "6.2", lv: "S", ty: "mcq",
    q: "How does a catalyst work?",
    o: ["It increases the number of collisions",
        "It raises the temperature of the reaction",
        "It provides an alternative pathway with a lower activation energy",
        "It removes the products as they form"],
    a: 2,
    ex: "With a lower barrier, a greater proportion of collisions has enough energy to react, so the rate increases at the same temperature." },

  { id: "q6-08", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "A student follows a reaction that gives off carbon dioxide by placing the flask on a balance. What does the reading do?",
    o: ["Increases, then levels off", "Decreases, then levels off",
        "Stays constant throughout", "Decreases forever"],
    a: 1,
    ex: "The gas escapes, so the mass falls. The graph levels off when the reaction stops because a reactant has been used up." },

  { id: "q6-09", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "On a graph of volume of gas produced against time, what does the steepness of the curve show?",
    o: ["The total yield", "The rate of reaction",
        "The temperature", "The concentration of the product"],
    a: 1,
    ex: "The gradient is the rate. The curve is steepest at the start when concentrations are highest and becomes horizontal when the reaction finishes." },

  { id: "q6-10", t: 6, s: "6.2", lv: "S", ty: "mcq",
    q: "Why is a fine powder such as flour or custard powder an explosion risk in a mill?",
    o: ["The powder is chemically unstable",
        "The enormous surface area allows extremely rapid combustion once ignited",
        "The powder lowers the activation energy of the air",
        "The powder reacts with nitrogen"],
    a: 1,
    ex: "Suspended in air, the particles have a huge total surface area in contact with oxygen, so combustion can spread almost instantly." },

  { id: "q6-11", t: 6, s: "6.3", lv: "C", ty: "mcq",
    q: "Hydrated copper(II) sulfate is heated. What is observed?",
    o: ["Blue crystals turn white and water is driven off",
        "White crystals turn blue and water is driven off",
        "Blue crystals turn green",
        "There is no change"],
    a: 0,
    ex: "Heating removes the water of crystallisation, leaving white anhydrous copper(II) sulfate. Adding water turns it blue again, so the reaction is reversible." },

  { id: "q6-12", t: 6, s: "6.3", lv: "C", ty: "mcq",
    q: "What colour change occurs when anhydrous cobalt(II) chloride is exposed to water?",
    o: ["Pink to blue", "Blue to pink", "White to blue", "Green to pink"],
    a: 1,
    ex: "Anhydrous cobalt(II) chloride is blue and turns pink when hydrated. This is used as a test for the presence of water." },

  { id: "q6-13", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "What is true at dynamic equilibrium in a closed system?",
    o: ["Both reactions have stopped",
        "The forward and reverse reactions occur at the same rate and concentrations remain constant",
        "The amounts of reactants and products are equal",
        "Only the forward reaction occurs"],
    a: 1,
    ex: "Equilibrium is dynamic, not static. Both reactions continue but at equal rates, so no net change is observed. The amounts are constant but not necessarily equal." },

  { id: "q6-14", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "For N2 + 3H2 gives 2NH3, the forward reaction is exothermic. What happens to the yield of ammonia if the temperature is increased?",
    o: ["It increases", "It decreases", "It is unchanged", "It falls to zero"],
    a: 1,
    ex: "Raising the temperature shifts the position of equilibrium in the endothermic direction, which here is backwards, so less ammonia is produced at equilibrium." },

  { id: "q6-15", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "For N2 + 3H2 gives 2NH3, what is the effect of increasing the pressure on the yield of ammonia?",
    o: ["It increases because there are fewer gas molecules on the product side",
        "It decreases because there are fewer gas molecules on the product side",
        "It has no effect",
        "It increases because ammonia is a liquid"],
    a: 0,
    ex: "Four molecules of gas become two. Higher pressure shifts the equilibrium towards the side with fewer gas molecules, so the yield rises." },

  { id: "q6-16", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "Which are the typical conditions for the Haber process?",
    o: ["450 degrees Celsius, 200 atmospheres, iron catalyst",
        "450 degrees Celsius, 2 atmospheres, vanadium(V) oxide catalyst",
        "25 degrees Celsius, 1 atmosphere, no catalyst",
        "1000 degrees Celsius, 200 atmospheres, nickel catalyst"],
    a: 0,
    ex: "About 450 degrees Celsius and 200 atmospheres with an iron catalyst. The temperature is a compromise between a good yield and a workable rate." },

  { id: "q6-17", t: 6, s: "6.3", lv: "S", ty: "mcq",
    q: "Which catalyst is used in the Contact process?",
    o: ["Iron", "Nickel", "Vanadium(V) oxide", "Platinum"],
    a: 2,
    ex: "Vanadium(V) oxide catalyses the conversion of sulfur dioxide to sulfur trioxide at about 450 degrees Celsius and 2 atmospheres." },

  { id: "q6-18", t: 6, s: "6.4", lv: "C", ty: "mcq",
    q: "In terms of oxygen, what is oxidation?",
    o: ["Loss of oxygen", "Gain of oxygen", "Loss of electrons", "Gain of hydrogen"],
    a: 1,
    ex: "In the simple definition, oxidation is gain of oxygen and reduction is loss of oxygen. Both happen together in a redox reaction." },

  { id: "q6-19", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "In terms of electrons, what is reduction?",
    o: ["Gain of electrons", "Loss of electrons", "Gain of oxygen", "Loss of hydrogen"],
    a: 0,
    ex: "Reduction is gain of electrons, and oxidation is loss. The mnemonic OIL RIG helps: Oxidation Is Loss, Reduction Is Gain." },

  { id: "q6-20", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "In the reaction Fe2O3 + 3CO gives 2Fe + 3CO2, which species is the reducing agent?",
    o: ["Fe2O3", "CO", "Fe", "CO2"],
    a: 1,
    ex: "Carbon monoxide removes oxygen from the iron oxide, so it reduces the iron and is itself oxidised. The reducing agent is the one that gets oxidised." },

  { id: "q6-21", t: 6, s: "6.4", lv: "S", ty: "num",
    q: "What is the oxidation number of manganese in the manganate(VII) ion, MnO4-?",
    a: 7, tol: 0,
    ex: "Each oxygen is -2, giving -8 in total. For an overall charge of -1, manganese must be +7, which is what the Roman numeral in the name tells you." },

  { id: "q6-22", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "What is observed when a reducing agent is added to acidified potassium manganate(VII)?",
    o: ["Purple to colourless", "Colourless to purple",
        "Orange to green", "Green to orange"],
    a: 0,
    ex: "Acidified potassium manganate(VII) is purple and is decolourised when reduced. It is used as a test for reducing agents." },

  { id: "q6-23", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "An oxidising agent is added to aqueous potassium iodide. What is seen?",
    o: ["The solution stays colourless",
        "The solution turns from colourless to brown as iodine is formed",
        "A white precipitate forms",
        "The solution turns purple"],
    a: 1,
    ex: "The oxidising agent removes electrons from iodide ions, forming brown iodine. This is the standard test for an oxidising agent." },

  { id: "q6-24", t: 6, s: "6.4", lv: "S", ty: "mcq",
    q: "In Zn + CuSO4 gives ZnSO4 + Cu, what happens to the zinc?",
    o: ["It is reduced because it gains electrons",
        "It is oxidised because it loses electrons",
        "It is neither oxidised nor reduced",
        "It acts as a catalyst"],
    a: 1,
    ex: "Zinc atoms lose two electrons to become Zn2+, so zinc is oxidised and acts as the reducing agent. The copper ions gain those electrons and are reduced." },

  { id: "q6-25", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Excess marble chips react with 50 cm3 of acid. The experiment is repeated with 50 cm3 of the same acid at a higher temperature. How do the graphs compare?",
    o: ["The second curve is steeper and levels off at the same volume of gas",
        "The second curve is steeper and levels off at a higher volume of gas",
        "The second curve is less steep and levels off lower",
        "The two curves are identical"],
    a: 0,
    ex: "Temperature changes the rate, not the amount of product. The same amount of acid is used, so the same total volume of gas is produced but more quickly." },

  { id: "q6-26", t: 6, s: "6.3", lv: "C", ty: "mcq",
    q: "Which symbol shows that a reaction is reversible?",
    o: ["A single arrow pointing right", "Two half arrows pointing in opposite directions",
        "An equals sign", "A downward arrow"],
    a: 1,
    ex: "The pair of opposing half arrows shows that the reaction can go in both directions under the same conditions." },

  { id: "q6-27", t: 6, s: "6.1", lv: "C", ty: "mcq",
    q: "Which observation is the strongest evidence that a chemical change has taken place?",
    o: ["The mixture gets warmer", "A colour change occurs",
        "A new substance with different properties is formed", "The solid dissolves"],
    a: 2,
    ex: "Temperature and colour changes can happen in physical changes too. The defining feature of a chemical change is that a new substance is made." },

  /* ---------------- Topic 7: Acids, Bases and Salts ---------------- */
  { id: "q7-01", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "Which ion do all acids produce in aqueous solution?",
    o: ["OH-", "H+", "H2+", "O2-"],
    a: 1,
    ex: "An acid in solution is a source of hydrogen ions, H+. An alkali is a soluble base that produces hydroxide ions, OH-." },

  { id: "q7-02", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "What are the products when a dilute acid reacts with a metal carbonate?",
    o: ["Salt and hydrogen only", "Salt, water and carbon dioxide",
        "Salt and water only", "Salt and oxygen"],
    a: 1,
    ex: "Acid plus carbonate always gives a salt, water and carbon dioxide. The fizzing and the limewater test for carbon dioxide identify a carbonate." },

  { id: "q7-03", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "What are the products when a dilute acid reacts with a reactive metal?",
    o: ["Salt and water", "Salt and hydrogen",
        "Salt, water and carbon dioxide", "Metal oxide and hydrogen"],
    a: 1,
    ex: "Acid plus metal gives a salt and hydrogen. The hydrogen can be tested with a lighted splint, which burns with a squeaky pop." },

  { id: "q7-04", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "What colour is methyl orange in an alkaline solution?",
    o: ["Red", "Yellow", "Blue", "Colourless"],
    a: 1,
    ex: "Methyl orange is red in acid and yellow in alkali. Litmus is red in acid and blue in alkali, while thymolphthalein is colourless in acid and blue in alkali." },

  { id: "q7-05", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "A solution has a pH of 3. What is it?",
    o: ["Strongly alkaline", "Weakly alkaline", "Neutral", "Acidic"],
    a: 3,
    ex: "Below 7 is acidic, exactly 7 is neutral and above 7 is alkaline. The lower the number, the more acidic the solution." },

  { id: "q7-06", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "What colour is universal indicator in a strongly alkaline solution?",
    o: ["Red", "Green", "Purple", "Orange"],
    a: 2,
    ex: "Universal indicator runs from red at very low pH, through green at pH 7, to purple at very high pH." },

  { id: "q7-07", t: 7, s: "7.1", lv: "S", ty: "mcq",
    q: "In terms of protons, what is a base?",
    o: ["A proton donor", "A proton acceptor",
        "An electron donor", "An electron acceptor"],
    a: 1,
    ex: "An acid donates protons, that is H+ ions, and a base accepts them. This definition works even where no water is present." },

  { id: "q7-08", t: 7, s: "7.1", lv: "S", ty: "mcq",
    q: "What is the difference between a strong acid and a weak acid?",
    o: ["A strong acid is more concentrated",
        "A strong acid is fully dissociated into ions in solution, while a weak acid is only partially dissociated",
        "A strong acid contains more hydrogen atoms per molecule",
        "A weak acid does not react with metals"],
    a: 1,
    ex: "Strength is about the extent of dissociation, not concentration. Hydrochloric acid is fully dissociated, while ethanoic acid only partly dissociates." },

  { id: "q7-09", t: 7, s: "7.1", lv: "S", ty: "mcq",
    q: "Equal concentrations of hydrochloric acid and ethanoic acid are compared. Which statement is correct?",
    o: ["The ethanoic acid has a lower pH",
        "The hydrochloric acid has a lower pH and reacts faster with magnesium",
        "They have the same pH",
        "Only the ethanoic acid reacts with magnesium"],
    a: 1,
    ex: "The fully dissociated hydrochloric acid has a higher concentration of H+ ions, so it has a lower pH and reacts more quickly." },

  { id: "q7-10", t: 7, s: "7.1", lv: "C", ty: "text",
    q: "What is the name for the reaction between an acid and an alkali that produces a salt and water only?",
    disp: "Neutralisation", a: ["neutralisation", "neutralization", "neutralising"],
    ex: "Neutralisation. The ionic equation is H+ + OH- gives H2O." },

  { id: "q7-11", t: 7, s: "7.2", lv: "C", ty: "mcq",
    q: "Which type of element usually forms an acidic oxide?",
    o: ["Metals", "Non-metals", "Noble gases", "Transition elements"],
    a: 1,
    ex: "Non-metal oxides such as sulfur dioxide and carbon dioxide are acidic. Metal oxides such as sodium oxide and magnesium oxide are basic." },

  { id: "q7-12", t: 7, s: "7.2", lv: "S", ty: "mcq",
    q: "What is an amphoteric oxide?",
    o: ["An oxide that does not react with anything",
        "An oxide that reacts with both acids and alkalis",
        "An oxide that dissolves to give a neutral solution",
        "An oxide that contains two different metals"],
    a: 1,
    ex: "Zinc oxide and aluminium oxide are amphoteric, so they behave as a base with acids and as an acid with alkalis." },

  { id: "q7-13", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Which salt is insoluble in water?",
    o: ["Sodium carbonate", "Potassium nitrate", "Barium sulfate", "Ammonium chloride"],
    a: 2,
    ex: "All sodium, potassium and ammonium salts and all nitrates are soluble. Sulfates are soluble except those of barium, calcium and lead." },

  { id: "q7-14", t: 7, s: "7.3", lv: "C", ty: "multi",
    q: "Which statements about solubility rules are correct? Select all that apply.",
    o: ["All nitrates are soluble",
        "All chlorides are soluble except silver chloride and lead chloride",
        "All carbonates are soluble",
        "All sodium, potassium and ammonium salts are soluble"],
    a: [0, 1, 3],
    ex: "Carbonates are mostly insoluble, the exceptions being those of sodium, potassium and ammonium." },

  { id: "q7-15", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "A soluble salt is made by adding excess copper(II) oxide to warm dilute sulfuric acid. What is the next step?",
    o: ["Evaporate the mixture to dryness",
        "Filter to remove the unreacted copper(II) oxide",
        "Add more acid",
        "Add sodium hydroxide"],
    a: 1,
    ex: "The excess ensures all the acid reacts. Filtering removes the leftover solid, then the filtrate is crystallised to obtain the salt." },

  { id: "q7-16", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Why is the solution heated only to the point of crystallisation rather than evaporated to dryness?",
    o: ["To save time",
        "To avoid decomposing the salt and to allow well formed crystals to grow",
        "To keep the salt dissolved",
        "To remove impurities"],
    a: 1,
    ex: "Evaporating to dryness can decompose the salt and drives off the water of crystallisation, giving a powder rather than crystals." },

  { id: "q7-17", t: 7, s: "7.3", lv: "S", ty: "mcq",
    q: "Why must a titration be used to prepare a salt from an acid and a soluble base?",
    o: ["Because the reaction is very slow",
        "Because there is no excess solid to filter off, so the exact volumes must be found",
        "Because the salt is insoluble",
        "Because an indicator makes the salt purer"],
    a: 1,
    ex: "Both reactants are in solution, so excess cannot be filtered out. The titration finds the exact volume needed, then the process is repeated without indicator." },

  { id: "q7-18", t: 7, s: "7.3", lv: "S", ty: "mcq",
    q: "How is an insoluble salt such as lead(II) sulfate prepared?",
    o: ["By titration",
        "By mixing solutions of two soluble salts so that a precipitate forms, then filtering, washing and drying it",
        "By adding excess metal to an acid",
        "By electrolysis"],
    a: 1,
    ex: "This is precipitation. Mixing lead(II) nitrate solution with a soluble sulfate gives lead(II) sulfate as a solid that can be filtered off." },

  { id: "q7-19", t: 7, s: "7.3", lv: "C", ty: "text",
    q: "Which acid is used to prepare a nitrate salt?",
    disp: "Nitric acid", a: ["nitric acid", "nitric", "hno3"],
    ex: "Nitric acid gives nitrates, hydrochloric acid gives chlorides and sulfuric acid gives sulfates. The acid decides the second half of the salt's name." },

  { id: "q7-20", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "Which is the correct word equation for the reaction of zinc oxide with hydrochloric acid?",
    o: ["zinc oxide + hydrochloric acid gives zinc chloride + water",
        "zinc oxide + hydrochloric acid gives zinc chloride + hydrogen",
        "zinc oxide + hydrochloric acid gives zinc + water + chlorine",
        "zinc oxide + hydrochloric acid gives zinc chloride + carbon dioxide"],
    a: 0,
    ex: "A metal oxide is a base, so acid plus base gives a salt and water only. No gas is produced." },

  { id: "q7-21", t: 7, s: "7.1", lv: "S", ty: "mcq",
    q: "Which ionic equation represents neutralisation?",
    o: ["H+ + OH- gives H2O", "Na+ + Cl- gives NaCl",
        "H+ + Cl- gives HCl", "H2O gives H+ + OH-"],
    a: 0,
    ex: "Whatever acid and alkali are used, the reaction that actually occurs is hydrogen ions combining with hydroxide ions to form water." },

  { id: "q7-22", t: 7, s: "7.2", lv: "C", ty: "mcq",
    q: "Sulfur dioxide dissolves in water. What is the approximate pH of the solution?",
    o: ["3", "7", "10", "14"],
    a: 0,
    ex: "Sulfur dioxide is a non-metal oxide, so it is acidic and gives a solution with a pH well below 7. This contributes to acid rain." },

  { id: "q7-23", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Which salt would be produced by reacting magnesium carbonate with sulfuric acid?",
    o: ["Magnesium sulfide", "Magnesium sulfate",
        "Magnesium sulfite", "Magnesium hydroxide"],
    a: 1,
    ex: "The metal comes from the carbonate and the rest comes from the acid, so sulfuric acid gives a sulfate. Carbon dioxide and water are also formed." },

  { id: "q7-24", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "Which of these is an alkali?",
    o: ["Copper(II) oxide", "Aqueous sodium hydroxide",
        "Dilute sulfuric acid", "Calcium carbonate"],
    a: 1,
    ex: "An alkali is a soluble base. Copper(II) oxide is a base but is insoluble, so it is not an alkali." },

  /* ---------------- Topic 8: The Periodic Table ---------------- */
  { id: "q8-01", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "In what order are the elements arranged in the Periodic Table?",
    o: ["Increasing relative atomic mass", "Increasing proton number",
        "Alphabetical order", "Decreasing reactivity"],
    a: 1,
    ex: "Modern tables are ordered by proton number, which puts every element with matching outer-shell electrons in the same group." },

  { id: "q8-02", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "Why do elements in the same group have similar chemical properties?",
    o: ["They have the same number of shells",
        "They have the same number of outer-shell electrons",
        "They have the same relative atomic mass",
        "They have the same number of neutrons"],
    a: 1,
    ex: "Chemical behaviour depends on the outer-shell electrons, and the group number tells you how many there are." },

  { id: "q8-03", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "How does the character of the elements change across a period from left to right?",
    o: ["From non-metallic to metallic", "From metallic to non-metallic",
        "It stays metallic throughout", "It stays non-metallic throughout"],
    a: 1,
    ex: "Metals are on the left, non-metals on the right, with the change happening around the middle of each period." },

  { id: "q8-04", t: 8, s: "8.1", lv: "S", ty: "mcq",
    q: "What charge does an ion of a Group III element carry?",
    o: ["3-", "1+", "3+", "5+"],
    a: 2,
    ex: "Group III atoms lose three outer electrons to reach a noble gas configuration, giving a 3+ ion such as Al3+." },

  { id: "q8-05", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "How does reactivity change down Group I?",
    o: ["It increases", "It decreases", "It stays the same", "It increases then decreases"],
    a: 0,
    ex: "The outer electron is further from the nucleus and is more shielded, so it is lost more easily. Potassium reacts far more vigorously than lithium." },

  { id: "q8-06", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "What is observed when potassium is added to water?",
    o: ["Nothing happens",
        "It sinks and slowly dissolves",
        "It floats, melts and moves rapidly, and the hydrogen produced burns with a lilac flame",
        "It reacts to form a brown precipitate"],
    a: 2,
    ex: "The reaction is very exothermic, melting the metal and igniting the hydrogen. The resulting solution is alkaline because potassium hydroxide is formed." },

  { id: "q8-07", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "Rubidium is below potassium in Group I. Which prediction is correct?",
    o: ["It is less reactive and has a higher melting point than potassium",
        "It is more reactive and has a lower melting point than potassium",
        "It does not react with water",
        "It has a lower density than lithium"],
    a: 1,
    ex: "Going down Group I, reactivity increases while melting point decreases. Density generally increases down the group." },

  { id: "q8-08", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "Which properties are typical of Group I metals compared with transition metals?",
    o: ["Harder, denser and higher melting points",
        "Softer, lower density and lower melting points",
        "They form coloured compounds",
        "They are unreactive"],
    a: 1,
    ex: "Group I metals are soft enough to cut with a knife, have low densities, low melting points, and form white compounds that dissolve to give colourless solutions." },

  { id: "q8-09", t: 8, s: "8.3", lv: "C", ty: "mcq",
    q: "What are the colour and state of bromine at room temperature?",
    o: ["Pale yellow gas", "Green gas", "Red-brown liquid", "Grey-black solid"],
    a: 2,
    ex: "Chlorine is a pale yellow-green gas, bromine is a red-brown liquid and iodine is a grey-black solid. The colour gets darker down the group." },

  { id: "q8-10", t: 8, s: "8.3", lv: "C", ty: "mcq",
    q: "How does reactivity change down Group VII?",
    o: ["It increases", "It decreases", "It stays the same", "It decreases then increases"],
    a: 1,
    ex: "Halogens react by gaining an electron. Further down the group the outer shell is further from the nucleus, so an electron is attracted less strongly." },

  { id: "q8-11", t: 8, s: "8.3", lv: "S", ty: "mcq",
    q: "Chlorine solution is added to aqueous potassium bromide. What happens?",
    o: ["No reaction occurs",
        "The solution turns orange as bromine is displaced",
        "A white precipitate forms",
        "The solution turns purple"],
    a: 1,
    ex: "Chlorine is more reactive than bromine, so it displaces it: Cl2 + 2KBr gives 2KCl + Br2. The orange colour is the bromine formed." },

  { id: "q8-12", t: 8, s: "8.3", lv: "S", ty: "mcq",
    q: "Which combination results in no reaction?",
    o: ["Chlorine added to potassium iodide", "Bromine added to potassium iodide",
        "Iodine added to potassium bromide", "Chlorine added to potassium bromide"],
    a: 2,
    ex: "A halogen can only displace one below it in the group. Iodine is the least reactive of the three, so it cannot displace bromide ions." },

  { id: "q8-13", t: 8, s: "8.3", lv: "C", ty: "mcq",
    q: "Astatine is below iodine in Group VII. Which prediction is correct?",
    o: ["It is a colourless gas that is very reactive",
        "It is a dark solid that is less reactive than iodine",
        "It is a red liquid more reactive than bromine",
        "It does not form compounds"],
    a: 1,
    ex: "Trends continue down the group: darker colour, higher density and melting point, and lower reactivity." },

  { id: "q8-14", t: 8, s: "8.4", lv: "C", ty: "multi",
    q: "Which are typical properties of transition elements? Select all that apply.",
    o: ["High density", "High melting point",
        "They form coloured compounds", "They react vigorously with cold water"],
    a: [0, 1, 2],
    ex: "Transition elements are dense, strong and high melting, and their compounds are coloured. They are far less reactive than Group I metals." },

  { id: "q8-15", t: 8, s: "8.4", lv: "S", ty: "multi",
    q: "Which additional features are characteristic of transition elements? Select all that apply.",
    o: ["They form ions with variable oxidation numbers",
        "They and their compounds often act as catalysts",
        "They always form 1+ ions",
        "They are all gases at room temperature"],
    a: [0, 1],
    ex: "Iron forms Fe2+ and Fe3+, and copper forms Cu+ and Cu2+. Iron in the Haber process and vanadium(V) oxide in the Contact process are catalysts." },

  { id: "q8-16", t: 8, s: "8.5", lv: "C", ty: "mcq",
    q: "Why are the noble gases unreactive?",
    o: ["They have full outer electron shells, so they have no tendency to lose, gain or share electrons",
        "They are too heavy to react",
        "They have no electrons",
        "They exist as diatomic molecules"],
    a: 0,
    ex: "A full outer shell is already the stable arrangement other atoms are trying to reach, so there is nothing to gain from reacting. Noble gases are monatomic." },

  { id: "q8-17", t: 8, s: "8.5", lv: "C", ty: "mcq",
    q: "What does monatomic mean?",
    o: ["Made of two atoms joined together", "Existing as single, separate atoms",
        "Containing one type of atom only", "Having one electron shell"],
    a: 1,
    ex: "Noble gases exist as single atoms because they have no need to bond, unlike oxygen or chlorine which are diatomic." },

  { id: "q8-18", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "An element is in Group VI, Period 3. What is its electronic configuration?",
    o: ["2,8,6", "2,6", "2,8,8,6", "2,8,3"],
    a: 0,
    ex: "Period 3 means three occupied shells and Group VI means six outer electrons, giving 2,8,6. This is sulfur." },

  { id: "q8-19", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "What is formed when sodium reacts with water?",
    o: ["Sodium oxide and hydrogen", "Sodium hydroxide and hydrogen",
        "Sodium hydride and oxygen", "Sodium peroxide only"],
    a: 1,
    ex: "2Na + 2H2O gives 2NaOH + H2. The solution turns universal indicator purple because sodium hydroxide is a strong alkali." },

  { id: "q8-20", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "Which element is in the same group as fluorine?",
    o: ["Neon", "Oxygen", "Iodine", "Sodium"],
    a: 2,
    ex: "Fluorine is in Group VII with chlorine, bromine, iodine and astatine. Neon is a noble gas and oxygen is in Group VI." },

  { id: "q8-21", t: 8, s: "8.3", lv: "C", ty: "mcq",
    q: "How does the density of the halogens change down Group VII?",
    o: ["It increases", "It decreases", "It stays the same", "It changes randomly"],
    a: 0,
    ex: "Density increases down the group, which fits with the change from gas to liquid to solid at room temperature." }
];
