/* Question bank, part 4: extra coverage so every topic has a full
   challenge deck even with Supplement content switched off. */

window.QUESTIONS_4 = [

  /* ---- Topic 1 ---- */
  { id: "q1-21", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "A substance has a fixed volume but takes the shape of its container. Which state is it in?",
    o: ["Solid", "Liquid", "Gas", "It could be any of them"],
    a: 1,
    ex: "Only a liquid does both. A solid keeps its own shape and a gas has no fixed volume." },

  { id: "q1-22", t: 1, s: "1.1", lv: "C", ty: "mcq",
    q: "Which process happens at a fixed temperature throughout the whole liquid, not just at the surface?",
    o: ["Evaporation", "Boiling", "Condensation", "Diffusion"],
    a: 1,
    ex: "Boiling occurs at one particular temperature and bubbles of vapour form throughout the liquid. Evaporation happens only at the surface, at any temperature." },

  { id: "q1-23", t: 1, s: "1.1", lv: "S", ty: "mcq",
    q: "A sealed syringe of gas is cooled at constant pressure. Which explanation of the volume change is correct?",
    o: ["The particles get smaller so the volume falls",
        "The particles move more slowly and hit the walls less often and less hard, so the volume falls until the pressure balances again",
        "The particles stick together and the volume rises",
        "The number of particles decreases"],
    a: 1,
    ex: "Cooling reduces the average kinetic energy. To keep the pressure equal to the outside pressure, the volume must decrease." },

  { id: "q1-24", t: 1, s: "1.2", lv: "C", ty: "mcq",
    q: "Which pair of conditions gives the fastest diffusion of a gas?",
    o: ["Low temperature, high relative molecular mass",
        "High temperature, low relative molecular mass",
        "Low temperature, low relative molecular mass",
        "High temperature, high relative molecular mass"],
    a: 1,
    ex: "Speed rises with temperature and falls as the molecules get heavier, so hot and light diffuses fastest." },

  /* ---- Topic 3 ---- */
  { id: "q3-29", t: 3, s: "3.1", lv: "C", ty: "num",
    q: "How many atoms in total are represented by the formula Ca(NO3)2?",
    a: 9, tol: 0,
    ex: "1 calcium, plus 2 x (1 nitrogen + 3 oxygen) = 1 + 2 + 6 = 9 atoms." },

  { id: "q3-30", t: 3, s: "3.1", lv: "C", ty: "num",
    q: "Balance the equation and give the coefficient in front of H2O: __ H2 + __ O2 gives __ H2O",
    a: 2, tol: 0,
    ex: "2H2 + O2 gives 2H2O. One O2 supplies two oxygen atoms, so two water molecules are formed." },

  { id: "q3-31", t: 3, s: "3.1", lv: "C", ty: "mcq",
    q: "Which is the correct word equation for burning magnesium in oxygen?",
    o: ["magnesium + oxygen gives magnesium oxide",
        "magnesium + oxygen gives magnesium hydroxide",
        "magnesium oxide gives magnesium + oxygen",
        "magnesium + oxide gives magnesium oxide"],
    a: 0,
    ex: "The reactants go on the left and the single product on the right. The symbol equation is 2Mg + O2 gives 2MgO." },

  { id: "q3-32", t: 3, s: "3.1", lv: "C", ty: "mcq",
    q: "Which element is written as a diatomic molecule in equations?",
    o: ["Carbon", "Sodium", "Chlorine", "Sulfur"],
    a: 2,
    ex: "Hydrogen, nitrogen, oxygen and the halogens all exist as diatomic molecules, so chlorine is written Cl2." },

  { id: "q3-33", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "Calculate the relative molecular mass of carbon dioxide, CO2. Use Ar: C = 12, O = 16",
    a: 44, tol: 0,
    ex: "Mr = 12 + (2 x 16) = 12 + 32 = 44" },

  { id: "q3-34", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "Calculate the relative formula mass of magnesium nitrate, Mg(NO3)2. Use Ar: Mg = 24, N = 14, O = 16",
    a: 148, tol: 0,
    ex: "Mr = 24 + 2 x (14 + 48) = 24 + 124 = 148" },

  { id: "q3-35", t: 3, s: "3.2", lv: "C", ty: "num",
    q: "56 g of iron reacts with 32 g of sulfur to form iron(II) sulfide. What mass of sulfur, in g, reacts with 28 g of iron?",
    a: 16, tol: 0.1,
    ex: "Halving the iron halves the sulfur needed, because reacting masses stay in the same proportion. 32 / 2 = 16 g" },

  { id: "q3-36", t: 3, s: "3.1", lv: "C", ty: "mcq",
    q: "Which equation is correctly balanced?",
    o: ["H2 + Cl2 gives HCl", "2H2 + O2 gives 2H2O",
        "Mg + O2 gives MgO", "Na + Cl2 gives NaCl"],
    a: 1,
    ex: "Only the second has the same number of each type of atom on both sides: 4 H and 2 O either way." },

  /* ---- Topic 4 ---- */
  { id: "q4-25", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "During electrolysis, which way do negative ions move?",
    o: ["To the cathode", "To the anode", "They stay still", "They move at random only"],
    a: 1,
    ex: "Opposite charges attract, so negative ions, the anions, move to the positive anode. Anions to the anode is worth memorising." },

  { id: "q4-26", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "A steel spoon is to be plated with silver. Which electrolyte should be used?",
    o: ["Dilute sulfuric acid", "Aqueous silver nitrate",
        "Aqueous sodium chloride", "Molten lead(II) bromide"],
    a: 1,
    ex: "The electrolyte must contain ions of the plating metal, so a soluble silver salt is needed." },

  { id: "q4-27", t: 4, s: "4.1", lv: "C", ty: "mcq",
    q: "Which substance would conduct electricity and be decomposed by it?",
    o: ["Solid sodium chloride", "Molten sodium chloride",
        "Copper wire", "Sugar solution"],
    a: 1,
    ex: "Molten sodium chloride has free ions, so it conducts and is broken down. Copper conducts but is an element, so nothing decomposes." },

  /* ---- Topic 5 ---- */
  { id: "q5-13", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Dilute hydrochloric acid is added to sodium hydroxide solution and the temperature rises from 20 to 27 degrees Celsius. What can you conclude?",
    o: ["The reaction is endothermic", "The reaction is exothermic",
        "No reaction occurred", "Energy was destroyed"],
    a: 1,
    ex: "Neutralisation releases energy to the surroundings, so the temperature of the mixture rises." },

  { id: "q5-14", t: 5, s: "5.1", lv: "C", ty: "multi",
    q: "Which of these are endothermic? Select all that apply.",
    o: ["Thermal decomposition of calcium carbonate", "Respiration",
        "Photosynthesis", "The combustion of ethanol"],
    a: [0, 2],
    ex: "Both need a continuous supply of energy, heat in one case and light in the other. Respiration and combustion both release energy." },

  { id: "q5-15", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "A self-heating can of coffee warms up when a chemical reaction inside it starts. What kind of reaction is it?",
    o: ["Endothermic, because energy is absorbed",
        "Exothermic, because energy is released to the surroundings",
        "Reversible", "Neutralisation only"],
    a: 1,
    ex: "The energy released by the reaction warms the drink, so the reaction is exothermic." },

  { id: "q5-16", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "On a reaction pathway diagram, what does the vertical distance between the reactants and the products represent?",
    o: ["The activation energy", "The overall energy change of the reaction",
        "The temperature rise", "The rate of reaction"],
    a: 1,
    ex: "That difference is the overall energy change. The activation energy is measured from the reactants up to the top of the curve." },

  { id: "q5-17", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Magnesium is added to copper(II) sulfate solution and the temperature rises sharply. Which statement is correct?",
    o: ["The displacement reaction is exothermic",
        "The displacement reaction is endothermic",
        "The magnesium is melting",
        "The water is boiling"],
    a: 0,
    ex: "Displacement reactions of a more reactive metal are strongly exothermic, which is why the mixture heats up quickly." },

  { id: "q5-18", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Which of these always releases energy?",
    o: ["Breaking a chemical bond", "Forming a chemical bond",
        "Melting a solid", "Evaporating a liquid"],
    a: 1,
    ex: "Making bonds is exothermic. Breaking bonds, melting and evaporating all require energy to be supplied." },

  { id: "q5-19", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "A student mixes two solutions and the temperature falls by 5 degrees Celsius. Which statement about the products is correct?",
    o: ["The products store less energy than the reactants",
        "The products store more energy than the reactants",
        "The products and reactants store the same energy",
        "No bonds were formed"],
    a: 1,
    ex: "Energy has been taken in from the surroundings, so it is now stored in the products. This is an endothermic reaction." },

  { id: "q5-20", t: 5, s: "5.1", lv: "C", ty: "mcq",
    q: "Which practical precaution improves the accuracy of a temperature change measurement?",
    o: ["Using a larger beaker",
        "Insulating the container with a lid and a polystyrene cup to reduce energy loss",
        "Stirring with the thermometer",
        "Heating the solutions first"],
    a: 1,
    ex: "Energy lost to the surroundings makes an exothermic temperature rise look smaller than it really is, so insulation matters." },

  { id: "q5-21", t: 5, s: "5.1", lv: "S", ty: "num",
    q: "A reaction breaks bonds worth 940 kJ/mol and forms bonds worth 1180 kJ/mol. What is delta H in kJ/mol?",
    a: -240, tol: 1,
    ex: "delta H = bonds broken - bonds made = 940 - 1180 = -240 kJ/mol, so the reaction is exothermic." },

  { id: "q5-22", t: 5, s: "5.1", lv: "S", ty: "mcq",
    q: "On a reaction pathway diagram for an endothermic reaction, which is true?",
    o: ["The products are below the reactants and delta H is negative",
        "The products are above the reactants and delta H is positive",
        "There is no activation energy",
        "The activation energy equals delta H"],
    a: 1,
    ex: "Energy has been absorbed, so the products sit higher than the reactants and delta H carries a positive sign." },

  /* ---- Topic 6 ---- */
  { id: "q6-28", t: 6, s: "6.2", lv: "C", ty: "mcq",
    q: "Two identical experiments are run, one with 1.0 mol/dm3 acid and one with 2.0 mol/dm3 acid, both with excess magnesium. What difference is seen?",
    o: ["The more concentrated acid produces gas faster and produces more gas in total",
        "The more concentrated acid produces gas faster but the same total volume",
        "Both produce gas at the same rate",
        "The more concentrated acid produces less gas"],
    a: 0,
    ex: "With the metal in excess, the acid is the limiting reactant. Doubling its concentration doubles the moles of acid, so both the rate and the total gas increase." },

  { id: "q6-29", t: 6, s: "6.1", lv: "C", ty: "mcq",
    q: "Which change is a physical change?",
    o: ["Iron rusting", "Sublimation of solid carbon dioxide",
        "Burning wood", "A metal reacting with an acid"],
    a: 1,
    ex: "Sublimation is only a change of state, so no new substance is formed and it can be reversed by cooling." },

  { id: "q6-30", t: 6, s: "6.3", lv: "C", ty: "mcq",
    q: "White anhydrous copper(II) sulfate is left in a damp room and turns blue. Which statement is correct?",
    o: ["A new element has formed",
        "It has been hydrated, and heating would reverse the change",
        "It has been oxidised",
        "The change is irreversible"],
    a: 1,
    ex: "Water of crystallisation has been taken up. Heating drives it off again, which is why the reaction is described as reversible." },

  /* ---- Topic 7 ---- */
  { id: "q7-25", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "What is the pH of a neutral solution such as pure water?",
    o: ["0", "5", "7", "14"],
    a: 2,
    ex: "pH 7 is neutral, and universal indicator turns green." },

  { id: "q7-26", t: 7, s: "7.1", lv: "C", ty: "mcq",
    q: "A gas given off when an acid is added to a solid turns limewater milky. What does the solid contain?",
    o: ["A metal", "A carbonate", "A hydroxide", "A sulfate"],
    a: 1,
    ex: "Only a carbonate gives carbon dioxide with a dilute acid. A metal would give hydrogen instead." },

  { id: "q7-27", t: 7, s: "7.3", lv: "C", ty: "mcq",
    q: "Which method is used to obtain dry crystals from the filtrate after preparing a soluble salt?",
    o: ["Heat the filtrate to the point of crystallisation, cool it, then filter and dry the crystals",
        "Boil the filtrate until only powder remains",
        "Add more acid and filter again",
        "Add a precipitating agent"],
    a: 0,
    ex: "Slow crystallisation gives well formed crystals. The crystals are then dried between filter papers or in a warm oven." },

  /* ---- Topic 8 ---- */
  { id: "q8-22", t: 8, s: "8.2", lv: "C", ty: "mcq",
    q: "What is observed when a small piece of lithium is dropped into water?",
    o: ["It sinks and no reaction occurs",
        "It floats and fizzes steadily, giving off hydrogen and forming an alkaline solution",
        "It explodes immediately with a lilac flame",
        "It turns the water red"],
    a: 1,
    ex: "Lithium is the least reactive of the three Group I metals studied, so the reaction is steady rather than violent. It forms lithium hydroxide and hydrogen." },

  { id: "q8-23", t: 8, s: "8.1", lv: "C", ty: "mcq",
    q: "Which pair of elements would you expect to have the most similar chemical properties?",
    o: ["Sodium and magnesium", "Chlorine and argon",
        "Magnesium and calcium", "Oxygen and fluorine"],
    a: 2,
    ex: "Magnesium and calcium are both in Group II, so both have two outer-shell electrons and behave similarly. The other pairs are in different groups." },

  { id: "q8-24", t: 8, s: "8.5", lv: "C", ty: "mcq",
    q: "Which use of a noble gas depends on it being unreactive?",
    o: ["Filling weather balloons with helium",
        "Using argon in a light bulb to stop the filament burning away",
        "Using neon in advertising signs",
        "All of these"],
    a: 3,
    ex: "Every one of these uses relies on the gas being chemically inert as well as having the right physical property." },

  /* ---- Topic 9 ---- */
  { id: "q9-24", t: 9, s: "9.4", lv: "S", ty: "mcq",
    q: "A mixture of magnesium powder and copper(II) oxide is heated strongly. What happens?",
    o: ["No reaction, because copper is more reactive",
        "Magnesium reduces the copper(II) oxide, forming magnesium oxide and copper",
        "The magnesium is oxidised by the air only",
        "Copper reduces the magnesium"],
    a: 1,
    ex: "Mg + CuO gives MgO + Cu. The more reactive metal takes the oxygen, so magnesium is oxidised and the copper oxide is reduced." },

  { id: "q9-25", t: 9, s: "9.3", lv: "C", ty: "mcq",
    q: "Which pair correctly matches an alloy with its components?",
    o: ["Brass is copper and zinc", "Brass is copper and tin",
        "Stainless steel is iron and copper", "Stainless steel is aluminium and carbon"],
    a: 0,
    ex: "Brass is copper with zinc. Stainless steel is iron with chromium and nickel, which stops it rusting." },

  { id: "q9-26", t: 9, s: "9.5", lv: "C", ty: "mcq",
    q: "In an experiment, an iron nail is placed in boiled water covered with a layer of oil. What is observed after a week and why?",
    o: ["It rusts, because water is present",
        "It does not rust, because boiling removed the dissolved oxygen and the oil keeps air out",
        "It rusts faster, because oil speeds up corrosion",
        "It dissolves"],
    a: 1,
    ex: "Rusting needs both water and oxygen. Removing one of them stops the process, which is what this control shows." },

  { id: "q9-27", t: 9, s: "9.6", lv: "C", ty: "mcq",
    q: "Why is copper found as the uncombined metal in some places, while sodium never is?",
    o: ["Copper is denser than sodium",
        "Copper is very unreactive, so it does not readily form compounds, while sodium is highly reactive",
        "Copper has a higher melting point",
        "Sodium is a transition metal"],
    a: 1,
    ex: "The lower a metal sits in the reactivity series, the more likely it is to be found native rather than as an ore." },

  /* ---- Topic 10 ---- */
  { id: "q10-17", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "Which stage of water treatment removes the smallest suspended solids?",
    o: ["Sedimentation", "Filtration through sand", "Chlorination", "Boiling"],
    a: 1,
    ex: "Sedimentation lets the largest particles settle out, then filtration through sand traps the finer ones. Chlorination deals with microbes, not solids." },

  { id: "q10-18", t: 10, s: "10.1", lv: "C", ty: "mcq",
    q: "A liquid turns anhydrous cobalt(II) chloride from blue to pink. What does this prove?",
    o: ["The liquid is pure water",
        "The liquid contains water, but it may not be pure",
        "The liquid is an acid",
        "The liquid contains dissolved salts"],
    a: 1,
    ex: "The chemical test only shows water is present. Proving purity needs the boiling and freezing points instead." },

  { id: "q10-19", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "What is the main source of the methane released by human activity?",
    o: ["Car exhausts", "Livestock farming and decomposing waste in landfill",
        "Power stations burning coal", "Volcanoes"],
    a: 1,
    ex: "Cattle digestion and rotting waste release large amounts of methane, which is a powerful greenhouse gas." },

  { id: "q10-20", t: 10, s: "10.3", lv: "C", ty: "mcq",
    q: "Which pollutant is formed by the incomplete combustion of a hydrocarbon fuel?",
    o: ["Sulfur dioxide", "Carbon monoxide", "Oxides of nitrogen", "Ozone"],
    a: 1,
    ex: "A limited supply of oxygen gives carbon monoxide and carbon particulates instead of carbon dioxide." },

  /* ---- Topic 11 ---- */
  { id: "q11-32", t: 11, s: "11.2", lv: "C", ty: "text",
    q: "What is the name of the alcohol with two carbon atoms?",
    disp: "Ethanol", a: ["ethanol"],
    ex: "Ethanol, C2H5OH. The eth prefix means two carbons and the anol ending shows the -OH functional group." },

  { id: "q11-33", t: 11, s: "11.3", lv: "C", ty: "mcq",
    q: "Which property makes the shorter fractions from petroleum easier to use as fuels?",
    o: ["They are more viscous", "They are more volatile and ignite more easily",
        "They have higher boiling points", "They are darker in colour"],
    a: 1,
    ex: "Shorter chains have weaker forces between molecules, so they evaporate readily and burn easily." },

  { id: "q11-34", t: 11, s: "11.8", lv: "C", ty: "mcq",
    q: "Which monomer is used to make poly(ethene)?",
    o: ["Ethane", "Ethene", "Ethanol", "Ethanoic acid"],
    a: 1,
    ex: "The carbon to carbon double bond in ethene opens up so that thousands of molecules can join together in a long chain." },

  /* ---- Topic 12 ---- */
  { id: "q12-29", t: 12, s: "12.1", lv: "C", ty: "mcq",
    q: "A burette reading is taken. Where should the eye be placed?",
    o: ["Above the meniscus, looking down",
        "Level with the bottom of the meniscus",
        "Below the meniscus, looking up",
        "It does not matter"],
    a: 1,
    ex: "Reading at eye level to the bottom of the curve avoids a parallax error." },

  { id: "q12-30", t: 12, s: "12.2", lv: "C", ty: "mcq",
    q: "Why is a titration repeated until concordant results are obtained?",
    o: ["To use up the solutions",
        "To show the results are reliable, so a fair mean titre can be calculated",
        "To warm the solutions evenly",
        "To make the indicator work"],
    a: 1,
    ex: "Concordant titres, usually within 0.10 cm3 of each other, show the technique was consistent. The rough first run is left out of the mean." },

  { id: "q12-31", t: 12, s: "12.4", lv: "C", ty: "mcq",
    q: "Which technique separates two liquids that do not mix, such as oil and water?",
    o: ["A separating funnel", "Fractional distillation",
        "Filtration", "Chromatography"],
    a: 0,
    ex: "The denser lower layer is run off through the tap first, leaving the other layer behind." },

  { id: "q12-32", t: 12, s: "12.3", lv: "C", ty: "mcq",
    q: "In a chromatogram, why does one substance travel further up the paper than another?",
    o: ["It is heavier",
        "It is more soluble in the solvent and less strongly attracted to the paper",
        "It is more strongly attracted to the paper",
        "It was placed higher on the start line"],
    a: 1,
    ex: "Separation depends on the balance between solubility in the moving solvent and attraction to the stationary paper." }
];
