/* glossary.js — key terms. Doubles as the flashcard deck.
   { id, t: term, d: definition, u: unit, tp: topic id }                   */

BS.glossary = [
  /* ---------------- Unit 1 ---------------- */
  { id: 'needs', t: 'Needs', d: 'Goods and services essential for human survival, such as food, water, shelter, warmth and clothing.', u: 1, tp: '1.1' },
  { id: 'wants', t: 'Wants', d: 'Goods and services people would like to have but can survive without. Wants are unlimited.', u: 1, tp: '1.1' },
  { id: 'scarcity', t: 'Scarcity', d: 'There are not enough resources to satisfy everyone\'s unlimited wants, so choices have to be made.', u: 1, tp: '1.1' },
  { id: 'opportunity-cost', t: 'Opportunity cost', d: 'The next best alternative given up when a choice is made.', u: 1, tp: '1.1' },
  { id: 'factors-of-production', t: 'Factors of production', d: 'The four resources used to produce goods and services: land, labour, capital and enterprise.', u: 1, tp: '1.1' },
  { id: 'specialisation', t: 'Specialisation', d: 'When people, businesses or countries concentrate on producing what they are best at.', u: 1, tp: '1.1' },
  { id: 'division-of-labour', t: 'Division of labour', d: 'Splitting production into separate tasks so that each worker performs only one of them.', u: 1, tp: '1.1' },
  { id: 'added-value', t: 'Added value', d: 'The difference between the selling price of a product and the cost of the bought-in materials and components used to make it. It is not the same as profit.', u: 1, tp: '1.1' },

  { id: 'primary-sector', t: 'Primary sector', d: 'Business activity that extracts natural resources from the earth or sea: farming, fishing, mining, oil extraction, forestry.', u: 1, tp: '1.2' },
  { id: 'secondary-sector', t: 'Secondary sector', d: 'Business activity that manufactures or processes goods, and construction.', u: 1, tp: '1.2' },
  { id: 'tertiary-sector', t: 'Tertiary sector', d: 'Business activity that provides services to businesses and consumers: retailing, banking, transport, insurance, hotels.', u: 1, tp: '1.2' },
  { id: 'de-industrialisation', t: 'De-industrialisation', d: 'The decline in the importance of the secondary (manufacturing) sector of an economy, and the growth of the tertiary sector.', u: 1, tp: '1.2' },
  { id: 'private-sector', t: 'Private sector', d: 'Businesses owned and run by individuals or groups of individuals, usually aiming to make a profit.', u: 1, tp: '1.2' },
  { id: 'public-sector', t: 'Public sector', d: 'Organisations owned and run by the government, usually aiming to provide a service rather than a profit.', u: 1, tp: '1.2' },
  { id: 'mixed-economy', t: 'Mixed economy', d: 'An economy that contains both a private sector and a public sector.', u: 1, tp: '1.2' },
  { id: 'privatisation', t: 'Privatisation', d: 'Selling a public-sector (government-owned) business to the private sector.', u: 1, tp: '1.2' },

  { id: 'entrepreneur', t: 'Entrepreneur', d: 'A person who organises the other factors of production and takes the financial risk of starting and running a business.', u: 1, tp: '1.3' },
  { id: 'business-plan', t: 'Business plan', d: 'A written document describing a business, its objectives, strategies, target market and financial forecasts. Usually required by lenders.', u: 1, tp: '1.3' },
  { id: 'internal-growth', t: 'Internal (organic) growth', d: 'When a business expands its own operations — new branches, new products, new markets — rather than joining with another business.', u: 1, tp: '1.3' },
  { id: 'external-growth', t: 'External growth', d: 'When a business grows by merging with or taking over another business.', u: 1, tp: '1.3' },
  { id: 'horizontal-integration', t: 'Horizontal integration', d: 'When one business merges with or takes over another in the same industry at the same stage of production.', u: 1, tp: '1.3' },
  { id: 'vertical-integration', t: 'Vertical integration', d: 'When one business merges with or takes over another in the same industry but at a different stage of production. Forward = towards the customer; backward = towards the raw materials.', u: 1, tp: '1.3' },
  { id: 'conglomerate', t: 'Conglomerate integration (diversification)', d: 'When one business merges with or takes over a business in a completely different industry, to spread risk.', u: 1, tp: '1.3' },
  { id: 'merger', t: 'Merger', d: 'When the owners of two businesses agree to join together to form one new business.', u: 1, tp: '1.3' },
  { id: 'takeover', t: 'Takeover (acquisition)', d: 'When one business buys a controlling interest (over 50% of the shares) in another business.', u: 1, tp: '1.3' },
  { id: 'capital-employed', t: 'Capital employed', d: 'The total long-term finance invested in a business: shareholders\' equity plus non-current liabilities.', u: 1, tp: '1.3' },
  { id: 'market-share', t: 'Market share', d: 'The percentage of total sales in a market that is held by one business or product.', u: 1, tp: '1.3' },

  { id: 'sole-trader', t: 'Sole trader', d: 'A business owned and controlled by one person, who has unlimited liability.', u: 1, tp: '1.4' },
  { id: 'partnership', t: 'Partnership', d: 'A business owned by two or more partners who share the capital, the decisions and the profits, usually with unlimited liability.', u: 1, tp: '1.4' },
  { id: 'unlimited-liability', t: 'Unlimited liability', d: 'The owners are personally responsible for all the debts of the business, so their personal possessions can be taken to pay creditors.', u: 1, tp: '1.4' },
  { id: 'limited-liability', t: 'Limited liability', d: 'The owners can only lose the amount they have invested in the business; their personal possessions are protected.', u: 1, tp: '1.4' },
  { id: 'private-limited-company', t: 'Private limited company (Ltd)', d: 'An incorporated business with limited liability whose shares are sold privately and cannot be offered to the general public.', u: 1, tp: '1.4' },
  { id: 'public-limited-company', t: 'Public limited company (plc)', d: 'An incorporated business with limited liability that can sell its shares to the general public on a stock exchange.', u: 1, tp: '1.4' },
  { id: 'shareholder', t: 'Shareholder', d: 'A part-owner of a limited company who has bought shares in it and receives dividends.', u: 1, tp: '1.4' },
  { id: 'dividend', t: 'Dividend', d: 'A share of a company\'s profit paid to its shareholders.', u: 1, tp: '1.4' },
  { id: 'franchise', t: 'Franchise', d: 'An agreement in which one business (the franchisor) allows another (the franchisee) to use its brand name and business format in return for a fee and a share of revenue.', u: 1, tp: '1.4' },
  { id: 'joint-venture', t: 'Joint venture', d: 'When two or more businesses agree to start a new project together, sharing the cost, risk, expertise and profit.', u: 1, tp: '1.4' },
  { id: 'public-corporation', t: 'Public corporation', d: 'A business owned and run by the government, usually providing an essential service.', u: 1, tp: '1.4' },
  { id: 'incorporation', t: 'Incorporation', d: 'Giving a business a separate legal identity from its owners, which creates limited liability.', u: 1, tp: '1.4' },
  { id: 'divorce-of-ownership-and-control', t: 'Divorce of ownership and control', d: 'In a public limited company the shareholders own the business but directors and managers control it, so their objectives can conflict.', u: 1, tp: '1.4' },

  { id: 'objective', t: 'Business objective', d: 'A target or goal that a business sets itself and works towards, used to give direction and measure success.', u: 1, tp: '1.5' },
  { id: 'smart-objectives', t: 'SMART objectives', d: 'Objectives that are Specific, Measurable, Achievable, Realistic and Time-bound.', u: 1, tp: '1.5' },
  { id: 'stakeholder', t: 'Stakeholder', d: 'Any person or group with an interest in the activities of a business, such as owners, employees, customers, suppliers, government and the local community.', u: 1, tp: '1.5' },
  { id: 'social-enterprise', t: 'Social enterprise', d: 'A business with social, environmental or ethical objectives as well as financial ones, which reinvests most of its profit into its social purpose.', u: 1, tp: '1.5' },
  { id: 'triple-bottom-line', t: 'Triple bottom line', d: 'Measuring business success on three objectives: profit, people (social) and planet (environmental).', u: 1, tp: '1.5' },
  { id: 'profit-maximisation', t: 'Profit maximisation', d: 'Setting the objective of making the largest possible profit.', u: 1, tp: '1.5' },

  /* ---------------- Unit 2 ---------------- */
  { id: 'motivation', t: 'Motivation', d: 'The reason why employees work, and the effort they are willing to put into their work.', u: 2, tp: '2.1' },
  { id: 'labour-turnover', t: 'Labour turnover', d: 'The percentage of a business\'s workforce that leaves in a year. Calculated as (number leaving ÷ average number employed) × 100.', u: 2, tp: '2.1' },
  { id: 'productivity', t: 'Productivity', d: 'A measure of efficiency: the output produced per worker (or per machine) in a given period.', u: 2, tp: '2.1' },
  { id: 'piece-rate', t: 'Piece rate', d: 'A payment system where workers are paid a fixed amount for each unit they produce.', u: 2, tp: '2.1' },
  { id: 'time-rate', t: 'Time rate (wage)', d: 'A payment system where workers are paid a fixed amount for each hour worked.', u: 2, tp: '2.1' },
  { id: 'salary', t: 'Salary', d: 'A fixed annual amount of pay, usually paid monthly, not directly linked to hours worked or units produced.', u: 2, tp: '2.1' },
  { id: 'commission', t: 'Commission', d: 'Payment based on a percentage of the value of the sales an employee makes.', u: 2, tp: '2.1' },
  { id: 'bonus', t: 'Bonus', d: 'An additional payment made to employees for reaching a target or for good performance.', u: 2, tp: '2.1' },
  { id: 'profit-sharing', t: 'Profit sharing', d: 'A system in which employees receive a share of the profits the business makes.', u: 2, tp: '2.1' },
  { id: 'performance-related-pay', t: 'Performance-related pay', d: 'Pay linked to how well an employee performs, usually judged through an appraisal.', u: 2, tp: '2.1' },
  { id: 'fringe-benefits', t: 'Fringe benefits', d: 'Non-cash rewards given to employees in addition to pay, such as a company car, health insurance, staff discount or a pension.', u: 2, tp: '2.1' },
  { id: 'job-rotation', t: 'Job rotation', d: 'Regularly switching employees between different tasks of a similar level to reduce boredom.', u: 2, tp: '2.1' },
  { id: 'job-enlargement', t: 'Job enlargement', d: 'Adding more tasks of a similar level of difficulty to a job to give more variety.', u: 2, tp: '2.1' },
  { id: 'job-enrichment', t: 'Job enrichment', d: 'Adding tasks that require more skill and responsibility to a job, so it becomes more challenging and rewarding.', u: 2, tp: '2.1' },
  { id: 'empowerment', t: 'Empowerment', d: 'Giving employees the authority to make decisions about how they do their own work.', u: 2, tp: '2.1' },
  { id: 'teamworking', t: 'Teamworking', d: 'Organising employees into groups that are jointly responsible for a complete unit of work.', u: 2, tp: '2.1' },
  { id: 'taylor', t: 'Taylor (scientific management)', d: 'The theory that workers are motivated mainly by money, so jobs should be broken into simple timed tasks and workers paid per unit produced.', u: 2, tp: '2.1' },
  { id: 'maslow', t: 'Maslow (hierarchy of needs)', d: 'The theory that human needs form a hierarchy — physical, safety, social, esteem, self-actualisation — and each level must be satisfied before the next motivates.', u: 2, tp: '2.1' },
  { id: 'herzberg', t: 'Herzberg (two-factor theory)', d: 'The theory that hygiene factors such as pay and conditions prevent dissatisfaction but do not motivate; only motivators such as achievement, recognition and responsibility create satisfaction.', u: 2, tp: '2.1' },

  { id: 'organisational-structure', t: 'Organisational structure', d: 'The way a business arranges its employees into levels and departments, showing who is responsible to whom.', u: 2, tp: '2.2' },
  { id: 'hierarchy', t: 'Hierarchy', d: 'The levels of management within a business, from the most senior at the top to the least senior at the bottom.', u: 2, tp: '2.2' },
  { id: 'chain-of-command', t: 'Chain of command', d: 'The path along which instructions and authority pass down through the levels of an organisation.', u: 2, tp: '2.2' },
  { id: 'span-of-control', t: 'Span of control', d: 'The number of subordinates who report directly to one manager.', u: 2, tp: '2.2' },
  { id: 'delegation', t: 'Delegation', d: 'Giving a subordinate the authority to carry out a task, while the manager keeps overall responsibility for it.', u: 2, tp: '2.2' },
  { id: 'delayering', t: 'Delayering', d: 'Removing one or more levels of the hierarchy, usually middle management, to make the structure flatter.', u: 2, tp: '2.2' },
  { id: 'autocratic', t: 'Autocratic leadership', d: 'A leadership style in which the leader makes all the decisions alone and tells employees what to do.', u: 2, tp: '2.2' },
  { id: 'democratic', t: 'Democratic leadership', d: 'A leadership style in which the leader discusses decisions with employees and takes their views into account.', u: 2, tp: '2.2' },
  { id: 'laissez-faire', t: 'Laissez-faire leadership', d: 'A leadership style in which the leader sets broad goals and then leaves employees to decide how to achieve them.', u: 2, tp: '2.2' },
  { id: 'trade-union', t: 'Trade union', d: 'An organisation of workers that negotiates with employers over pay and conditions on behalf of its members.', u: 2, tp: '2.2' },
  { id: 'collective-bargaining', t: 'Collective bargaining', d: 'Negotiations between a trade union and an employer over pay and conditions on behalf of all the union\'s members.', u: 2, tp: '2.2' },

  { id: 'job-description', t: 'Job description', d: 'A document setting out the title, duties, responsibilities and reporting line of a job.', u: 2, tp: '2.3' },
  { id: 'person-specification', t: 'Person specification', d: 'A document setting out the qualifications, skills, experience and personal qualities needed by the ideal candidate for a job.', u: 2, tp: '2.3' },
  { id: 'internal-recruitment', t: 'Internal recruitment', d: 'Filling a vacancy with someone who already works for the business.', u: 2, tp: '2.3' },
  { id: 'external-recruitment', t: 'External recruitment', d: 'Filling a vacancy with someone from outside the business.', u: 2, tp: '2.3' },
  { id: 'induction-training', t: 'Induction training', d: 'Training given to a new employee when they first start, covering the layout, procedures, health and safety and key people.', u: 2, tp: '2.3' },
  { id: 'on-the-job-training', t: 'On-the-job training', d: 'Training given at the workplace by watching and being guided by an experienced employee while doing the job.', u: 2, tp: '2.3' },
  { id: 'off-the-job-training', t: 'Off-the-job training', d: 'Training given away from the workplace, such as a college course or a specialist training centre.', u: 2, tp: '2.3' },
  { id: 'redundancy', t: 'Redundancy', d: 'When an employee loses their job because the job itself is no longer needed, not because of anything they have done wrong.', u: 2, tp: '2.3' },
  { id: 'dismissal', t: 'Dismissal', d: 'When an employee\'s contract is ended because they have broken it, for example through poor performance or misconduct.', u: 2, tp: '2.3' },
  { id: 'natural-wastage', t: 'Natural wastage', d: 'Reducing the size of the workforce by not replacing employees who leave or retire.', u: 2, tp: '2.3' },
  { id: 'minimum-wage', t: 'Minimum wage', d: 'A legally enforced lowest hourly rate of pay that employers must pay their workers.', u: 2, tp: '2.3' },
  { id: 'part-time-employee', t: 'Part-time employee', d: 'An employee who works fewer hours than a full-time employee, giving the business flexibility to match staffing to demand.', u: 2, tp: '2.3' },

  { id: 'communication', t: 'Communication', d: 'The transfer of a message from a sender to a receiver, which is only effective when it is understood and feedback is given.', u: 2, tp: '2.4' },
  { id: 'feedback', t: 'Feedback', d: 'The response of the receiver, which tells the sender that the message has been received and understood.', u: 2, tp: '2.4' },
  { id: 'internal-communication', t: 'Internal communication', d: 'Communication between people within the same business.', u: 2, tp: '2.4' },
  { id: 'external-communication', t: 'External communication', d: 'Communication between the business and people or organisations outside it, such as customers, suppliers and government.', u: 2, tp: '2.4' },
  { id: 'one-way-communication', t: 'One-way communication', d: 'Communication in which the receiver has no opportunity to respond, such as a notice on a noticeboard.', u: 2, tp: '2.4' },
  { id: 'two-way-communication', t: 'Two-way communication', d: 'Communication in which the receiver can respond and give feedback, such as a meeting or a phone call.', u: 2, tp: '2.4' },
  { id: 'communication-barrier', t: 'Communication barrier', d: 'Anything that stops a message being received or understood, such as jargon, noise, the wrong medium or a long chain of command.', u: 2, tp: '2.4' },

  /* ---------------- Unit 3 ---------------- */
  { id: 'marketing', t: 'Marketing', d: 'The management process of identifying, anticipating and satisfying customer requirements profitably.', u: 3, tp: '3.1' },
  { id: 'mass-marketing', t: 'Mass marketing', d: 'Selling one product to the whole market rather than to a particular segment.', u: 3, tp: '3.1' },
  { id: 'niche-marketing', t: 'Niche marketing', d: 'Aiming a product at a small, specific segment of a larger market.', u: 3, tp: '3.1' },
  { id: 'market-segmentation', t: 'Market segmentation', d: 'Dividing a market into groups of customers with similar characteristics so a product and marketing mix can be aimed at each group.', u: 3, tp: '3.1' },
  { id: 'consumer', t: 'Consumer', d: 'The person who uses a product, who is not always the person who bought it.', u: 3, tp: '3.1' },
  { id: 'brand', t: 'Brand', d: 'A name, symbol or design that identifies a product and distinguishes it from those of competitors.', u: 3, tp: '3.1' },

  { id: 'market-research', t: 'Market research', d: 'The collection, recording and analysis of data about customers, competitors and the market, in order to reduce the risk of business decisions.', u: 3, tp: '3.2' },
  { id: 'primary-research', t: 'Primary (field) research', d: 'Collecting new, original data first hand for a specific purpose.', u: 3, tp: '3.2' },
  { id: 'secondary-research', t: 'Secondary (desk) research', d: 'Using data that already exists, collected by someone else for a different purpose.', u: 3, tp: '3.2' },
  { id: 'questionnaire', t: 'Questionnaire', d: 'A set of questions used to collect data from a sample of people, in person, by post, by phone or online.', u: 3, tp: '3.2' },
  { id: 'focus-group', t: 'Focus group', d: 'A small group of consumers who discuss a product or idea with a researcher to give detailed opinions.', u: 3, tp: '3.2' },
  { id: 'sample', t: 'Sample', d: 'The group of people questioned in market research, chosen to represent the whole target market.', u: 3, tp: '3.2' },
  { id: 'quantitative-data', t: 'Quantitative data', d: 'Data that can be measured and expressed as numbers, making it easy to compare but unable to explain why.', u: 3, tp: '3.2' },
  { id: 'qualitative-data', t: 'Qualitative data', d: 'Data about opinions, attitudes and reasons, which explains motives but is harder to analyse.', u: 3, tp: '3.2' },
  { id: 'test-marketing', t: 'Test marketing', d: 'Selling a new product in a limited area before a full launch, to gather real sales data and find problems.', u: 3, tp: '3.2' },

  { id: 'marketing-mix', t: 'Marketing mix', d: 'The combination of product, price, place and promotion used to market a product. All four must be consistent with each other.', u: 3, tp: '3.3' },
  { id: 'product-life-cycle', t: 'Product life cycle', d: 'The stages a product passes through from development, through introduction, growth and maturity, to decline.', u: 3, tp: '3.3' },
  { id: 'extension-strategy', t: 'Extension strategy', d: 'A method used to lengthen the life of a product at the maturity or decline stage, such as new packaging, new versions, new markets or a price cut.', u: 3, tp: '3.3' },
  { id: 'packaging', t: 'Packaging', d: 'The material around a product, which protects it, makes it easy to transport, promotes it and informs the customer.', u: 3, tp: '3.3' },
  { id: 'cost-plus-pricing', t: 'Cost-plus pricing', d: 'Setting a price by calculating the cost per unit and adding a fixed percentage mark-up.', u: 3, tp: '3.3' },
  { id: 'penetration-pricing', t: 'Penetration pricing', d: 'Setting a low price when entering a market in order to gain customers and market share quickly.', u: 3, tp: '3.3' },
  { id: 'price-skimming', t: 'Price skimming', d: 'Setting a high price for a new, innovative product at launch, then lowering it once competitors appear.', u: 3, tp: '3.3' },
  { id: 'competitive-pricing', t: 'Competitive pricing', d: 'Setting a price at or just below the prices charged by competitors.', u: 3, tp: '3.3' },
  { id: 'promotional-pricing', t: 'Promotional pricing', d: 'Temporarily lowering the price to boost sales, clear stock or launch a product.', u: 3, tp: '3.3' },
  { id: 'psychological-pricing', t: 'Psychological pricing', d: 'Setting a price to influence how customers perceive it, such as $9.99 instead of $10, or a high price to signal quality.', u: 3, tp: '3.3' },
  { id: 'price-elasticity-of-demand', t: 'Price elasticity of demand', d: 'A measure of how much the quantity demanded responds to a change in price: % change in quantity demanded ÷ % change in price. Above 1 is elastic; below 1 is inelastic.', u: 3, tp: '3.3' },
  { id: 'channel-of-distribution', t: 'Channel of distribution', d: 'The route a product takes from the producer to the final consumer.', u: 3, tp: '3.3' },
  { id: 'wholesaler', t: 'Wholesaler', d: 'A business that buys in bulk from producers, stores the goods and sells smaller quantities to retailers.', u: 3, tp: '3.3' },
  { id: 'retailer', t: 'Retailer', d: 'A business that sells goods directly to the final consumer.', u: 3, tp: '3.3' },
  { id: 'informative-advertising', t: 'Informative advertising', d: 'Advertising that gives customers factual information about a product, such as its features, price and where to buy it.', u: 3, tp: '3.3' },
  { id: 'persuasive-advertising', t: 'Persuasive advertising', d: 'Advertising that tries to convince customers that they want or need a product, often using images and emotion.', u: 3, tp: '3.3' },
  { id: 'above-the-line', t: 'Above-the-line promotion', d: 'Promotion carried out through independent media such as TV, radio, newspapers and billboards.', u: 3, tp: '3.3' },
  { id: 'below-the-line', t: 'Below-the-line promotion', d: 'Promotion the business controls directly, such as special offers, free samples, loyalty cards, point-of-sale displays and direct mail.', u: 3, tp: '3.3' },
  { id: 'e-commerce', t: 'E-commerce', d: 'Buying and selling goods and services over the internet.', u: 3, tp: '3.3' },
  { id: 'viral-marketing', t: 'Viral marketing', d: 'Using social media so that users share the marketing message themselves, spreading it rapidly at little cost.', u: 3, tp: '3.3' },

  { id: 'marketing-strategy', t: 'Marketing strategy', d: 'A plan that uses the marketing mix to achieve the marketing objectives of a business.', u: 3, tp: '3.4' },
  { id: 'misleading-advertising', t: 'Misleading advertising', d: 'Advertising that makes false or exaggerated claims about a product. It is illegal in most countries.', u: 3, tp: '3.4' },
  { id: 'consumer-protection', t: 'Consumer protection', d: 'Laws that protect customers from unsafe products, false descriptions, misleading advertising and unfair trading.', u: 3, tp: '3.4' },
  { id: 'exporting', t: 'Exporting', d: 'Selling goods or services produced in one country to customers in another country.', u: 3, tp: '3.4' },

  /* ---------------- Unit 4 ---------------- */
  { id: 'production', t: 'Production', d: 'The process of converting inputs such as land, labour and capital into outputs of goods and services.', u: 4, tp: '4.1' },
  { id: 'job-production', t: 'Job production', d: 'Producing one unique item at a time, made to the customer\'s specific order and completed before the next is started.', u: 4, tp: '4.1' },
  { id: 'batch-production', t: 'Batch production', d: 'Producing groups of identical items together, with each stage completed for the whole batch before the next begins.', u: 4, tp: '4.1' },
  { id: 'flow-production', t: 'Flow (mass) production', d: 'Producing large quantities of an identical product continuously along a production line.', u: 4, tp: '4.1' },
  { id: 'lean-production', t: 'Lean production', d: 'Producing goods and services with the minimum waste of time, materials, labour, space and energy.', u: 4, tp: '4.1' },
  { id: 'just-in-time', t: 'Just-in-time (JIT)', d: 'An inventory method in which materials arrive exactly when they are needed, so almost no stock is held.', u: 4, tp: '4.1' },
  { id: 'kaizen', t: 'Kaizen', d: 'Continuous improvement — all employees regularly suggest small improvements to methods, layout and processes.', u: 4, tp: '4.1' },
  { id: 'cell-production', t: 'Cell production', d: 'Dividing the production line into self-contained teams, each responsible for a complete unit of work.', u: 4, tp: '4.1' },
  { id: 'buffer-stock', t: 'Buffer stock', d: 'A minimum level of inventory held in reserve in case of unexpected demand or supply problems.', u: 4, tp: '4.1' },
  { id: 'automation', t: 'Automation', d: 'Using machines and computers to carry out tasks previously done by workers.', u: 4, tp: '4.1' },
  { id: 'cad-cam', t: 'CAD / CAM', d: 'Computer-aided design (designing products on a computer) and computer-aided manufacture (computers controlling the machines that make them).', u: 4, tp: '4.1' },

  { id: 'fixed-costs', t: 'Fixed costs', d: 'Costs that do not change with the level of output in the short run, such as rent, insurance and managers\' salaries.', u: 4, tp: '4.2' },
  { id: 'variable-costs', t: 'Variable costs', d: 'Costs that change directly with the level of output, such as raw materials, components and piece-rate wages.', u: 4, tp: '4.2' },
  { id: 'total-costs', t: 'Total costs', d: 'Fixed costs plus total variable costs.', u: 4, tp: '4.2' },
  { id: 'average-cost', t: 'Average cost (unit cost)', d: 'The cost of producing one unit: total costs divided by output.', u: 4, tp: '4.2' },
  { id: 'revenue', t: 'Revenue', d: 'The income a business receives from selling its products: selling price × quantity sold.', u: 4, tp: '4.2' },
  { id: 'contribution', t: 'Contribution per unit', d: 'Selling price per unit minus variable cost per unit. It contributes first to paying fixed costs and then to profit.', u: 4, tp: '4.2' },
  { id: 'break-even', t: 'Break-even point', d: 'The level of output at which total revenue exactly equals total costs, so the business makes neither profit nor loss. Calculated as fixed costs ÷ contribution per unit.', u: 4, tp: '4.2' },
  { id: 'margin-of-safety', t: 'Margin of safety', d: 'The amount by which current output exceeds the break-even output, showing how far sales can fall before a loss is made.', u: 4, tp: '4.2' },
  { id: 'economies-of-scale', t: 'Economies of scale', d: 'The factors that cause average cost per unit to fall as a business grows: purchasing, technical, financial, marketing, managerial and risk-bearing.', u: 4, tp: '4.2' },
  { id: 'diseconomies-of-scale', t: 'Diseconomies of scale', d: 'The factors that cause average cost per unit to rise when a business becomes too large: poor communication, poor coordination, low morale and slow decision making.', u: 4, tp: '4.2' },

  { id: 'quality', t: 'Quality', d: 'Producing a good or service that meets customers\' expectations — fit for purpose, reliable and safe.', u: 4, tp: '4.3' },
  { id: 'quality-control', t: 'Quality control', d: 'Checking and inspecting products at the end of the production process to find and remove faults.', u: 4, tp: '4.3' },
  { id: 'quality-assurance', t: 'Quality assurance', d: 'Checking quality throughout the production process, with standards agreed at every stage, so that faults are prevented rather than found later.', u: 4, tp: '4.3' },
  { id: 'tqm', t: 'Total quality management (TQM)', d: 'A quality assurance approach in which every employee is responsible for quality at every stage, aiming for zero defects.', u: 4, tp: '4.3' },

  { id: 'location', t: 'Location decision', d: 'The choice of where to site a business, based on factors such as costs, markets, labour, transport and legal controls.', u: 4, tp: '4.4' },
  { id: 'relocation', t: 'Relocation', d: 'Moving a business from one site to another, usually to cut costs, expand or get closer to a market.', u: 4, tp: '4.4' },
  { id: 'footfall', t: 'Footfall', d: 'The number of potential customers passing a retail site, a key factor in shop location.', u: 4, tp: '4.4' },
  { id: 'infrastructure', t: 'Infrastructure', d: 'The basic facilities a business needs to operate: roads, ports, airports, power, water and communications.', u: 4, tp: '4.4' },
  { id: 'government-incentives', t: 'Government incentives', d: 'Grants, subsidies, tax breaks and cheap rent offered to persuade businesses to locate in a particular area.', u: 4, tp: '4.4' },
  { id: 'planning-permission', t: 'Planning permission', d: 'Legal approval from local government that a business must obtain before building or changing the use of premises.', u: 4, tp: '4.4' },

  /* ---------------- Unit 5 ---------------- */
  { id: 'retained-profit', t: 'Retained profit', d: 'Profit kept in the business after tax and dividends, and reinvested. It is an internal, permanent source of finance with no interest.', u: 5, tp: '5.1' },
  { id: 'overdraft', t: 'Bank overdraft', d: 'An arrangement allowing a business to withdraw more than is in its bank account, up to an agreed limit. Flexible but with a high interest rate.', u: 5, tp: '5.1' },
  { id: 'trade-credit', t: 'Trade credit', d: 'Buying goods from suppliers and paying for them at a later date, usually 30 to 90 days — effectively an interest-free short-term loan.', u: 5, tp: '5.1' },
  { id: 'bank-loan', t: 'Bank loan', d: 'A fixed sum borrowed from a bank and repaid with interest in instalments over an agreed period. Usually requires collateral.', u: 5, tp: '5.1' },
  { id: 'share-issue', t: 'Share issue', d: 'Raising permanent capital by selling new shares in a limited company. It never has to be repaid but dilutes ownership.', u: 5, tp: '5.1' },
  { id: 'debenture', t: 'Debenture', d: 'A long-term loan certificate sold by a company to investors, repayable on a fixed future date with interest.', u: 5, tp: '5.1' },
  { id: 'hire-purchase', t: 'Hire purchase', d: 'Paying for an asset in instalments, with ownership passing to the business at the final payment.', u: 5, tp: '5.1' },
  { id: 'leasing', t: 'Leasing', d: 'Renting an asset rather than buying it, avoiding a large initial payment but never owning the asset.', u: 5, tp: '5.1' },
  { id: 'venture-capital', t: 'Venture capital', d: 'Finance provided by specialist investors to high-risk, high-growth businesses in return for a share of the business.', u: 5, tp: '5.1' },
  { id: 'collateral', t: 'Collateral (security)', d: 'An asset pledged to a lender, which the lender can take and sell if the loan is not repaid.', u: 5, tp: '5.1' },
  { id: 'crowdfunding', t: 'Crowdfunding', d: 'Raising finance by collecting small amounts from a large number of people, usually through an online platform.', u: 5, tp: '5.1' },
  { id: 'microfinance', t: 'Microfinance', d: 'Very small loans provided to entrepreneurs in low-income countries who cannot access normal banking services.', u: 5, tp: '5.1' },
  { id: 'debt-factoring', t: 'Debt factoring', d: 'Selling unpaid customer invoices to a finance company, which pays most of their value immediately, improving cash flow.', u: 5, tp: '5.1' },

  { id: 'cash-flow', t: 'Cash flow', d: 'The flow of money into and out of a business over a period of time.', u: 5, tp: '5.2' },
  { id: 'cash-inflow', t: 'Cash inflow', d: 'Money coming into a business, such as cash sales, payments from debtors, loans received and asset sales.', u: 5, tp: '5.2' },
  { id: 'cash-outflow', t: 'Cash outflow', d: 'Money going out of a business, such as payments for materials, wages, rent, loan repayments and equipment.', u: 5, tp: '5.2' },
  { id: 'net-cash-flow', t: 'Net cash flow', d: 'Total cash inflows minus total cash outflows in a period.', u: 5, tp: '5.2' },
  { id: 'opening-balance', t: 'Opening balance', d: 'The amount of cash a business holds at the start of a period, which equals the previous period\'s closing balance.', u: 5, tp: '5.2' },
  { id: 'closing-balance', t: 'Closing balance', d: 'The amount of cash held at the end of a period: opening balance plus net cash flow.', u: 5, tp: '5.2' },
  { id: 'cash-flow-forecast', t: 'Cash-flow forecast', d: 'An estimate of future cash inflows and outflows, month by month, used to predict when cash shortages will occur.', u: 5, tp: '5.2' },
  { id: 'working-capital', t: 'Working capital', d: 'The finance available for day-to-day running of a business: current assets minus current liabilities.', u: 5, tp: '5.2' },
  { id: 'liquidity', t: 'Liquidity', d: 'The ability of a business to pay its short-term debts as they fall due.', u: 5, tp: '5.2' },
  { id: 'insolvency', t: 'Insolvency', d: 'When a business cannot pay its debts as they fall due, even if it owns valuable assets.', u: 5, tp: '5.2' },

  { id: 'income-statement', t: 'Income statement', d: 'A financial statement showing a business\'s revenue, costs and profit over a period of time, usually one year.', u: 5, tp: '5.3' },
  { id: 'cost-of-sales', t: 'Cost of sales', d: 'The direct cost of the goods actually sold during the period, such as materials and direct labour.', u: 5, tp: '5.3' },
  { id: 'gross-profit', t: 'Gross profit', d: 'Revenue minus cost of sales — profit before overheads and expenses are deducted.', u: 5, tp: '5.3' },
  { id: 'net-profit', t: 'Profit (net profit)', d: 'Gross profit minus all expenses and overheads — what the business has actually earned from trading.', u: 5, tp: '5.3' },
  { id: 'expenses', t: 'Expenses (overheads)', d: 'The indirect running costs of a business, such as rent, salaries, marketing, insurance and electricity.', u: 5, tp: '5.3' },
  { id: 'depreciation', t: 'Depreciation', d: 'The fall in the value of a non-current asset over time, recorded as an expense in the income statement.', u: 5, tp: '5.3' },

  { id: 'statement-of-financial-position', t: 'Statement of financial position', d: 'A financial statement showing what a business owns, what it owes and the capital invested by the owners at one point in time.', u: 5, tp: '5.4' },
  { id: 'non-current-asset', t: 'Non-current (fixed) asset', d: 'An asset a business keeps and uses for more than one year, such as land, buildings, machinery and vehicles.', u: 5, tp: '5.4' },
  { id: 'current-asset', t: 'Current asset', d: 'An asset likely to be turned into cash within one year: inventory, trade receivables and cash.', u: 5, tp: '5.4' },
  { id: 'current-liability', t: 'Current liability', d: 'A debt that must be repaid within one year: trade payables, overdraft, short-term loans and tax owed.', u: 5, tp: '5.4' },
  { id: 'non-current-liability', t: 'Non-current (long-term) liability', d: 'A debt repayable in more than one year, such as a bank loan, mortgage or debenture.', u: 5, tp: '5.4' },
  { id: 'inventory', t: 'Inventory (stock)', d: 'Raw materials, work in progress and finished goods held by a business. A current asset.', u: 5, tp: '5.4' },
  { id: 'trade-receivables', t: 'Trade receivables (debtors)', d: 'Money owed to the business by customers who have bought on credit. A current asset.', u: 5, tp: '5.4' },
  { id: 'trade-payables', t: 'Trade payables (creditors)', d: 'Money the business owes to suppliers for goods bought on credit. A current liability.', u: 5, tp: '5.4' },
  { id: 'shareholders-equity', t: 'Shareholders\' equity', d: 'The owners\' stake in a company: share capital plus retained earnings.', u: 5, tp: '5.4' },

  { id: 'gross-profit-margin', t: 'Gross profit margin', d: 'A profitability ratio: (gross profit ÷ revenue) × 100. It shows how well direct costs and pricing are controlled.', u: 5, tp: '5.5' },
  { id: 'profit-margin', t: 'Profit margin', d: 'A profitability ratio: (profit ÷ revenue) × 100. It shows how well both direct costs and overheads are controlled.', u: 5, tp: '5.5' },
  { id: 'roce', t: 'Return on capital employed (ROCE)', d: 'A profitability ratio: (profit ÷ capital employed) × 100. It shows how much profit is earned for every $100 of capital invested.', u: 5, tp: '5.5' },
  { id: 'current-ratio', t: 'Current ratio', d: 'A liquidity ratio: current assets ÷ current liabilities. Around 1.5:1 to 2:1 is usually considered safe.', u: 5, tp: '5.5' },
  { id: 'acid-test-ratio', t: 'Acid test ratio', d: 'A liquidity ratio: (current assets − inventory) ÷ current liabilities. Around 1:1 is usually considered safe.', u: 5, tp: '5.5' },
  { id: 'ratio-analysis', t: 'Ratio analysis', d: 'Using figures from the accounts to calculate ratios that measure performance and allow comparison over time and between businesses.', u: 5, tp: '5.5' },
  { id: 'window-dressing', t: 'Window dressing', d: 'Presenting accounts in a way that makes the business look better than it really is.', u: 5, tp: '5.5' },

  /* ---------------- Unit 6 ---------------- */
  { id: 'inflation', t: 'Inflation', d: 'A sustained rise in the general level of prices, which reduces the value of money.', u: 6, tp: '6.1' },
  { id: 'unemployment', t: 'Unemployment', d: 'People who are willing and able to work but cannot find a job.', u: 6, tp: '6.1' },
  { id: 'economic-growth', t: 'Economic growth', d: 'An increase in a country\'s real gross domestic product (GDP) over time.', u: 6, tp: '6.1' },
  { id: 'gdp', t: 'Gross domestic product (GDP)', d: 'The total value of goods and services produced in a country in a year.', u: 6, tp: '6.1' },
  { id: 'recession', t: 'Recession', d: 'A period of falling GDP, usually lasting two consecutive quarters or more, with rising unemployment and falling demand.', u: 6, tp: '6.1' },
  { id: 'business-cycle', t: 'Business (trade) cycle', d: 'The pattern of growth, boom, recession, slump and recovery that an economy repeatedly passes through.', u: 6, tp: '6.1' },
  { id: 'fiscal-policy', t: 'Fiscal policy', d: 'Government decisions about taxation and government spending, used to influence the economy.', u: 6, tp: '6.1' },
  { id: 'monetary-policy', t: 'Monetary policy', d: 'Government or central bank decisions about interest rates and the money supply, used to influence the economy.', u: 6, tp: '6.1' },
  { id: 'direct-tax', t: 'Direct tax', d: 'A tax on income and profit, paid directly by the person or business earning it, such as income tax and corporation tax.', u: 6, tp: '6.1' },
  { id: 'indirect-tax', t: 'Indirect tax', d: 'A tax on spending, added to the price of goods and services, such as VAT or sales tax.', u: 6, tp: '6.1' },
  { id: 'interest-rate', t: 'Interest rate', d: 'The cost of borrowing money, and the reward for saving, expressed as a percentage.', u: 6, tp: '6.1' },
  { id: 'disposable-income', t: 'Disposable income', d: 'The income a consumer has left to spend or save after income tax has been deducted.', u: 6, tp: '6.1' },
  { id: 'supply-side-policy', t: 'Supply-side policy', d: 'Government policies that aim to increase the economy\'s capacity to produce, such as training, lower business taxes and better infrastructure.', u: 6, tp: '6.1' },

  { id: 'sustainable-development', t: 'Sustainable development', d: 'Development that meets the needs of the present without reducing the ability of future generations to meet their own needs.', u: 6, tp: '6.2' },
  { id: 'externalities', t: 'Externalities', d: 'Costs or benefits of business activity that fall on third parties rather than on the business itself, such as pollution.', u: 6, tp: '6.2' },
  { id: 'social-costs', t: 'Social costs', d: 'The full cost to society of business activity: the private costs paid by the business plus the external costs borne by others.', u: 6, tp: '6.2' },
  { id: 'business-ethics', t: 'Business ethics', d: 'The moral principles that guide business decisions — doing what is right, not just what is legal or profitable.', u: 6, tp: '6.2' },
  { id: 'pressure-group', t: 'Pressure group', d: 'An organisation of people who campaign to change the behaviour of businesses or governments, for example on the environment.', u: 6, tp: '6.2' },
  { id: 'recycling', t: 'Recycling', d: 'Reprocessing used materials into new products, reducing waste and the use of non-renewable resources.', u: 6, tp: '6.2' },
  { id: 'carbon-footprint', t: 'Carbon footprint', d: 'The total amount of greenhouse gases produced by the activities of a business or product.', u: 6, tp: '6.2' },

  { id: 'globalisation', t: 'Globalisation', d: 'The growing integration of the world\'s economies, so that businesses increasingly buy, sell, produce and invest across national borders.', u: 6, tp: '6.3' },
  { id: 'tariff', t: 'Tariff', d: 'A tax on imported goods, which raises their price so consumers switch to domestic products.', u: 6, tp: '6.3' },
  { id: 'quota', t: 'Quota', d: 'A physical limit on the quantity of a good that may be imported into a country.', u: 6, tp: '6.3' },
  { id: 'free-trade', t: 'Free trade', d: 'International trade without tariffs, quotas or other barriers.', u: 6, tp: '6.3' },
  { id: 'trade-bloc', t: 'Trade bloc', d: 'A group of countries that have agreed to remove trade barriers between themselves.', u: 6, tp: '6.3' },
  { id: 'multinational-company', t: 'Multinational company (MNC)', d: 'A business with its headquarters in one country that produces or operates in two or more countries.', u: 6, tp: '6.3' },
  { id: 'exchange-rate', t: 'Exchange rate', d: 'The price of one currency in terms of another.', u: 6, tp: '6.3' },
  { id: 'currency-appreciation', t: 'Appreciation of a currency', d: 'A rise in the value of a currency against others. It makes imports cheaper and exports dearer (SPICED).', u: 6, tp: '6.3' },
  { id: 'currency-depreciation', t: 'Depreciation of a currency', d: 'A fall in the value of a currency against others. It makes imports dearer and exports cheaper.', u: 6, tp: '6.3' },
  { id: 'exports', t: 'Exports', d: 'Goods and services produced in one country and sold to customers in another.', u: 6, tp: '6.3' },
  { id: 'imports', t: 'Imports', d: 'Goods and services bought from producers in another country.', u: 6, tp: '6.3' },
  { id: 'protectionism', t: 'Protectionism', d: 'Government policies such as tariffs and quotas that restrict imports in order to protect domestic businesses and jobs.', u: 6, tp: '6.3' }
];

BS.term = function (id) {
  for (var i = 0; i < BS.glossary.length; i++) if (BS.glossary[i].id === id) return BS.glossary[i];
  return null;
};
