/* glossary.js — key terms, written to mark-scheme precision.

   { id, t: term, d: definition, keys: [creditable elements], note?, u, tp }

   d     the definition as it should be written in the exam: one sentence,
         no commentary, using the technical vocabulary examiners look for.
   keys  the separate elements a 2-mark definition question credits. Write a
         definition containing all of these and it cannot be marked down.
   note  a warning about how the term is commonly got wrong. Not part of the
         definition — never write it as one.                                  */

BS.glossary = [

/* ==================== UNIT 1 ==================== */

{ id: 'needs', t: 'Needs', d: 'Goods and services essential for human survival.', u: 1, tp: '1.1',
  keys: ['essential / necessary for survival', 'e.g. food, water, shelter, clothing, warmth'] },
{ id: 'wants', t: 'Wants', d: 'Goods and services people would like to have but which are not essential for survival.', u: 1, tp: '1.1',
  keys: ['desired but not essential', 'unlimited in number'] },
{ id: 'scarcity', t: 'Scarcity', d: 'The lack of sufficient resources to satisfy everyone\'s unlimited wants.', u: 1, tp: '1.1',
  keys: ['limited / insufficient resources', 'unlimited wants, so choices must be made'] },
{ id: 'opportunity-cost', t: 'Opportunity cost', d: 'The next best alternative given up when a choice is made.', u: 1, tp: '1.1',
  keys: ['the next best alternative', 'given up / forgone when choosing'],
  note: 'Not "the money spent". It is the alternative sacrificed — name a specific one from the case.' },
{ id: 'factors-of-production', t: 'Factors of production', d: 'The resources needed to produce goods and services: land, labour, capital and enterprise.', u: 1, tp: '1.1',
  keys: ['resources used to produce', 'land, labour, capital, enterprise'] },
{ id: 'specialisation', t: 'Specialisation', d: 'When people, businesses or countries concentrate on producing the goods and services they are best at making.', u: 1, tp: '1.1',
  keys: ['concentrating on one product or task', 'what they do best / most efficiently'] },
{ id: 'division-of-labour', t: 'Division of labour', d: 'When the production process is split into separate tasks and each worker performs only one of those tasks.', u: 1, tp: '1.1',
  keys: ['production split into separate tasks', 'each worker does one task repeatedly'] },
{ id: 'added-value', t: 'Added value', d: 'The difference between the selling price of a product and the cost of the bought-in materials and components used to make it.', u: 1, tp: '1.1',
  keys: ['selling price minus cost of bought-in materials', 'per unit / per product'],
  note: 'Added value is not profit. Wages, rent and other costs still have to be paid out of it.' },

{ id: 'primary-sector', t: 'Primary sector', d: 'Business activity that extracts or uses natural resources from the earth or sea.', u: 1, tp: '1.2',
  keys: ['extracting natural resources', 'e.g. farming, fishing, mining, oil extraction, forestry'] },
{ id: 'secondary-sector', t: 'Secondary sector', d: 'Business activity that manufactures or processes goods, including construction.', u: 1, tp: '1.2',
  keys: ['manufacturing / processing into finished goods', 'e.g. car assembly, baking, construction'] },
{ id: 'tertiary-sector', t: 'Tertiary sector', d: 'Business activity that provides services to consumers and other businesses.', u: 1, tp: '1.2',
  keys: ['providing services', 'e.g. retailing, banking, transport, insurance'] },
{ id: 'de-industrialisation', t: 'De-industrialisation', d: 'The decline in the relative importance of the secondary sector of an economy.', u: 1, tp: '1.2',
  keys: ['fall in importance of manufacturing / secondary sector', 'usually alongside growth of the tertiary sector'] },
{ id: 'private-sector', t: 'Private sector', d: 'Business activity owned and controlled by individuals or groups of individuals.', u: 1, tp: '1.2',
  keys: ['owned by individuals / shareholders, not government', 'usually aims to make a profit'] },
{ id: 'public-sector', t: 'Public sector', d: 'Business activity owned and controlled by the government.', u: 1, tp: '1.2',
  keys: ['owned / controlled by the government or state', 'usually aims to provide a service'],
  note: 'A public limited company is private sector. "Public" there means the shares can be bought by the public.' },
{ id: 'mixed-economy', t: 'Mixed economy', d: 'An economy in which resources are owned and allocated by both the private sector and the public sector.', u: 1, tp: '1.2',
  keys: ['contains both a private and a public sector'] },
{ id: 'privatisation', t: 'Privatisation', d: 'The sale of public-sector organisations to the private sector.', u: 1, tp: '1.2',
  keys: ['transfer of ownership from government', 'to the private sector'] },

{ id: 'entrepreneur', t: 'Entrepreneur', d: 'A person who organises the other factors of production and takes the risk of starting and running a business.', u: 1, tp: '1.3',
  keys: ['organises the other factors of production', 'takes the financial risk'] },
{ id: 'business-plan', t: 'Business plan', d: 'A document containing the business objectives and important details about the operations, finance and owners of the business.', u: 1, tp: '1.3',
  keys: ['a written document setting out objectives', 'covers operations, marketing, finance and owners'] },
{ id: 'internal-growth', t: 'Internal (organic) growth', d: 'When a business expands by increasing its own scale of operations rather than by joining with another business.', u: 1, tp: '1.3',
  keys: ['expanding its own operations', 'e.g. new branches, new products, new markets'] },
{ id: 'external-growth', t: 'External growth', d: 'When a business expands by merging with or taking over another business.', u: 1, tp: '1.3',
  keys: ['growth by joining with another business', 'through a merger or takeover'] },
{ id: 'horizontal-integration', t: 'Horizontal integration', d: 'When one business merges with or takes over another business in the same industry at the same stage of production.', u: 1, tp: '1.3',
  keys: ['same industry', 'same stage of production'] },
{ id: 'vertical-integration', t: 'Vertical integration', d: 'When one business merges with or takes over another business in the same industry but at a different stage of production.', u: 1, tp: '1.3',
  keys: ['same industry', 'different stage of production'],
  note: 'Forward = towards the customer. Backward = towards the raw materials. Name the direction.' },
{ id: 'conglomerate', t: 'Conglomerate integration (diversification)', d: 'When one business merges with or takes over a business in a completely different industry.', u: 1, tp: '1.3',
  keys: ['different / unrelated industry', 'spreads risk through diversification'] },
{ id: 'merger', t: 'Merger', d: 'When the owners of two businesses agree to join their businesses together to form one new business.', u: 1, tp: '1.3',
  keys: ['two businesses join together', 'by agreement, forming one new business'] },
{ id: 'takeover', t: 'Takeover (acquisition)', d: 'When one business buys a controlling interest in another business.', u: 1, tp: '1.3',
  keys: ['buying over 50% of the shares', 'gaining control, possibly without agreement'] },
{ id: 'capital-employed', t: 'Capital employed', d: 'The total long-term finance invested in a business, made up of shareholders\' equity plus non-current liabilities.', u: 1, tp: '1.3',
  keys: ['total long-term finance invested', 'equity plus non-current liabilities'] },
{ id: 'market-share', t: 'Market share', d: 'The percentage of total sales in a market held by one business or product.', u: 1, tp: '1.3',
  keys: ['a business\'s sales as a percentage', 'of total market sales'] },

{ id: 'sole-trader', t: 'Sole trader', d: 'A business owned and controlled by one person.', u: 1, tp: '1.4',
  keys: ['owned and controlled by one person', 'has unlimited liability'],
  note: 'A sole trader can still employ other people — "one person" means one owner.' },
{ id: 'partnership', t: 'Partnership', d: 'A business owned and controlled by two or more people who share the capital, the decisions and the profits.', u: 1, tp: '1.4',
  keys: ['two or more owners', 'share capital, control and profits'] },
{ id: 'unlimited-liability', t: 'Unlimited liability', d: 'When the owners of a business are personally responsible for all of its debts.', u: 1, tp: '1.4',
  keys: ['owners personally responsible for business debts', 'personal possessions can be taken to pay creditors'] },
{ id: 'limited-liability', t: 'Limited liability', d: 'When the liability of the owners of a business is limited to the amount they have invested in it.', u: 1, tp: '1.4',
  keys: ['owners can only lose what they invested', 'personal possessions are protected'],
  note: 'It limits the *owners\'* losses, not the company\'s debts.' },
{ id: 'private-limited-company', t: 'Private limited company (Ltd)', d: 'A business owned by shareholders with limited liability, whose shares cannot be sold to the general public.', u: 1, tp: '1.4',
  keys: ['incorporated, with limited liability', 'shares sold privately, not to the public'] },
{ id: 'public-limited-company', t: 'Public limited company (plc)', d: 'A business owned by shareholders with limited liability, whose shares can be bought and sold by the general public on a stock exchange.', u: 1, tp: '1.4',
  keys: ['incorporated, with limited liability', 'shares can be sold to the public on a stock exchange'] },
{ id: 'shareholder', t: 'Shareholder', d: 'A part-owner of a limited company who has bought shares in it.', u: 1, tp: '1.4',
  keys: ['a part-owner of a limited company', 'receives dividends and can vote'] },
{ id: 'dividend', t: 'Dividend', d: 'A share of a company\'s profits paid to its shareholders.', u: 1, tp: '1.4',
  keys: ['payment from profit', 'to shareholders / owners'],
  note: 'A dividend is a distribution of profit, not an expense of the business.' },
{ id: 'franchise', t: 'Franchise', d: 'A business agreement in which one business (the franchisor) gives another business (the franchisee) the right to use its name, products and business format in return for a fee and a share of revenue.', u: 1, tp: '1.4',
  keys: ['the right to trade using an established brand and format', 'in return for a fee and a share of revenue'] },
{ id: 'joint-venture', t: 'Joint venture', d: 'When two or more businesses agree to work together on a project and share the cost, risk and profit.', u: 1, tp: '1.4',
  keys: ['two or more businesses work together on a project', 'sharing cost, risk and profit'] },
{ id: 'public-corporation', t: 'Public corporation', d: 'A business owned and controlled by the government, usually providing an essential service.', u: 1, tp: '1.4',
  keys: ['owned and run by the government', 'provides a service rather than maximising profit'] },
{ id: 'incorporation', t: 'Incorporation', d: 'When a business is given a legal identity separate from that of its owners.', u: 1, tp: '1.4',
  keys: ['separate legal identity from its owners', 'creates limited liability and continuity'] },
{ id: 'divorce-of-ownership-and-control', t: 'Divorce of ownership and control', d: 'When the shareholders who own a company are not the same people as the directors and managers who control it.', u: 1, tp: '1.4',
  keys: ['shareholders own but managers control', 'their objectives may conflict'] },

{ id: 'objective', t: 'Business objective', d: 'A target or goal that a business works towards.', u: 1, tp: '1.5',
  keys: ['a target the business aims to achieve', 'gives direction and allows performance to be measured'] },
{ id: 'smart-objectives', t: 'SMART objectives', d: 'Objectives that are Specific, Measurable, Achievable, Realistic and Time-bound.', u: 1, tp: '1.5',
  keys: ['Specific, Measurable, Achievable, Realistic, Time-bound'] },
{ id: 'stakeholder', t: 'Stakeholder', d: 'Any person or group with an interest in the activities of a business.', u: 1, tp: '1.5',
  keys: ['a person or group affected by / interested in the business', 'e.g. owners, employees, customers, suppliers, government, community'] },
{ id: 'social-enterprise', t: 'Social enterprise', d: 'A business with social objectives as well as financial ones, which reinvests most of its profits into achieving those objectives.', u: 1, tp: '1.5',
  keys: ['has social or environmental aims as well as profit', 'reinvests profit into its social purpose'] },
{ id: 'triple-bottom-line', t: 'Triple bottom line', d: 'The three objectives of a social enterprise: economic, social and environmental — often called profit, people and planet.', u: 1, tp: '1.5',
  keys: ['economic / profit', 'social / people', 'environmental / planet'] },
{ id: 'profit-maximisation', t: 'Profit maximisation', d: 'The objective of making the largest possible profit.', u: 1, tp: '1.5',
  keys: ['aiming for the highest possible profit'] },

/* ==================== UNIT 2 ==================== */

{ id: 'motivation', t: 'Motivation', d: 'The reason why employees work and the amount of effort they put into their work.', u: 2, tp: '2.1',
  keys: ['the reason employees work', 'the effort / willingness they put in'] },
{ id: 'labour-turnover', t: 'Labour turnover', d: 'The percentage of a business\'s workforce that leaves the business over a period of time, usually one year.', u: 2, tp: '2.1',
  keys: ['percentage of the workforce that leaves', 'over a period, usually a year'],
  note: 'Calculated as (number leaving ÷ average number employed) × 100.' },
{ id: 'productivity', t: 'Productivity', d: 'The output produced per worker, or per unit of another resource, in a given period of time.', u: 2, tp: '2.1',
  keys: ['output per worker / per resource', 'in a given period of time'],
  note: 'Productivity is output per worker. Production is total output. They are not the same.' },
{ id: 'piece-rate', t: 'Piece rate', d: 'A payment system in which workers are paid a fixed amount for each unit they produce.', u: 2, tp: '2.1',
  keys: ['paid per unit produced', 'a fixed amount for each item'] },
{ id: 'time-rate', t: 'Time rate (wage)', d: 'A payment system in which workers are paid a fixed amount for each hour or period of time worked.', u: 2, tp: '2.1',
  keys: ['paid per hour / per period of time worked'] },
{ id: 'salary', t: 'Salary', d: 'A fixed annual amount of pay, usually paid to an employee in monthly instalments.', u: 2, tp: '2.1',
  keys: ['a fixed annual amount', 'paid monthly, not linked to hours or output'] },
{ id: 'commission', t: 'Commission', d: 'A payment made to an employee based on a percentage of the value of the sales they make.', u: 2, tp: '2.1',
  keys: ['a percentage of sales value', 'paid to the employee who made the sale'] },
{ id: 'bonus', t: 'Bonus', d: 'An additional payment made to an employee for reaching a target or for good performance.', u: 2, tp: '2.1',
  keys: ['an extra payment on top of normal pay', 'for reaching a target or performing well'] },
{ id: 'profit-sharing', t: 'Profit sharing', d: 'A payment system in which employees receive a share of the profits the business makes.', u: 2, tp: '2.1',
  keys: ['employees receive a share of company profits'] },
{ id: 'performance-related-pay', t: 'Performance-related pay', d: 'A payment system in which pay is linked to how effectively an employee performs, usually judged through an appraisal.', u: 2, tp: '2.1',
  keys: ['pay linked to how well the employee performs', 'usually assessed by appraisal'] },
{ id: 'fringe-benefits', t: 'Fringe benefits', d: 'Non-cash rewards given to employees in addition to their pay.', u: 2, tp: '2.1',
  keys: ['non-financial / non-cash rewards', 'e.g. company car, health insurance, pension, staff discount'] },
{ id: 'job-rotation', t: 'Job rotation', d: 'When employees are regularly moved between different tasks of a similar level of difficulty.', u: 2, tp: '2.1',
  keys: ['switching between different tasks', 'of a similar level, to reduce boredom'] },
{ id: 'job-enlargement', t: 'Job enlargement', d: 'When extra tasks of a similar level of difficulty are added to an employee\'s job.', u: 2, tp: '2.1',
  keys: ['adding more tasks', 'of the same level of difficulty (horizontal loading)'] },
{ id: 'job-enrichment', t: 'Job enrichment', d: 'When tasks requiring more skill and responsibility are added to an employee\'s job.', u: 2, tp: '2.1',
  keys: ['adding tasks needing more skill and responsibility', 'makes the job more challenging (vertical loading)'],
  note: 'Enlargement adds tasks at the same level; enrichment adds responsibility. A very common mix-up.' },
{ id: 'empowerment', t: 'Empowerment', d: 'When employees are given the authority to make decisions about how they carry out their own work.', u: 2, tp: '2.1',
  keys: ['giving employees authority / control', 'over their own work and decisions'] },
{ id: 'teamworking', t: 'Teamworking', d: 'When employees are organised into groups that are jointly responsible for completing a whole unit of work.', u: 2, tp: '2.1',
  keys: ['employees work in groups', 'jointly responsible for a complete task'] },
{ id: 'taylor', t: 'Taylor (scientific management)', d: 'The theory that employees are motivated mainly by money, so work should be broken into simple timed tasks and workers paid according to output.', u: 2, tp: '2.1',
  keys: ['money is the main motivator', 'jobs broken into simple tasks, paid per unit (piece rate)'] },
{ id: 'maslow', t: 'Maslow (hierarchy of needs)', d: 'The theory that human needs form a hierarchy of five levels, and that a level only motivates until it has been satisfied, at which point the person moves up to the next level.', u: 2, tp: '2.1',
  keys: ['five levels: physical, safety, social, esteem, self-actualisation', 'each level must be satisfied before the next motivates'] },
{ id: 'herzberg', t: 'Herzberg (two-factor theory)', d: 'The theory that hygiene factors such as pay and conditions must be right to prevent dissatisfaction, but only motivators such as achievement, recognition and responsibility create job satisfaction.', u: 2, tp: '2.1',
  keys: ['hygiene factors prevent dissatisfaction but do not motivate', 'motivators create satisfaction'] },

{ id: 'organisational-structure', t: 'Organisational structure', d: 'The way in which a business arranges its employees into levels and departments, showing the roles and responsibilities of each.', u: 2, tp: '2.2',
  keys: ['how employees are arranged into levels and departments', 'shows who is responsible to whom'] },
{ id: 'hierarchy', t: 'Hierarchy', d: 'The levels of authority within a business, from the most senior at the top to the least senior at the bottom.', u: 2, tp: '2.2',
  keys: ['the levels of management / authority', 'ranked from most to least senior'] },
{ id: 'chain-of-command', t: 'Chain of command', d: 'The route along which instructions and authority pass down through the levels of a business.', u: 2, tp: '2.2',
  keys: ['the path instructions pass down', 'from senior management to employees'] },
{ id: 'span-of-control', t: 'Span of control', d: 'The number of subordinates working directly under a manager.', u: 2, tp: '2.2',
  keys: ['the number of subordinates', 'reporting directly to one manager'],
  note: 'A wider span of control means a shorter chain of command, and the reverse.' },
{ id: 'delegation', t: 'Delegation', d: 'When a manager gives a subordinate the authority to carry out a task, while keeping overall responsibility for it.', u: 2, tp: '2.2',
  keys: ['passing authority to a subordinate', 'the manager keeps responsibility'] },
{ id: 'delayering', t: 'Delayering', d: 'The removal of one or more levels of the hierarchy from a business\'s organisational structure.', u: 2, tp: '2.2',
  keys: ['removing a level / levels of hierarchy', 'usually middle management'] },
{ id: 'autocratic', t: 'Autocratic leadership', d: 'A leadership style in which the leader makes all the decisions alone and instructs employees what to do.', u: 2, tp: '2.2',
  keys: ['leader makes all decisions', 'one-way communication, no consultation'] },
{ id: 'democratic', t: 'Democratic leadership', d: 'A leadership style in which the leader discusses decisions with employees and takes their views into account.', u: 2, tp: '2.2',
  keys: ['leader consults employees', 'employee views influence the decision'] },
{ id: 'laissez-faire', t: 'Laissez-faire leadership', d: 'A leadership style in which the leader sets broad objectives and then leaves employees to decide how to achieve them.', u: 2, tp: '2.2',
  keys: ['leader sets broad goals only', 'employees decide how to do the work'] },
{ id: 'trade-union', t: 'Trade union', d: 'An organisation of workers that negotiates with employers on behalf of its members over pay and working conditions.', u: 2, tp: '2.2',
  keys: ['a group / organisation of workers', 'negotiates with employers on members\' behalf'] },
{ id: 'collective-bargaining', t: 'Collective bargaining', d: 'Negotiations between a trade union and an employer over the pay and conditions of all the union\'s members.', u: 2, tp: '2.2',
  keys: ['negotiation between union and employer', 'on behalf of all members together'] },

{ id: 'job-description', t: 'Job description', d: 'A document that outlines the title, duties and responsibilities of a particular job.', u: 2, tp: '2.3',
  keys: ['describes the job', 'title, duties, responsibilities and who it reports to'] },
{ id: 'person-specification', t: 'Person specification', d: 'A document that outlines the qualifications, skills, experience and personal qualities required of the person who will do a job.', u: 2, tp: '2.3',
  keys: ['describes the ideal candidate', 'qualifications, skills, experience, qualities'],
  note: 'Job description describes the job; person specification describes the person.' },
{ id: 'internal-recruitment', t: 'Internal recruitment', d: 'When a vacancy is filled by someone who is already an employee of the business.', u: 2, tp: '2.3',
  keys: ['filling a vacancy from existing employees'] },
{ id: 'external-recruitment', t: 'External recruitment', d: 'When a vacancy is filled by someone who is not already an employee of the business.', u: 2, tp: '2.3',
  keys: ['filling a vacancy from outside the business'] },
{ id: 'induction-training', t: 'Induction training', d: 'Training given to a new employee when they first start work, introducing them to the business and its procedures.', u: 2, tp: '2.3',
  keys: ['given to new employees at the start', 'covers layout, procedures, health and safety, key people'] },
{ id: 'on-the-job-training', t: 'On-the-job training', d: 'Training given to an employee at their place of work, usually by watching and being guided by an experienced worker.', u: 2, tp: '2.3',
  keys: ['training while doing the job at work', 'guided by an experienced employee'] },
{ id: 'off-the-job-training', t: 'Off-the-job training', d: 'Training given to an employee away from their place of work, such as at a college or specialist training centre.', u: 2, tp: '2.3',
  keys: ['training away from the workplace', 'e.g. college course, external trainer'] },
{ id: 'redundancy', t: 'Redundancy', d: 'When an employee loses their job because the job itself is no longer needed by the business.', u: 2, tp: '2.3',
  keys: ['the job is no longer required', 'the employee has done nothing wrong'] },
{ id: 'dismissal', t: 'Dismissal', d: 'When an employee\'s contract is ended by the employer because the employee has broken its terms.', u: 2, tp: '2.3',
  keys: ['contract ended by the employer', 'because of the employee\'s conduct or performance'],
  note: 'Redundancy is about the job disappearing; dismissal is about the employee\'s behaviour.' },
{ id: 'natural-wastage', t: 'Natural wastage', d: 'Reducing the size of the workforce by not replacing employees who leave or retire.', u: 2, tp: '2.3',
  keys: ['not replacing employees who leave or retire', 'avoids redundancy payments'] },
{ id: 'minimum-wage', t: 'Minimum wage', d: 'A legally enforced lowest rate of pay per hour that employers must pay their workers.', u: 2, tp: '2.3',
  keys: ['a legal lowest hourly rate of pay', 'employers must not pay below it'] },
{ id: 'part-time-employee', t: 'Part-time employee', d: 'An employee who works fewer hours per week than a full-time employee.', u: 2, tp: '2.3',
  keys: ['works fewer hours than full-time staff', 'gives the business flexibility'] },

{ id: 'communication', t: 'Communication', d: 'The transfer of a message from a sender to a receiver, which is only effective when the message is understood.', u: 2, tp: '2.4',
  keys: ['a message passed from sender to receiver', 'must be received and understood'] },
{ id: 'feedback', t: 'Feedback', d: 'The response of the receiver, which shows the sender that the message has been received and understood.', u: 2, tp: '2.4',
  keys: ['the receiver\'s response', 'confirms the message was understood'] },
{ id: 'internal-communication', t: 'Internal communication', d: 'Communication between people within the same business.', u: 2, tp: '2.4',
  keys: ['between members of the same organisation'] },
{ id: 'external-communication', t: 'External communication', d: 'Communication between a business and individuals or organisations outside it.', u: 2, tp: '2.4',
  keys: ['between the business and outsiders', 'e.g. customers, suppliers, banks, government'] },
{ id: 'one-way-communication', t: 'One-way communication', d: 'Communication in which the receiver has no opportunity to respond to the message.', u: 2, tp: '2.4',
  keys: ['no opportunity for the receiver to reply', 'no feedback, e.g. a notice'] },
{ id: 'two-way-communication', t: 'Two-way communication', d: 'Communication in which the receiver is able to respond to the message and give feedback.', u: 2, tp: '2.4',
  keys: ['the receiver can respond', 'feedback is possible, e.g. a meeting'] },
{ id: 'communication-barrier', t: 'Communication barrier', d: 'Anything that prevents a message being received or correctly understood.', u: 2, tp: '2.4',
  keys: ['something that stops the message getting through or being understood', 'e.g. jargon, noise, wrong medium, long chain of command'] },

/* ==================== UNIT 3 ==================== */

{ id: 'marketing', t: 'Marketing', d: 'The management process of identifying, anticipating and satisfying customer requirements profitably.', u: 3, tp: '3.1',
  keys: ['identifying and satisfying customer needs', 'doing so profitably'] },
{ id: 'mass-marketing', t: 'Mass marketing', d: 'When a business sells the same product to the whole market rather than to a particular segment of it.', u: 3, tp: '3.1',
  keys: ['one product aimed at the whole market', 'not aimed at a specific segment'] },
{ id: 'niche-marketing', t: 'Niche marketing', d: 'When a business aims a product at a small, specific segment of a larger market.', u: 3, tp: '3.1',
  keys: ['aimed at a small, specific segment', 'of a larger market'] },
{ id: 'market-segmentation', t: 'Market segmentation', d: 'The division of a market into groups of customers who share similar characteristics.', u: 3, tp: '3.1',
  keys: ['dividing a market into groups', 'of customers with similar characteristics'],
  note: 'Segmentation is the method; niche marketing is one strategy that uses it.' },
{ id: 'consumer', t: 'Consumer', d: 'The person who uses a product.', u: 3, tp: '3.1',
  keys: ['the user of the product', 'not always the person who bought it'] },
{ id: 'brand', t: 'Brand', d: 'A name, symbol or design that identifies a product and distinguishes it from those of competitors.', u: 3, tp: '3.1',
  keys: ['a name, logo or design identifying the product', 'distinguishes it from competitors'] },

{ id: 'market-research', t: 'Market research', d: 'The collection, recording and analysis of data about customers, competitors and the market.', u: 3, tp: '3.2',
  keys: ['collecting and analysing data', 'about customers, competitors and the market'],
  note: 'Market research reduces risk. It does not remove or guarantee anything.' },
{ id: 'primary-research', t: 'Primary (field) research', d: 'The collection of original data first hand for a specific purpose.', u: 3, tp: '3.2',
  keys: ['new / original data', 'collected first hand for a specific purpose'] },
{ id: 'secondary-research', t: 'Secondary (desk) research', d: 'The use of data that already exists, which was collected by someone else for a different purpose.', u: 3, tp: '3.2',
  keys: ['data that already exists', 'collected by someone else for another purpose'] },
{ id: 'questionnaire', t: 'Questionnaire', d: 'A set of questions used to collect data from a sample of respondents.', u: 3, tp: '3.2',
  keys: ['a set of written questions', 'answered by a sample of people'] },
{ id: 'focus-group', t: 'Focus group', d: 'A small group of consumers who are asked to discuss their opinions of a product or idea with a researcher.', u: 3, tp: '3.2',
  keys: ['a small group of consumers', 'discuss opinions in detail with a researcher'] },
{ id: 'sample', t: 'Sample', d: 'The group of people questioned in market research, selected to represent the whole target market.', u: 3, tp: '3.2',
  keys: ['the group questioned', 'chosen to represent the whole target market'] },
{ id: 'quantitative-data', t: 'Quantitative data', d: 'Data that can be measured and expressed as numbers.', u: 3, tp: '3.2',
  keys: ['numerical / measurable data', 'easy to compare and analyse'] },
{ id: 'qualitative-data', t: 'Qualitative data', d: 'Data about the opinions, attitudes and reasons behind consumer behaviour.', u: 3, tp: '3.2',
  keys: ['opinions, attitudes and reasons', 'explains why, but harder to analyse'] },
{ id: 'test-marketing', t: 'Test marketing', d: 'Selling a new product in a limited area before deciding whether to launch it fully.', u: 3, tp: '3.2',
  keys: ['selling in a limited area first', 'before a full launch, to gather real sales data'] },

{ id: 'marketing-mix', t: 'Marketing mix', d: 'The combination of product, price, place and promotion used to market a product.', u: 3, tp: '3.3',
  keys: ['product, price, place, promotion'],
  note: 'The four Ps must be consistent with each other and with the target market.' },
{ id: 'product-life-cycle', t: 'Product life cycle', d: 'The stages a product passes through from its development to its withdrawal from the market.', u: 3, tp: '3.3',
  keys: ['the stages a product passes through', 'development, introduction, growth, maturity, decline'] },
{ id: 'extension-strategy', t: 'Extension strategy', d: 'A method used to lengthen the life of a product and delay the decline stage.', u: 3, tp: '3.3',
  keys: ['used at maturity or early decline', 'e.g. new versions, new packaging, new markets, price cut'] },
{ id: 'packaging', t: 'Packaging', d: 'The material used to protect, contain, promote and provide information about a product.', u: 3, tp: '3.3',
  keys: ['protects and contains the product', 'promotes it and informs the customer'] },
{ id: 'cost-plus-pricing', t: 'Cost-plus pricing', d: 'Setting a price by calculating the cost of producing one unit and adding a percentage mark-up.', u: 3, tp: '3.3',
  keys: ['unit cost plus a percentage mark-up'],
  note: 'Ignores what competitors charge and what customers will pay.' },
{ id: 'penetration-pricing', t: 'Penetration pricing', d: 'Setting a low price when a product is first launched in order to gain customers and market share quickly.', u: 3, tp: '3.3',
  keys: ['a low price at launch', 'to win market share quickly'] },
{ id: 'price-skimming', t: 'Price skimming', d: 'Setting a high price for a new product at launch, then lowering it once competitors enter the market.', u: 3, tp: '3.3',
  keys: ['a high price at launch', 'lowered later as competition appears'],
  note: 'Skimming is high then low; penetration is low then higher. Do not swap them.' },
{ id: 'competitive-pricing', t: 'Competitive pricing', d: 'Setting a price at or just below the prices charged by competitors.', u: 3, tp: '3.3',
  keys: ['price set in line with or below rivals'] },
{ id: 'promotional-pricing', t: 'Promotional pricing', d: 'Temporarily reducing the price of a product to boost sales or clear stock.', u: 3, tp: '3.3',
  keys: ['a temporary price reduction', 'to boost sales or clear old stock'] },
{ id: 'psychological-pricing', t: 'Psychological pricing', d: 'Setting a price to influence how customers perceive the product, such as pricing just below a round number.', u: 3, tp: '3.3',
  keys: ['a price set to affect customer perception', 'e.g. $9.99, or a high price to signal quality'] },
{ id: 'price-elasticity-of-demand', t: 'Price elasticity of demand', d: 'A measure of the responsiveness of the quantity demanded to a change in price.', u: 3, tp: '3.3',
  keys: ['how much quantity demanded responds to a price change', '% change in quantity ÷ % change in price'],
  note: 'Above 1 is elastic (cut price to raise revenue); below 1 is inelastic (raise price to raise revenue).' },
{ id: 'channel-of-distribution', t: 'Channel of distribution', d: 'The route taken by a product from the producer to the final consumer.', u: 3, tp: '3.3',
  keys: ['the route from producer to consumer', 'may include intermediaries'] },
{ id: 'wholesaler', t: 'Wholesaler', d: 'A business that buys goods in bulk from producers, stores them and sells them in smaller quantities to retailers.', u: 3, tp: '3.3',
  keys: ['buys in bulk from producers', 'breaks bulk and sells on to retailers'] },
{ id: 'retailer', t: 'Retailer', d: 'A business that sells goods directly to the final consumer.', u: 3, tp: '3.3',
  keys: ['sells directly to the final consumer'] },
{ id: 'informative-advertising', t: 'Informative advertising', d: 'Advertising that gives customers factual information about a product.', u: 3, tp: '3.3',
  keys: ['provides facts about the product', 'e.g. features, price, where to buy'] },
{ id: 'persuasive-advertising', t: 'Persuasive advertising', d: 'Advertising that aims to convince customers that they want or need a product.', u: 3, tp: '3.3',
  keys: ['aims to convince customers to buy', 'often uses emotion or image rather than fact'] },
{ id: 'above-the-line', t: 'Above-the-line promotion', d: 'Promotion carried out through independent media such as television, radio, newspapers and billboards.', u: 3, tp: '3.3',
  keys: ['paid promotion through independent media', 'reaches a wide audience'] },
{ id: 'below-the-line', t: 'Below-the-line promotion', d: 'Promotion that the business controls directly rather than paying independent media.', u: 3, tp: '3.3',
  keys: ['controlled directly by the business', 'e.g. special offers, free samples, loyalty cards, point-of-sale displays'] },
{ id: 'e-commerce', t: 'E-commerce', d: 'The buying and selling of goods and services over the internet.', u: 3, tp: '3.3',
  keys: ['buying and selling online / over the internet'] },
{ id: 'viral-marketing', t: 'Viral marketing', d: 'The use of social media and networks so that consumers pass the marketing message on to each other.', u: 3, tp: '3.3',
  keys: ['users share the message themselves', 'spreads rapidly at low cost'] },

{ id: 'marketing-strategy', t: 'Marketing strategy', d: 'A plan that uses the marketing mix to achieve a business\'s marketing objectives.', u: 3, tp: '3.4',
  keys: ['a plan to achieve marketing objectives', 'uses the marketing mix and a target market'] },
{ id: 'misleading-advertising', t: 'Misleading advertising', d: 'Advertising that gives customers a false or exaggerated impression of a product.', u: 3, tp: '3.4',
  keys: ['false or exaggerated claims about a product', 'illegal in most countries'] },
{ id: 'consumer-protection', t: 'Consumer protection', d: 'Laws that protect customers from unsafe products, false descriptions and unfair trading.', u: 3, tp: '3.4',
  keys: ['laws protecting customers', 'from unsafe goods, false descriptions and misleading advertising'] },
{ id: 'exporting', t: 'Exporting', d: 'Selling goods or services produced in one country to customers in another country.', u: 3, tp: '3.4',
  keys: ['selling to customers abroad', 'goods produced in the home country'] },

/* ==================== UNIT 4 ==================== */

{ id: 'production', t: 'Production', d: 'The process of converting inputs such as land, labour and capital into outputs of goods and services.', u: 4, tp: '4.1',
  keys: ['converting inputs into outputs', 'of goods and services'] },
{ id: 'job-production', t: 'Job production', d: 'The production of a single item at a time, made to the customer\'s specific requirements.', u: 4, tp: '4.1',
  keys: ['one unique item at a time', 'made to the customer\'s own requirements'] },
{ id: 'batch-production', t: 'Batch production', d: 'The production of a group of identical items together, with each stage completed for the whole group before the next stage begins.', u: 4, tp: '4.1',
  keys: ['groups of identical items made together', 'each stage completed for the whole batch first'] },
{ id: 'flow-production', t: 'Flow (mass) production', d: 'The continuous production of large quantities of an identical, standardised product.', u: 4, tp: '4.1',
  keys: ['large quantities of identical products', 'produced continuously along a production line'] },
{ id: 'lean-production', t: 'Lean production', d: 'Producing goods and services with the minimum possible waste of resources.', u: 4, tp: '4.1',
  keys: ['minimising waste', 'of time, materials, labour, space and energy'] },
{ id: 'just-in-time', t: 'Just-in-time (JIT)', d: 'An inventory method in which materials and components arrive exactly when they are needed, so that almost no inventory is held.', u: 4, tp: '4.1',
  keys: ['materials arrive exactly when needed', 'little or no inventory held'],
  note: 'JIT depends completely on reliable suppliers — there is no buffer stock to fall back on.' },
{ id: 'kaizen', t: 'Kaizen', d: 'Continuous improvement, in which all employees regularly suggest small improvements to the way work is done.', u: 4, tp: '4.1',
  keys: ['continuous improvement', 'small changes suggested by all employees'] },
{ id: 'cell-production', t: 'Cell production', d: 'When production is divided into self-contained teams, each responsible for completing a whole unit of work.', u: 4, tp: '4.1',
  keys: ['production split into self-contained teams', 'each completes a whole unit of work'] },
{ id: 'buffer-stock', t: 'Buffer stock', d: 'A minimum level of inventory held in reserve in case of unexpected demand or supply problems.', u: 4, tp: '4.1',
  keys: ['minimum inventory held in reserve', 'covers unexpected demand or delivery delays'] },
{ id: 'automation', t: 'Automation', d: 'The use of machines and computers to carry out tasks previously performed by workers.', u: 4, tp: '4.1',
  keys: ['machines / computers replacing human labour'] },
{ id: 'cad-cam', t: 'CAD / CAM', d: 'Computer-aided design, which is designing products using a computer, and computer-aided manufacture, which is using computers to control the machines that make them.', u: 4, tp: '4.1',
  keys: ['CAD: designing products on a computer', 'CAM: computers controlling production machinery'] },

{ id: 'fixed-costs', t: 'Fixed costs', d: 'Costs that do not change with the level of output in the short run.', u: 4, tp: '4.2',
  keys: ['do not vary with output', 'e.g. rent, insurance, managers\' salaries'],
  note: 'They must still be paid when output is zero.' },
{ id: 'variable-costs', t: 'Variable costs', d: 'Costs that change directly with the level of output.', u: 4, tp: '4.2',
  keys: ['change directly with output', 'e.g. raw materials, components, piece-rate wages'] },
{ id: 'total-costs', t: 'Total costs', d: 'The fixed costs plus the total variable costs of producing a given level of output.', u: 4, tp: '4.2',
  keys: ['fixed costs plus total variable costs'] },
{ id: 'average-cost', t: 'Average cost (unit cost)', d: 'The cost of producing one unit of output, calculated as total costs divided by output.', u: 4, tp: '4.2',
  keys: ['cost per unit', 'total costs ÷ output'] },
{ id: 'revenue', t: 'Revenue', d: 'The income a business receives from selling its products, calculated as selling price multiplied by quantity sold.', u: 4, tp: '4.2',
  keys: ['income from sales', 'price × quantity sold'] },
{ id: 'contribution', t: 'Contribution per unit', d: 'The selling price of one unit minus its variable cost, which contributes towards paying the fixed costs and then towards profit.', u: 4, tp: '4.2',
  keys: ['selling price minus variable cost per unit', 'contributes to fixed costs then profit'] },
{ id: 'break-even', t: 'Break-even point', d: 'The level of output at which total revenue equals total costs, so the business makes neither a profit nor a loss.', u: 4, tp: '4.2',
  keys: ['total revenue equals total costs', 'neither profit nor loss'],
  note: 'Calculated as fixed costs ÷ contribution per unit. Never divide by the selling price.' },
{ id: 'margin-of-safety', t: 'Margin of safety', d: 'The amount by which current output exceeds the break-even output.', u: 4, tp: '4.2',
  keys: ['current output minus break-even output', 'how far sales can fall before a loss is made'] },
{ id: 'economies-of-scale', t: 'Economies of scale', d: 'The factors that cause the average cost per unit to fall as a business increases its scale of production.', u: 4, tp: '4.2',
  keys: ['average cost per unit falls', 'as output / scale increases'],
  note: 'Types: purchasing, technical, financial, marketing, managerial, risk-bearing.' },
{ id: 'diseconomies-of-scale', t: 'Diseconomies of scale', d: 'The factors that cause the average cost per unit to rise when a business becomes too large.', u: 4, tp: '4.2',
  keys: ['average cost per unit rises', 'because the business has grown too large'],
  note: 'Causes: poor communication, weak coordination, lack of employee commitment.' },

{ id: 'quality', t: 'Quality', d: 'Producing a good or service that meets customers\' expectations and is fit for purpose.', u: 4, tp: '4.3',
  keys: ['meets customer expectations', 'fit for purpose, reliable and safe'] },
{ id: 'quality-control', t: 'Quality control', d: 'Checking products at the end of the production process in order to find and remove faulty items.', u: 4, tp: '4.3',
  keys: ['inspecting at the end of production', 'finds faults after they have been made'] },
{ id: 'quality-assurance', t: 'Quality assurance', d: 'Checking quality at every stage of the production process so that faults are prevented rather than detected.', u: 4, tp: '4.3',
  keys: ['standards checked throughout production', 'prevents faults; every worker is responsible'],
  note: 'Control finds faults; assurance prevents them. Use those two verbs.' },
{ id: 'tqm', t: 'Total quality management (TQM)', d: 'A quality assurance approach in which every employee is responsible for quality at every stage, aiming for zero defects.', u: 4, tp: '4.3',
  keys: ['quality is every employee\'s responsibility', 'at every stage, aiming for zero defects'] },

{ id: 'location', t: 'Location decision', d: 'The choice a business makes about where to site its operations.', u: 4, tp: '4.4',
  keys: ['where to site the business', 'based on costs, market, labour, transport and legal factors'] },
{ id: 'relocation', t: 'Relocation', d: 'When a business moves its operations from one site to another.', u: 4, tp: '4.4',
  keys: ['moving from one site to another'] },
{ id: 'footfall', t: 'Footfall', d: 'The number of potential customers passing a retail site.', u: 4, tp: '4.4',
  keys: ['the number of people passing a shop', 'a key factor for retail location'] },
{ id: 'infrastructure', t: 'Infrastructure', d: 'The basic facilities a business needs to operate, such as transport links, power, water and communications.', u: 4, tp: '4.4',
  keys: ['basic supporting facilities', 'roads, ports, power, water, communications'] },
{ id: 'government-incentives', t: 'Government incentives', d: 'Financial support offered by a government to encourage businesses to locate in a particular area.', u: 4, tp: '4.4',
  keys: ['grants, subsidies, tax breaks or cheap rent', 'to attract businesses to an area'] },
{ id: 'planning-permission', t: 'Planning permission', d: 'Legal approval from local government that a business must obtain before building or changing the use of premises.', u: 4, tp: '4.4',
  keys: ['legal approval to build or change premises', 'granted by local government'] },

/* ==================== UNIT 5 ==================== */

{ id: 'retained-profit', t: 'Retained profit', d: 'The profit kept in a business after tax and dividends have been paid, and reinvested in it.', u: 5, tp: '5.1',
  keys: ['profit kept in the business', 'after tax and dividends, and reinvested'],
  note: 'An internal, permanent source of finance with no interest and no loss of control.' },
{ id: 'overdraft', t: 'Bank overdraft', d: 'An arrangement with a bank allowing a business to withdraw more money than it has in its account, up to an agreed limit.', u: 5, tp: '5.1',
  keys: ['withdrawing more than is in the account', 'up to an agreed limit; short term'] },
{ id: 'trade-credit', t: 'Trade credit', d: 'When a supplier allows a business to buy goods and pay for them at a later date.', u: 5, tp: '5.1',
  keys: ['buy now, pay later', 'usually 30 to 90 days, interest free'] },
{ id: 'bank-loan', t: 'Bank loan', d: 'A fixed sum of money borrowed from a bank and repaid with interest in instalments over an agreed period.', u: 5, tp: '5.1',
  keys: ['a fixed sum borrowed', 'repaid with interest over an agreed period'] },
{ id: 'share-issue', t: 'Share issue', d: 'Raising permanent capital by selling new shares in a limited company.', u: 5, tp: '5.1',
  keys: ['selling new shares to raise capital', 'never repaid, but dilutes ownership'] },
{ id: 'debenture', t: 'Debenture', d: 'A long-term loan certificate issued by a company, repayable on a fixed future date with interest.', u: 5, tp: '5.1',
  keys: ['a long-term loan to the company', 'repaid on a fixed date with interest'] },
{ id: 'hire-purchase', t: 'Hire purchase', d: 'Buying an asset by paying for it in instalments, with ownership passing to the business at the final payment.', u: 5, tp: '5.1',
  keys: ['paying in instalments', 'ownership passes at the final payment'] },
{ id: 'leasing', t: 'Leasing', d: 'Renting an asset from another business rather than buying it.', u: 5, tp: '5.1',
  keys: ['renting rather than buying', 'the business never owns the asset'] },
{ id: 'venture-capital', t: 'Venture capital', d: 'Finance provided by specialist investors to businesses considered too risky for normal bank lending, in return for a share of the business.', u: 5, tp: '5.1',
  keys: ['investment in high-risk businesses', 'in exchange for a share of ownership'] },
{ id: 'collateral', t: 'Collateral (security)', d: 'An asset pledged to a lender, which the lender may take and sell if the loan is not repaid.', u: 5, tp: '5.1',
  keys: ['an asset offered as security', 'the lender can sell it if the loan is not repaid'] },
{ id: 'crowdfunding', t: 'Crowdfunding', d: 'Raising finance by collecting small amounts of money from a large number of people, usually online.', u: 5, tp: '5.1',
  keys: ['small amounts from many people', 'usually through an online platform'] },
{ id: 'microfinance', t: 'Microfinance', d: 'The provision of very small loans to entrepreneurs who cannot access normal banking services.', u: 5, tp: '5.1',
  keys: ['very small loans', 'to people without access to normal banks'] },
{ id: 'debt-factoring', t: 'Debt factoring', d: 'Selling unpaid customer invoices to a finance company, which pays most of their value immediately.', u: 5, tp: '5.1',
  keys: ['selling invoices / trade receivables', 'for immediate cash, less a percentage'] },

{ id: 'cash-flow', t: 'Cash flow', d: 'The movement of money into and out of a business over a period of time.', u: 5, tp: '5.2',
  keys: ['money flowing in and out', 'over a period of time'] },
{ id: 'cash-inflow', t: 'Cash inflow', d: 'Money flowing into a business.', u: 5, tp: '5.2',
  keys: ['money coming in', 'e.g. cash sales, payments from debtors, loans received'] },
{ id: 'cash-outflow', t: 'Cash outflow', d: 'Money flowing out of a business.', u: 5, tp: '5.2',
  keys: ['money going out', 'e.g. materials, wages, rent, loan repayments'] },
{ id: 'net-cash-flow', t: 'Net cash flow', d: 'The difference between total cash inflows and total cash outflows over a period of time.', u: 5, tp: '5.2',
  keys: ['total inflows minus total outflows'] },
{ id: 'opening-balance', t: 'Opening balance', d: 'The amount of cash a business holds at the beginning of a period.', u: 5, tp: '5.2',
  keys: ['cash held at the start of the period', 'equals the previous period\'s closing balance'] },
{ id: 'closing-balance', t: 'Closing balance', d: 'The amount of cash a business holds at the end of a period, calculated as the opening balance plus net cash flow.', u: 5, tp: '5.2',
  keys: ['cash held at the end of the period', 'opening balance plus net cash flow'] },
{ id: 'cash-flow-forecast', t: 'Cash-flow forecast', d: 'An estimate of the future cash inflows and outflows of a business, usually month by month.', u: 5, tp: '5.2',
  keys: ['a prediction of future inflows and outflows', 'shows when cash shortages will occur'] },
{ id: 'working-capital', t: 'Working capital', d: 'The finance available to a business for its day-to-day running, calculated as current assets minus current liabilities.', u: 5, tp: '5.2',
  keys: ['finance for day-to-day running', 'current assets minus current liabilities'] },
{ id: 'liquidity', t: 'Liquidity', d: 'The ability of a business to pay its short-term debts as they fall due.', u: 5, tp: '5.2',
  keys: ['ability to pay short-term debts', 'as they become due'] },
{ id: 'insolvency', t: 'Insolvency', d: 'When a business is unable to pay its debts as they fall due.', u: 5, tp: '5.2',
  keys: ['unable to pay debts when due', 'can happen even to a profitable business'] },

{ id: 'income-statement', t: 'Income statement', d: 'A financial statement showing the revenue, costs and profit of a business over a period of time.', u: 5, tp: '5.3',
  keys: ['shows revenue, costs and profit', 'over a period, usually one year'] },
{ id: 'cost-of-sales', t: 'Cost of sales', d: 'The direct cost of producing the goods that were actually sold during a period.', u: 5, tp: '5.3',
  keys: ['direct cost of goods sold', 'e.g. materials and direct labour'] },
{ id: 'gross-profit', t: 'Gross profit', d: 'Revenue minus the cost of sales.', u: 5, tp: '5.3',
  keys: ['revenue minus cost of sales', 'before expenses / overheads are deducted'] },
{ id: 'net-profit', t: 'Profit (net profit)', d: 'Gross profit minus the expenses of running the business.', u: 5, tp: '5.3',
  keys: ['gross profit minus expenses', 'what the business has earned from trading'] },
{ id: 'expenses', t: 'Expenses (overheads)', d: 'The indirect costs of running a business, which are not directly linked to producing each unit.', u: 5, tp: '5.3',
  keys: ['indirect running costs', 'e.g. rent, salaries, marketing, insurance'] },
{ id: 'depreciation', t: 'Depreciation', d: 'The fall in the value of a non-current asset over time, recorded as an expense.', u: 5, tp: '5.3',
  keys: ['the fall in value of a non-current asset', 'spread over its useful life as an expense'] },

{ id: 'statement-of-financial-position', t: 'Statement of financial position', d: 'A financial statement showing the assets, liabilities and capital of a business at a particular point in time.', u: 5, tp: '5.4',
  keys: ['shows assets, liabilities and equity', 'at one point in time'],
  note: 'A snapshot on one date. The income statement covers a period. It does not show profit.' },
{ id: 'non-current-asset', t: 'Non-current (fixed) asset', d: 'An asset owned by a business that it expects to keep and use for more than one year.', u: 5, tp: '5.4',
  keys: ['owned and used for more than one year', 'e.g. land, buildings, machinery, vehicles'] },
{ id: 'current-asset', t: 'Current asset', d: 'An asset that a business expects to convert into cash within one year.', u: 5, tp: '5.4',
  keys: ['expected to become cash within a year', 'inventory, trade receivables and cash'] },
{ id: 'current-liability', t: 'Current liability', d: 'A debt that a business must repay within one year.', u: 5, tp: '5.4',
  keys: ['repayable within one year', 'e.g. trade payables, overdraft, tax owed'] },
{ id: 'non-current-liability', t: 'Non-current (long-term) liability', d: 'A debt that a business does not have to repay for more than one year.', u: 5, tp: '5.4',
  keys: ['repayable in more than one year', 'e.g. bank loan, mortgage, debentures'] },
{ id: 'inventory', t: 'Inventory (stock)', d: 'The raw materials, work in progress and finished goods held by a business.', u: 5, tp: '5.4',
  keys: ['raw materials, work in progress and finished goods', 'a current asset'] },
{ id: 'trade-receivables', t: 'Trade receivables (debtors)', d: 'The money owed to a business by customers who have bought goods on credit.', u: 5, tp: '5.4',
  keys: ['money owed to the business by customers', 'a current asset'] },
{ id: 'trade-payables', t: 'Trade payables (creditors)', d: 'The money a business owes to suppliers for goods bought on credit.', u: 5, tp: '5.4',
  keys: ['money the business owes to suppliers', 'a current liability'] },
{ id: 'shareholders-equity', t: 'Shareholders\' equity', d: 'The total value of the owners\' stake in a company, made up of share capital plus retained earnings.', u: 5, tp: '5.4',
  keys: ['the owners\' stake in the business', 'share capital plus retained earnings'] },

{ id: 'gross-profit-margin', t: 'Gross profit margin', d: 'A profitability ratio showing gross profit as a percentage of revenue.', u: 5, tp: '5.5',
  keys: ['(gross profit ÷ revenue) × 100', 'measures control of direct costs and pricing'] },
{ id: 'profit-margin', t: 'Profit margin', d: 'A profitability ratio showing profit as a percentage of revenue.', u: 5, tp: '5.5',
  keys: ['(profit ÷ revenue) × 100', 'measures control of direct costs and overheads'] },
{ id: 'roce', t: 'Return on capital employed (ROCE)', d: 'A profitability ratio showing profit as a percentage of the capital employed in the business.', u: 5, tp: '5.5',
  keys: ['(profit ÷ capital employed) × 100', 'measures the return generated on money invested'] },
{ id: 'current-ratio', t: 'Current ratio', d: 'A liquidity ratio comparing current assets with current liabilities.', u: 5, tp: '5.5',
  keys: ['current assets ÷ current liabilities', 'about 1.5:1 to 2:1 is usually considered safe'],
  note: 'Expressed as a ratio, e.g. 1.6 : 1 — never as a percentage.' },
{ id: 'acid-test-ratio', t: 'Acid test ratio', d: 'A liquidity ratio comparing current assets excluding inventory with current liabilities.', u: 5, tp: '5.5',
  keys: ['(current assets − inventory) ÷ current liabilities', 'about 1:1 is usually considered safe'],
  note: 'Excludes inventory because stock may not sell quickly.' },
{ id: 'ratio-analysis', t: 'Ratio analysis', d: 'The use of figures from a business\'s accounts to calculate ratios that measure and compare its performance.', u: 5, tp: '5.5',
  keys: ['using accounting figures to calculate ratios', 'to measure performance and compare over time'] },
{ id: 'window-dressing', t: 'Window dressing', d: 'Presenting a business\'s accounts in a way that makes its performance look better than it really is.', u: 5, tp: '5.5',
  keys: ['making accounts look better than reality', 'a limitation of using accounts to judge performance'] },

/* ==================== UNIT 6 ==================== */

{ id: 'inflation', t: 'Inflation', d: 'A sustained increase in the general level of prices in an economy.', u: 6, tp: '6.1',
  keys: ['a general rise in prices', 'sustained over time; money loses value'] },
{ id: 'unemployment', t: 'Unemployment', d: 'When people who are willing and able to work are unable to find a job.', u: 6, tp: '6.1',
  keys: ['willing and able to work', 'but unable to find a job'] },
{ id: 'economic-growth', t: 'Economic growth', d: 'An increase in a country\'s real gross domestic product over time.', u: 6, tp: '6.1',
  keys: ['an increase in real GDP', 'over a period of time'] },
{ id: 'gdp', t: 'Gross domestic product (GDP)', d: 'The total value of goods and services produced in a country in one year.', u: 6, tp: '6.1',
  keys: ['total value of output', 'produced in a country in a year'] },
{ id: 'recession', t: 'Recession', d: 'A period during which a country\'s gross domestic product falls, usually for two consecutive quarters or more.', u: 6, tp: '6.1',
  keys: ['falling GDP', 'usually for two consecutive quarters or more'] },
{ id: 'business-cycle', t: 'Business (trade) cycle', d: 'The pattern of growth, boom, recession, slump and recovery that a country\'s output repeatedly passes through.', u: 6, tp: '6.1',
  keys: ['the repeating pattern of GDP over time', 'growth, boom, recession, slump, recovery'] },
{ id: 'fiscal-policy', t: 'Fiscal policy', d: 'Government decisions about taxation and government spending used to influence the economy.', u: 6, tp: '6.1',
  keys: ['taxation', 'government spending'] },
{ id: 'monetary-policy', t: 'Monetary policy', d: 'Government or central bank decisions about interest rates and the money supply used to influence the economy.', u: 6, tp: '6.1',
  keys: ['interest rates', 'the money supply'],
  note: 'Fiscal = tax and spending. Monetary = interest rates. Do not confuse them.' },
{ id: 'direct-tax', t: 'Direct tax', d: 'A tax on the income or profit of individuals and businesses, paid directly to the government by the person or business that earned it.', u: 6, tp: '6.1',
  keys: ['a tax on income or profit', 'e.g. income tax, corporation tax'] },
{ id: 'indirect-tax', t: 'Indirect tax', d: 'A tax on spending, added to the price of goods and services.', u: 6, tp: '6.1',
  keys: ['a tax on spending', 'e.g. VAT, sales tax, excise duty'] },
{ id: 'interest-rate', t: 'Interest rate', d: 'The cost of borrowing money and the reward for saving it, expressed as a percentage.', u: 6, tp: '6.1',
  keys: ['the cost of borrowing', 'the reward for saving'] },
{ id: 'disposable-income', t: 'Disposable income', d: 'The income a consumer has left to spend or save after income tax has been deducted.', u: 6, tp: '6.1',
  keys: ['income remaining after tax', 'available to spend or save'] },
{ id: 'supply-side-policy', t: 'Supply-side policy', d: 'Government policies that aim to increase the productive capacity and efficiency of an economy.', u: 6, tp: '6.1',
  keys: ['increases the economy\'s capacity to produce', 'e.g. training, lower business taxes, better infrastructure'] },

{ id: 'sustainable-development', t: 'Sustainable development', d: 'Development that meets the needs of the present without reducing the ability of future generations to meet their own needs.', u: 6, tp: '6.2',
  keys: ['meets present needs', 'without harming future generations\' ability to meet theirs'] },
{ id: 'externalities', t: 'Externalities', d: 'The costs or benefits of business activity that fall on people other than the business itself.', u: 6, tp: '6.2',
  keys: ['effects on third parties', 'not paid for by the business, e.g. pollution'] },
{ id: 'social-costs', t: 'Social costs', d: 'The total costs of business activity to society, made up of the private costs paid by the business plus the external costs borne by others.', u: 6, tp: '6.2',
  keys: ['private costs plus external costs', 'the full cost to society'] },
{ id: 'business-ethics', t: 'Business ethics', d: 'The moral principles and values that guide the decisions a business makes.', u: 6, tp: '6.2',
  keys: ['moral principles guiding decisions', 'doing what is right, not only what is legal'],
  note: 'Something can be legal and still unethical.' },
{ id: 'pressure-group', t: 'Pressure group', d: 'An organisation of people who campaign to change the decisions and behaviour of businesses or governments.', u: 6, tp: '6.2',
  keys: ['a group campaigning for change', 'aims to influence business or government behaviour'] },
{ id: 'recycling', t: 'Recycling', d: 'The reprocessing of used materials so that they can be made into new products.', u: 6, tp: '6.2',
  keys: ['reprocessing used materials into new products', 'reduces waste and use of resources'] },
{ id: 'carbon-footprint', t: 'Carbon footprint', d: 'The total amount of greenhouse gases produced by the activities of a business or the making of a product.', u: 6, tp: '6.2',
  keys: ['total greenhouse gases produced', 'by a business or product'] },

{ id: 'globalisation', t: 'Globalisation', d: 'The increasing integration of the world\'s economies, so that businesses trade, produce and invest across national borders.', u: 6, tp: '6.3',
  keys: ['growing integration of world economies', 'businesses trade and produce across borders'] },
{ id: 'tariff', t: 'Tariff', d: 'A tax placed on imported goods.', u: 6, tp: '6.3',
  keys: ['a tax on imports', 'raises their price to protect domestic producers'] },
{ id: 'quota', t: 'Quota', d: 'A physical limit on the quantity of a good that may be imported into a country.', u: 6, tp: '6.3',
  keys: ['a limit on the quantity of imports', 'a physical limit, not a tax'],
  note: 'A tariff is a tax; a quota is a quantity limit.' },
{ id: 'free-trade', t: 'Free trade', d: 'International trade that takes place without tariffs, quotas or other barriers.', u: 6, tp: '6.3',
  keys: ['trade without barriers', 'no tariffs or quotas'] },
{ id: 'trade-bloc', t: 'Trade bloc', d: 'A group of countries that have agreed to remove trade barriers between themselves.', u: 6, tp: '6.3',
  keys: ['a group of countries', 'that have removed trade barriers between them'] },
{ id: 'multinational-company', t: 'Multinational company (MNC)', d: 'A business that has its headquarters in one country but operates production or other operations in two or more countries.', u: 6, tp: '6.3',
  keys: ['headquarters in one country', 'operates / produces in two or more countries'],
  note: 'Exporting alone does not make a business multinational — it must operate abroad.' },
{ id: 'exchange-rate', t: 'Exchange rate', d: 'The price of one country\'s currency expressed in terms of another currency.', u: 6, tp: '6.3',
  keys: ['the value of one currency in terms of another'] },
{ id: 'currency-appreciation', t: 'Appreciation of a currency', d: 'An increase in the value of a currency compared with other currencies.', u: 6, tp: '6.3',
  keys: ['a rise in the value of the currency', 'imports become cheaper, exports dearer'],
  note: 'SPICED: Strong Pound = Imports Cheap, Exports Dear.' },
{ id: 'currency-depreciation', t: 'Depreciation of a currency', d: 'A fall in the value of a currency compared with other currencies.', u: 6, tp: '6.3',
  keys: ['a fall in the value of the currency', 'imports become dearer, exports cheaper'] },
{ id: 'exports', t: 'Exports', d: 'Goods and services produced in one country and sold to customers in another country.', u: 6, tp: '6.3',
  keys: ['goods and services sold abroad', 'produced in the home country'] },
{ id: 'imports', t: 'Imports', d: 'Goods and services bought from producers in another country.', u: 6, tp: '6.3',
  keys: ['goods and services bought from abroad'] },
{ id: 'protectionism', t: 'Protectionism', d: 'The use of government policies such as tariffs and quotas to restrict imports and protect domestic businesses.', u: 6, tp: '6.3',
  keys: ['restricting imports using tariffs and quotas', 'to protect domestic businesses and jobs'] }

];

BS.term = function (id) {
  for (var i = 0; i < BS.glossary.length; i++) if (BS.glossary[i].id === id) return BS.glossary[i];
  return null;
};
